### ISSUE TITLE
Output playlists to their own subdirectory

### ISSUE THREAD

**Issue by filcuk** [alexta69/metube#101]
Is it possible to move playlist downloads to their own subdirectory?

I've tried variations of the following, but that doesn't appear to be working:
`OUTPUT_TEMPLATE=%(playlist_title\,)s%(title)s.%(ext)s`

**Comment by alexta69** [comment]
Frankly I've no idea.. MeTube is using the capabilities provided by yt-dlp for this matter, so there's not much I can do about it. Perhaps you can ask the folks at yt-dlp...

**Comment by PikuZheng** [comment]
yes.

to avoid frequent and slow reads and writes of the destination folder (in smb) during the download, I always download to /tmp and move it to another folder when done
so don't worry about output filename, just move the file after the download is complete, based on the filename

for reference, [here](https://github.com/PikuZheng/metube/commit/5830f2b4fa2f0237847c25f49486b891179f3382#diff-1ee286939f5507d0e261aeb21894ff9b90f7af1900fbf8fe8803bb09440d1db0) is my modification
