### ISSUE TITLE
Facebook videos not working?

### ISSUE THREAD

**Issue by palla89** [alexta69/metube#103]
Hi, I always used meTube also for Facebook videos, until some days ago it started giving me this error:

Error adding URL: ERROR: [facebook] 961367928124127: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

I have the latest docker image. But I don't know if yt-dlp is at latest version

**Comment by alexta69** [comment]
As the message says, it's an issue with the underlying yt-dlp and not with MeTube. Please contact the yt-dlp project.

**Comment by palla89** [comment]
Thank you @alexta69, can I ask you if there is an option to use the bleeding edge yt-dlp? Because of the nature of the websites, they're constantly changing it to avoid downloading, so the develop version of yt-dlp has the fix, but it's not on the main branch. 
To install from Github the command is `python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.zip` 
thank you!

**Comment by alexta69** [comment]
There's a nightly job that checks for updates in yt-dlp, and builds a new version of MeTube if any are found. So if you use something like [watchtower](https://github.com/containrrr/watchtower) to keep your containers updated, you'll always have the latest version of yt-dlp in your MeTube instance.

**Comment by palla89** [comment]
Yes I saw that (and it's awesome) but I think that the job checks for new releases and it's not picking it from the master branch where they commit fresh fixes. I know maybe it's overkill but a setting to use yt-dlp from branch instead of their release could be useful when downloading from Facebook or other social networks that changes continuously their web source. 

Anyway, thank you very much for this awesome project! Couldn't live without it anymore! <3

**Comment by alexta69** [comment]
Glad you like the software! :)
I'm a bit wary of pulling it from master, because I'm afraid that for the small number of cases where it will deliver fixes quicker, it will introduce breakage that will hurt the functionality of everything more often, so I don't feel it's worth the risk.
But one option that can be implemented is creating a second docker image with the master, and then everyone can choose which one they're going to use.

**Comment by davgu** [comment]
How about making it an option when creating the container?
