### ISSUE TITLE
#(%23) isn't encoded in string

### ISSUE THREAD

**Issue by dishapatel010** [alexta69/metube#104]
If title have ```#``` it doesn't get encoded in url as other character gets.

**Comment by alexta69** [comment]
@dishapatel010  Can you paste an example video URL?

**Comment by dishapatel010** [comment]
> @dishapatel010  Can you paste an example video URL?

[Here](https://youtube.com/shorts/SRPFDAkg2Aw)

**Comment by alexta69** [comment]
I'm not sure what the problem is, I put that URL in my MeTube instance and it displayed properly, downloaded properly and was saved with the proper filename.
Can you explain the nature of the problem you're seeing?

**Comment by dishapatel010** [comment]
> I'm not sure what the problem is, I put that URL in my MeTube instance and it displayed properly, downloaded properly and was saved with the proper filename. Can you explain the nature of the problem you're seeing?

It won't get encoded on dashboard & after we click on url it says 404: Not Found coz it's is not in `%23`. But after you make # as %23 in url it work. here is another example https://youtube.com/shorts/Tru3JclULzE

You can test this on my [instance](https://xmetube.herokuapp.com)
