### ISSUE TITLE
Feature request: Download playlists to a subdirectory

### ISSUE THREAD

**Issue by matt-bartel** [alexta69/metube#107]
With yt-dlp it's possible to download a playlist to a subdirectory by providing an output template (example: `%(playlist_title)s/%(title)s.%(ext)s`). Unfortunately that isn't possible with metube since it gets the playlist info then passes each video on to yt-dlp rather than the playlist url, meaning yt-dlp isn't operating in the context of a playlist and the playlist fields can't be used in the output format.

I fixed this for myself by adding a new config option (`PLAYLIST_DIR_TEMPLATE`) but haven't opened a PR for this since it feels wrong to me. Rather than using yt-dlp's output formatting it takes a python format string. [Here's my branch](https://github.com/matt-bartel/metube/tree/playlist-subfolder) if you're interested.

**Comment by alexta69** [comment]
Yeah, I see. Indeed it's not ideal, though I can't think of a better solution at this point... I'll leave it as is for now, and hopefully someday someone will come up with one :)
Thanks!
