### ISSUE TITLE
Renaming Downloaded Videos 

### ISSUE THREAD

**Issue by Hussienfahmy** [alexta69/metube#112]
Can you please add a feature to rename the videos with the same order as it in the playlist 
for example
1 - Video_1.mp4
2 - Video_2.mp4
3 - Video_3.mp4

**Comment by alexta69** [comment]
If someone takes this ticket, please talk to me in advance so we can decide how to do it.

**Comment by PikuZheng** [comment]
try to change OUTPUT_TEMPLATE in ENV. `%(playlist_index)` is the index of the video in the playlist

**Comment by alexta69** [comment]
@PikuZheng this won't work, most likely, for the reasons mentioned in #107 ...
