### ISSUE TITLE
Add yt-dlp merge option for best version

### ISSUE THREAD

**Issue by gilly42** [alexta69/metube#115]
Implement a function like this, please, to get the best video + best audio (merged) version.
 
ytbest () {
  video_type=$(yt-dlp -F "$@" | grep "video only" | awk '{print $2}' | tail -n 1)
  case $video_type in
    mp4)
      yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$@";;
    webm)
      yt-dlp -f 'bestvideo[ext=webm]+bestaudio[ext=webm]' "$@";;
    *)
      echo "new best videoformat detected, please check it out! -> aborted";;
    esac
}

**Comment by PikuZheng** [comment]
it can download webm and megre it with option Quality=best and Format=any

**Comment by PikuZheng** [comment]
> but I have no way to tell metube to download webm or?

I think this part is what yt-dlp provides. Some videos do not exist webm format. At this point if 'best' is selected, the result will be mp4

**Comment by PikuZheng** [comment]
well, If you need to force download a webm (and it will fail if it does not exist), try to modify ui\src\app\formats.ts and \app\dl_formats.py

**Comment by gilly42** [comment]
Well I didnt know it would do that. I tried it an https://www.youtube.com/watch?v=zSmOvYzSeaQ and get only the 720p version.
But there is a 1080p version (its not really better, its just for example).
I hoped it would work like you described it, but then it would download the 1080p version right?

**Comment by gilly42** [comment]
I'll re-check it.

**Comment by PikuZheng** [comment]
> I would expect a download of 248+251 as webm cause for 137 there is no high quallity m4a available....

choose Quality=Best and Format=Any then you'll get a 1080p webm file.

**Comment by gilly42** [comment]
yes `yt-dlp -f 248+251` works

**Comment by alexta69** [comment]
@gilly42 maybe if you run metube locally (and not in the container) and then turn on verbose mode or something? and then perhaps it'll log what it's doing? I'm not sure myself..

**Comment by gilly42** [comment]
I'm on a bit debugging. I use `nikolaik/python-nodejs:python3.8-nodejs16-bullseye` to run it "locally" installed ffmpeg and followed you 'Build and run locally' and its downloaded the webm version ..... not sure how go from here.

**Comment by alexta69** [comment]
On line 71 in ytdl.py you have the initialization of the YoutubeDL object, I'd add a "verbose" flag with a True value to make it more verbose and hopefully it will tell more about the selections of the streams it performs... I've never tried it myself, just a suggestion.

**Comment by gilly42** [comment]
ahhhhhhhh dont hit me......

I've found it ;( It was me I set ` YTDL_OPTIONS={"format":"mp4"}` in my docker-compose.yml

But what see my eyes there youtube put a 1080p mp4 version online
399 mp4   1920x1080   24 │  59.09MiB 1211k https │ av01.0.08M.08 1211k video only              1080p, mp4_dash
137 mp4   1920x1080   24 │  90.43MiB 1854k https │ avc1.640028   1854k video only              1080p, mp4_dash

**Comment by alexta69** [comment]
Doh! OK, glad you found it :)
