### ISSUE TITLE
Question about options

### ISSUE THREAD

**Issue by Ponkhy** [alexta69/metube#125]
Hello,

unfortunately i wasn't able to figure out which parameters i've to use in YTDL_OPTIONS to have 1080p download as the default, since i'm using the MeTube Chrome Extensions and the files will end up in 720p.

Thanks, would be really appreciated if someone could help ^^

**Comment by PikuZheng** [comment]
Looks similar to #115. You don't need to make any modifications to get 1080p from the chrome browser extension.

**Comment by alexta69** [comment]
@Ponkhy can you please give a sample URL in which you're seeing the problem? And are you seeing a different result if you submit it via the MeTube GUI or via the browser extension? Generally, as @PikuZheng mentions, you don't need to specify in the options to get the best quality.

**Comment by Ponkhy** [comment]
Just tested it again, looks like i'm always getting only 720p, via GUI and Browser Extension.

Sample URLs:
https://www.youtube.com/watch?v=tsVsQRmw99E
https://www.youtube.com/watch?v=aetXqd9B8WE

**Comment by alexta69** [comment]
I tried the first one and got a 1080p webm file. It must be something with your settings. Are you sure you have quality "Best" and format "Any" selected?

**Comment by Ponkhy** [comment]
Okay, looks like it has something to do with mp4, which i was setting by default and it does ignore the option you've selected in the Web GUI.
I'd like to just have it at max. 1080p and mp4 but doesn't seem to work, so i guess i just live with it ^^

Thank you all so much anyway and sorry for the inconvenience.

**Comment by alexta69** [comment]
Yes, this video only has 1080p as webm, not as mp4.

**Comment by Ponkhy** [comment]
@alexta69 also thank you a lot for this project, it helps me a lot!

**Comment by PikuZheng** [comment]
>Sample URLs:
>https://www.youtube.com/watch?v=tsVsQRmw99E
>https://www.youtube.com/watch?v=aetXqd9B8WE

well...I got 1080p mp4 (f137) both of these videos. Just right click and left click "Send to MeTube".
Consider ffmpeg problem which converting to mp4 requires it
