### ISSUE TITLE
Ability to set download path

### ISSUE THREAD

**Issue by skobkin** [alexta69/metube#127]
It'd be good and easy to implement an ability to set the download path.

An example of use-case:

- I need to download videos from several channgels (`c1`, `c2`, `c3`)
- I want to save videos from each channel to the separate subdirectory (`/downloads/c1`, `/downloads/c2`, `/downloads/c3`)
- I'm setting the download dir for the `c1`, then entering channel URL, selecting quality and format and clicking "Add".
- Then I'm repeating this for every channel, playlist or separate video I need to download

It's ok to just set the subdirectory of the download folder. But setting full path for each is an option too.

In the current state I can't queue a download of several channels without making a mess in the download directory.

**Comment by PikuZheng** [comment]
try to modify output template (example: %(playlist_title)s/%(title)s.%(ext)s)?

**Comment by alexta69** [comment]
Exactly as @PikuZheng said, this is the way to do it, there's no need to add any additional support to MeTube.

**Comment by skobkin** [comment]
@alexta69 @PikuZheng It's not the same, but for this particular case it'll do the job. Ok, thanks.
