### ISSUE TITLE
Ability to download to a different folder

### ISSUE THREAD

**Issue by oliroe** [alexta69/metube#129]
Hi

I'm aware you can use output templates to direct the downloads to different folders but there's no way to do it with individual vidoes. Say for example I want to download a video that should be in a 'Kids' folder and then download one to 'Music Videos' it's not possible through the frontend

Thanks

**Comment by alexta69** [comment]
Not sure how to do this without clogging the UI (I imagine it's not a very common use case).. Perhaps some expandable panel can be added with "Additional options" or something like that, for this sort of stuff. Leaving the issue open for future thought. Thanks for the idea.

**Comment by alexta69** [comment]
It's a pretty good UX, I haven't thought of using this split button! The question is, where the folder list would come from.

**Comment by oliroe** [comment]
For docker wouldn't it just be your mapped volumes?

**Comment by alexta69** [comment]
I guess sometimes you'd want to save into subfolders under your main downloads directory... so maybe showing all the subfolders there would be a possibility. But I don't know if it'd cover all use cases.

**Comment by jgillman** [comment]
> The question is, where the folder list would come from.

hahaha yeaaaahhh... I'm 90% a front end person but the other 10% of me knows that figuring out where to store the data is the actual hard part! Especially since MeTube is doing config via env vars. Not sure what the best practice here would be but I realize this is a heavier lift that "just add a button."

IDK if the application can "know" what volumes are mounted by Docker or not but that would be a cool hack. I suspect that's not possible though.

**Comment by oliroe** [comment]
But it wouldn't need to know, the user could add them based on the mapped paths

**Comment by jgillman** [comment]
I guess my point was just that there's no stored config outside of env vars so idk how the app would "remember" where it could download to.

Looks like there's some data stored locally in the browser but one would have to re-add the data every time they use a different device/browser.

**Comment by Coyote21** [comment]
Would also like to "+1" this feature and add to the use cases.

I'd use this feature every time I download a playlist. I'm a little surprised that every user does not download a playlist to it's own unique folder.

This is my main use for youtube-dl, to get Let's Plays of various games as a playlist. I then sort the playlist into a folder named after the content creator, itself inside a folder named after the game title. (e.g. downloads/Minecraft/CohnCarnage/)

For now I download the playlist and then manually re-organise the files, which is still easier with metube than it was when I used youtube-dl from the command line, but having the ability to save to a folder would be even better.

**Comment by Coyote21** [comment]
UPDATE: For anyone else wanting this facility, a temporary work around, or possible solution is to use the following environment variables:

OUTPUT_TEMPLATE: "/downloads/%(channel)s/%(playlist_title)s/%(title)s.%(ext)s"

This will download playlists into a new folder structure, under your downloads folder, named after the channel's name and a sub-folder named after the playlists name. e.g. downloads/CohnCarnage/100 Days in Minecraft/

Perhaps others can review the OUTPUT_TEMPLATE documentation to find a similar fix for their own circumstance.

**Comment by jwoglom** [comment]
I just uploaded a PR to add support for this. Please take a look at https://github.com/alexta69/metube/pull/177

A docker image with these changes will also be available at https://hub.docker.com/r/jwoglom/metube as soon as the CI finishes for testing

**Comment by kmanan** [comment]
Any ideas why I am not seeing any folder options load? I installed this via TrueCharts on TrueNAS. I have added a mnt path for the folder I want it to download to but that folder shows nothing. (I have that folder mapped in Plex so was hoping to make a process flow). 
![image](https://user-images.githubusercontent.com/17659155/228131869-a0e9a68f-6698-4742-90f5-368cb56f1837.png)

**Comment by jwoglom** [comment]
@kmanan I think folders will only appear there if any subfolders in the configured download folder. However you can type anything you want there and it will mkdir the folders recursively; then the next time you attempt to download something those newly existent folders should appear

**Comment by kmanan** [comment]
> @kmanan I think folders will only appear there if any subfolders in the configured download folder. However you can type anything you want there and it will mkdir the folders recursively; then the next time you attempt to download something those newly existent folders should appear

Thanks! It was a permissions issue. MeTube's default user assigned by TrueNAS didn't have the permissions. Once I changed it to a user from the admin group, the folder structure showed up.
