### ISSUE TITLE
Feature Request- Allow us to use a GPU to render files

### ISSUE THREAD

**Issue by echodeck99** [alexta69/metube#132]
I'm sorry if i am not suggesting this correctly, this i my first post.

Would benefit with the ability to use a GPU to render/transcode/encode files.

**Comment by alexta69** [comment]
This project is just a UI frontend for [yt-dlp](https://github.com/yt-dlp/yt-dlp), which is the actual downloader. It in turn uses ffmpeg for muxing and transcoding. So the GPU usage would have to be implemented in ffmpeg (maybe it already is, I don't know), and supported by yt-dlp. If/when that happens, MeTube will inherit this support automatically.
