### ISSUE TITLE
writeinfojson help needed

### ISSUE THREAD

**Issue by binarygeek119** [alexta69/metube#134]
i want to use writeinfojson to write the videos jsons so i can then convert them into nfo for use with emby.
below is what i setup, but some video now wont download and some will.

`{"writeinfojson":true,"writesubtitles":true,"subtitleslangs":["en","-live_chat"],"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true}]}`

the error i get 

```
INFO:ytdl:adding https://www.youtube.com/playlist?list=PLfABUWdDse7bnyQ_0K2OgmQxmJaAFV_Uy
ERROR: Cannot write playlist metadata to JSON file Gadgets [PLfABUWdDse7bnyQ_0K2OgmQxmJaAFV_Uy].info.json
```

**Comment by PikuZheng** [comment]
As far as I know metube will first parse the playlist into several individual videos and add them to the download queue. 
I guess a playlist does not have some infomation. try try....cache.... to avoid errors if you'r using python.

**Comment by alexta69** [comment]
Closing (please reopen if there's still an issue)
