### ISSUE TITLE
Feature request:  Option for Playlist name to be used as subdirectory

### ISSUE THREAD

**Issue by forkless** [alexta69/metube#135]
Would be nice to have an option where a (sanitized) playlist name can be used to structure downloads a bit better.

**Comment by alexta69** [comment]
You can use variables like `%(playlist_title)s` in the `OUTPUT_TEMPLATE` environment variable to achieve this functionality.

**Comment by forkless** [comment]
Shame on me for not checking the environment variables fully yet. 

Thanks for the response. =)
