### ISSUE TITLE
FR: Convert to mp4?

### ISSUE THREAD

**Issue by gerroon** [alexta69/metube#138]
Hi

It would be great if the extension submitted video is converted to .mp4 optionally.

thanks

**Comment by MrZomka** [comment]
Just set the format as MP4.

**Comment by gerroon** [comment]
I am using the extension, there does not seem to be a way to set it to mp4

**Comment by PikuZheng** [comment]
yes the problem does exist. I use this modification to make the default format mp4 for myself:
https://github.com/PikuZheng/metube/commit/d891f0b7ebdc03a5a1b8f267552c936f5d367e9b

**Comment by AIR495** [comment]
Is there a way to default it to use mp4 for the format rather then Any

**Comment by PikuZheng** [comment]
>Is there a way to default it to use Quality: Best and Format: mp4 rather then having to select from 'Any' each time

Quality: Best  is the default value for this page. 
Format: mp4 will use cookies to remember when you choose  once.
So please enable browser cookies for metube.
