### ISSUE TITLE
Tiktok videos not working

### ISSUE THREAD

**Issue by Tonynks** [alexta69/metube#145]
Have to copy TikTok link into browser then it will make a new link.  Once the new link is copied into metube it works.

**Comment by alexta69** [comment]
MeTube is just a GUI wrapper for yt-dlp. Please check if it works with yt-dlp command line. If it doesn't, contact that project. If you find something that works with yt-dlp command line, but doesn't work with MeTube, then feel free to reopen.
Thanks
