### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JalenMak6** [alexta69/metube#150]
Wont it be possible to setup a credential authentication for accessing the web UI?
that will be great if it is exposed to the public and Others are not allowed to put the link and download to your server.

**Comment by PikuZheng** [comment]
My metube is on the internet and just takes the secondary path (for ifttt). According to the access logs, no one has guessed the correct path so far. So they will just get a 404.
I think metube is safe as long as address and path are not recorded in public.

**Comment by PikuZheng** [comment]
Additional use of nginx, adding https and auth_basic may be a better solution.

**Comment by alexta69** [comment]
There are very good existing authentication solutions, so I don't think it's the business of MeTube to reimplement them. The [linuxserver/swag](https://docs.linuxserver.io/general/swag) image for example offers Authelia for this purpose. So this sort of thing isn't coming to MeTube in the foreseeable future.
