### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by johngo54** [alexta69/metube#152]
Had been running metube on a Synology NAS with UID and GID set to specific values. The NAS also runs Watchtower and that resulted in an automatic update of the metube image. However, this failes to runs because of permission error. It looks as if recreating the container ignores both environment variables UID and GID and uses defaults (1000 and 1000).
Also, completely removing the container and the image and pulling a new one and running it with the specific UID and GID values still results in the metube container running under 1000 and 1000.
I am a relative newbie on docker and stuff, so please be patient. Thanks

**Comment by johngo54** [comment]
Ah! Found it! Previously the environment variables were called PUID en PGID. Changed them to UID and GID and it works again!

**Comment by alexta69** [comment]
They were never PUID and PGID, previously the `user` parameter of docker was used (and it's still supported for backwards compatibility). If you used to set PUID and PGID, then they had no effect... Anyway, glad that it works for you now :)

**Comment by johngo54** [comment]
Ah, another thing I learned today.

The docker run command I used was taken from mariushosting.com. This (P)UID thing may affect other applications as well for which he put info on his website.

Anyway, good to know this. Thanks for your reply.

(Needless to say I love metube)

John

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
