### ISSUE TITLE
Unable to download webpage: <urlopen error [Errno 99] Address not available

### ISSUE THREAD

**Issue by isaac574** [alexta69/metube#153]
stdout: Setting umask to 022
stdout: Creating download directory /downloads and state directory /downloads/.metube
stdout: Changing ownership of download and state directories to 1000:1000
stdout: Running MeTube as user 1000:1000
stderr: DEBUG:asyncio:Using selector: EpollSelector
stderr: INFO:ytdl:waiting for item to download
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET / HTTP/1.1" 200 235 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /runtime.6d606955289fb68ac11a.js HTTP/1.1" 200 248 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /polyfills.33354513befd4a9a69e2.js HTTP/1.1" 200 250 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /styles.85f191ecb2f9ab82fca0.css HTTP/1.1" 200 238 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /main.7864a51b9220d3fad5ba.js HTTP/1.1" 200 252 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /socket.io/?EIO=4&transport=polling&t=O68tU4B HTTP/1.1" 200 288 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "POST /socket.io/?EIO=4&transport=polling&t=O68tU52&sid=ZQpx4mAUPDS42XGUAAAA HTTP/1.1" 200 277 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /socket.io/?EIO=4&transport=polling&t=O68tU53&sid=ZQpx4mAUPDS42XGUAAAA HTTP/1.1" 200 244 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /favicon/favicon.ico HTTP/1.1" 200 252 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:aiohttp.access:192.168.1.247 [22/Jun/2022:00:44:17 +0000] "GET /socket.io/?EIO=4&transport=polling&t=O68tU5V&sid=ZQpx4mAUPDS42XGUAAAA HTTP/1.1" 200 191 "http://192.168.1.119:8081/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"
stderr: INFO:ytdl:adding https://www.youtube.com/watch?v=yAYIaTP63GY
stderr: WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 99] Address not available>
stderr: WARNING: [youtube] <urlopen error [Errno 99] Address not available>. Retrying ...
stderr: WARNING: [youtube] <urlopen error [Errno 99] Address not available>. Retrying ...
stderr: WARNING: [youtube] <urlopen error [Errno 99] Address not available>. Retrying ...
stderr: WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 99] Address not available>

**Comment by PikuZheng** [comment]
感觉是你的网的问题。。进docker内测一下youtub能打开不
另外他的视频直接从b站取不好嘛 ytdl可以下载b站视频的

**Comment by isaac574** [comment]
> 感觉是你的网的问题。。进docker内测一下youtub能打开不 另外他的视频直接从b站取不好嘛 ytdl可以下载b站视频的

谢了，兄弟。
\英文听力>youtube-dl.exe https://www.youtube.com/watch?v=y
AYIaTP63GY
[youtube] yAYIaTP63GY: Downloading webpage
[download] Destination: 福建舰的“电磁弹射”技术是什么？为何能巨幅提升航母战斗力
？-yAYIaTP63GY.f299.mp4
[download] 100% of 243.34MiB in 51:29
***这个会的。不就是折腾吗？

**Comment by PikuZheng** [comment]
容器内的网络和容器外的不一样的。所以说你进容器内测一下

**Comment by PikuZheng** [comment]
另外你用的windows的容器吗？

**Comment by isaac574** [comment]
> 容器内的网络和容器外的不一样的。所以说你进容器内测一下

在OPENWRT内DOCKER容器。

**Comment by isaac574** [comment]
> 另外你用的windows的容器吗？

NO, IT'S A CONTAINER  OF DOCKER THAT IS INSTALLED IN OPENWRT FIRMWARE;

**Comment by PikuZheng** [comment]
> 在OPENWRT内DOCKER容器。

那你需要考虑两个问题，一是openwrt“代理自身”，二是容器内的dns，可能被污染了。简单的用metube下载一个b站视频试试通不通

**Comment by isaac574** [comment]
> > 在OPENWRT内DOCKER容器。
> 
> 那你需要考虑两个问题，一是openwrt“代理自身”，二是容器内的dns，可能被污染了。简单的用metube下载一个b站视频试试通不通

***metube下载不了任意一个b站视频

**Comment by isaac574** [comment]
> openwrt“代理自身”

这个没有问题，不然不会是OPENWRT。

**Comment by PikuZheng** [comment]
那没办法了 进container内测ping，测路由吧。估计是单向了

**Comment by isaac574** [comment]
> 二是容器内的dns，可能被污染了

这个真不会。

**Comment by isaac574** [comment]
> 那没办法了 进container内测ping，测路由吧。估计是单向了

这个真不会。汗！

**Comment by PikuZheng** [comment]
```
docker inspect 容器名或id | grep Pid
```
拿到pid一般是几位数字
```
nsenter --target "上面得到的pid" --mount --uts --ipc --net --pid /bin/sh
```

进去以后ping，traceroute或nslookup测一圈，看看数据报怎么走的

**Comment by isaac574** [comment]
> ```
> docker inspect 容器名或id | grep Pid
> ```
> 
> 拿到pid一般是几位数字
> 
> ```
> nsenter --target "上面得到的pid" --mount --uts --ipc --net --pid /bin/sh
> ```
> 
> 进去以后ping，traceroute或nslookup测一圈，看看数据报怎么走的

FINE.

**Comment by isaac574** [comment]
PING得通163.COM & OPENWRT.ORG & APNEWS.COM & ALIYUN.COM，PING不能YOUTUBE.COM & WWW.YOUTUBE.COM & GOOGLE.COM

**Comment by PikuZheng** [comment]
https://v.youku.com/v_show/id_XNTIwMzMwNjc2OA==.html
 这个呢？如果下载不了，报什么错误？

**Comment by isaac574** [comment]
> https://v.youku.com/v_show/id_XNTIwMzMwNjc2OA==.html

下得飞快。

**Comment by isaac574** [comment]
![image](https://user-images.githubusercontent.com/59785107/175004700-1b198f1f-1e95-4896-81fe-0559b9b15571.png)

**Comment by PikuZheng** [comment]
那便还是gfw或dns的问题了

**Comment by PikuZheng** [comment]
Mainland of China's unique international internet access problem. issue could be closed. @alexta69

**Comment by isaac574** [comment]
> 那便还是gfw或dns的问题了 如果b站也有问题，那么可能还有bili漫游之类的问题，也可能是 helloword 的 ShadowsocksR Plus+ ，总之你从openwrt自身到youtube应该就是不可达

我访问YOUTUBE总要靠OPENWRT的。我DNS是用ADGUARD的。
