### ISSUE TITLE
Video Downloads Failing

### ISSUE THREAD

**Issue by cochraneserver** [alexta69/metube#156]
https://www.youtube.com/watch?v=Kr-17BIsihc

INFO:ytdl:adding https://www.youtube.com/watch?v=Kr-17BIsihc
INFO:ytdl:downloading DJ Dan ‎– Another Late Night
INFO:aiohttp.access:192.168.2.3 [01/Jul/2022:18:25:27 +0000] "POST /add HTTP/1.1" 200 265 "http://192.168.2.6:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37"
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 37: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 36: HTTP Error 404: Not Found

I updated to the latest metube today and issue still occuring, any ideas?

**Comment by alexta69** [comment]
This video downloads just fine here.

In your log it looks like it's complaining about thumbnails, have you set something in YTDL_OPTIONS that has to do with that? Perhaps try with an empty YTDL_OPTIONS.

Either way, if there's a problem, it looks like it's got to do with yt-dlp (for which MeTube is just a GUI wrapper) and not MeTube itself. So I'm closing the issue for now. Please try debugging with yt-dlp command line; if you figure it's a problem with MeTube and not just yt-dlp, please feel free to reopen!
