### ISSUE TITLE
config file location

### ISSUE THREAD

**Issue by Goldmaster** [alexta69/metube#158]
Hi there, Im in the works of setting this up and im currently wondering where the config file is?

https://github.com/yt-dlp/yt-dlp#configuration=

the only config file I see is in the AppData folder on unraid, do I just create a yt-dlp.conf or quite what?

**Comment by alexta69** [comment]
You configure yt-dlp using the `YTDL_OPTIONS` environment variable instead of a config file, as described in https://github.com/alexta69/metube#configuration-via-environment-variables.
