### ISSUE TITLE
Feature Request: Multiple Download destinations

### ISSUE THREAD

**Issue by LeLunZ** [alexta69/metube#159]
Wouldn't it be nice to have multiple locations where you can store your videos automatically?

Just like the option "Quality" or "Format", it would be cool to have an option for self configured download destinations. (through a config)

If you agree I can also take a look at the code and open a PR for it :)

**Comment by alexta69** [comment]
I don't know how common is the use case of having multiple download destination folders. Let's leave the issue open and see if anyone else also wants it. I'm trying to avoid over-complicating the software and especially the UI...

**Comment by LeLunZ** [comment]
Sure no problem 👍

**Comment by alexta69** [comment]
Implemented in #177 .
