### ISSUE TITLE
Feature: Multi Download / Format: Mp3

### ISSUE THREAD

**Issue by Dr4g0nM4st3r** [alexta69/metube#16]
Hello, 

i extend your very nice Script to download Youtube Videos and Convert it to MP3 with ffpmeg.

Could you extend the GUI to download multiple videos at one (parallel not serial) ?
Example: when i add a Playlist than he could run x downloads at the same time and converte the webm files to mp3. :) 

thank you. 

regards 
Pascal

**Comment by alexta69** [comment]
Hi Pascal,
I don't think I'll be able to find time to do this, but you're very welcome to submit a pull request with code that does it, and I'll be glad to merge it into MeTube.
If you decide to write the code, let's talk beforehand so we can sync on what's the best way to do it.
Thanks
Alex
