### ISSUE TITLE
Auth on Web UI

### ISSUE THREAD

**Issue by arjung24** [alexta69/metube#163]
Is there any way to apply auth (username and password) in metube Web UI??

**Comment by alexta69** [comment]
Use "username" and "password" parameters in YTDL_OPTIONS (https://github.com/alexta69/metube#configuration-via-environment-variables).

**Comment by arjung24** [comment]
> Use "username" and "password" parameters in YTDL_OPTIONS (https://github.com/alexta69/metube#configuration-via-environment-variables).

It would be great help if you give me an example of that parameter in YTDL_OPTIONS (how to write?)

**Comment by alexta69** [comment]
`{"username": "myser", "password": "mypass"}`

**Comment by arjung24** [comment]
> `{"username": "myser", "password": "mypass"}`

Thanks a lot brother

**Comment by suntong** [comment]
> Use "username" and "password" parameters in YTDL_OPTIONS

hmm..., 

> `YTDL_OPTIONS`: _Additional options to pass to youtube-dl_

@arjung24, did you asked for _youtube-dl_ username and password or the username and password for the _metube Web UI_ instead?

**Comment by suntong** [comment]
Would you share your way to apply auth (username and password) in metube Web UI please @arjung24 ?
