### ISSUE TITLE
Help with formatting of docker compose to ignore errors

### ISSUE THREAD

**Issue by cochraneserver** [alexta69/metube#164]
Hi, Wondering if someone could help me with the proper formatting, as this is not working. According to the logs it is an invalid option.

Everything bolded is working fine. Thanks.

**version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /mnt/media/Downloads/MeTube:/downloads
    environment:
      UID: 1000
      GID: 1002**
      YTDL_OPTIONS: "{ignoreerrors:true}"

**Comment by PikuZheng** [comment]
This looks suspicious, due to the lack of necessary line-starting spaces

**Comment by PikuZheng** [comment]
>YTDL_OPTIONS: "{ignoreerrors:true}"

---->

```
'YTDL_OPTIONS={"ignoreerrors":"true"}'
```
json in options for your infomation

**Comment by PikuZheng** [comment]
#102

**Comment by cochraneserver** [comment]
The formatting got messed up when I copied my docker-compose file, correct. This did resolve my problem though - thank you.
