### ISSUE TITLE
feature request: set modification time

### ISSUE THREAD

**Issue by shalak** [alexta69/metube#166]
Currently, the file modification time is set to the upload time of the video. Would be great to have a possibility to change that to download time.

**Comment by alexta69** [comment]
MeTube is just a GUI for yt-dlp, so if this feature is to be implemented, it would have to be done in yt-dlp and not in MeTube. Maybe it even already has such a feature, I suggest you check the yt-dlp documentation.

**Comment by PikuZheng** [comment]
In general, the file "create time" is the video release time; the "modify time" is the video download time; the date in the filename template (%(upload_date)) is the video upload date (may be different from the release date, such as scheduled release).
If the "modify time" cannot be satisfied, try other download tools (such as aria2c). This will make both the file create and modify time to the video download time.

**Comment by shalak** [comment]
@PikuZheng 
>  If the "modify time" cannot be satisfied, try other download tools (such as aria2c). This will make both the file create and modify time to the video download time.

Thanks for the tip. However, I'm not sure if I follow. Correct me if I'm wrong:
- I see that `aria2` is installed in `Dockerfile`, so I'm good to go? No need to fork the `Dockerfile`?
- I understand to use it, I need to pass `{"downloader":"aria2c"}` in `YTDL_OPTIONS`, right?

What else? How do I tell the downloader how to behave?

**Comment by PikuZheng** [comment]
`YTDL_OPTIONS={"external_downloader":"aria2c"}` 

https://github.com/alexta69/metube/issues/67#issuecomment-1213627110 fyi
