### ISSUE TITLE
rate_limit does only accepts bytes and not "5M" or "500K"

### ISSUE THREAD

**Issue by templehasfallen** [alexta69/metube#167]
It seems that currently the YTDL_OPTIONS option "ratelimit" only seems to accept values in form of bytes.

If used as such, it errors:
{"ratelimit":"3M"}

> 2022-08-20 13:36:05.017873+00:00Traceback (most recent call last):
> 2022-08-20 13:36:05.017889+00:00File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
> 2022-08-20 13:36:05.017902+00:00self.run()
> 2022-08-20 13:36:05.017913+00:00File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
> 2022-08-20 13:36:05.017963+00:00self._target(*self._args, **self._kwargs)
> 2022-08-20 13:36:05.017978+00:00File "/app/app/ytdl.py", line 71, in _download
> 2022-08-20 13:36:05.017991+00:00ret = yt_dlp.YoutubeDL(params={
> 2022-08-20 13:36:05.018003+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3264, in download
> 2022-08-20 13:36:05.018025+00:00self.__download_wrapper(self.extract_info)(
> 2022-08-20 13:36:05.018038+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3237, in wrapper
> 2022-08-20 13:36:05.018050+00:00res = func(*args, **kwargs)
> 2022-08-20 13:36:05.018061+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1399, in extract_info
> 2022-08-20 13:36:05.018082+00:00return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
> 2022-08-20 13:36:05.018094+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
> 2022-08-20 13:36:05.018106+00:00return func(self, *args, **kwargs)
> 2022-08-20 13:36:05.018118+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
> 2022-08-20 13:36:05.018140+00:00return self.process_ie_result(ie_result, download, extra_info)
> 2022-08-20 13:36:05.018152+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
> 2022-08-20 13:36:05.018164+00:00ie_result = self.process_video_result(ie_result, download=download)
> 2022-08-20 13:36:05.018185+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2648, in process_video_result
> 2022-08-20 13:36:05.018197+00:00self.process_info(new_info)
> 2022-08-20 13:36:05.018209+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2900, in process_info
> 2022-08-20 13:36:05.018232+00:00sub_files = self._write_subtitles(info_dict, temp_filename)
> 2022-08-20 13:36:05.018245+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3871, in _write_subtitles
> 2022-08-20 13:36:05.018257+00:00self.dl(sub_filename, sub_copy, subtitle=True)
> 2022-08-20 13:36:05.018269+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2846, in dl
> 2022-08-20 13:36:05.018291+00:00return fd.download(name, new_info, subtitle)
> 2022-08-20 13:36:05.018303+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 457, in download
> 2022-08-20 13:36:05.018315+00:00ret = self.real_download(filename, info_dict)
> 2022-08-20 13:36:05.018336+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 370, in real_download
> 2022-08-20 13:36:05.018350+00:00return download()
> 2022-08-20 13:36:05.018361+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 286, in download
> 2022-08-20 13:36:05.018374+00:00self.slow_down(start, now, byte_counter - ctx.resume_len)
> 2022-08-20 13:36:05.018392+00:00File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 194, in slow_down
> 2022-08-20 13:36:05.018405+00:00if speed > rate_limit:
> 2022-08-20 13:36:05.018417+00:00TypeError: '>' not supported between instances of 'float' and 'str'

It only works with {"ratelimit":3000000}

**Comment by alexta69** [comment]
Please reopen this issue for the yt-dlp project, since MeTube is just a GUI for yt-dlp, and the contents of the YTDL_OPTIONS goes directly to yt-dlp.

**Comment by PikuZheng** [comment]
According to the description of yt-dlp:
>ratelimit: Download speed limit, in bytes/sec.

 you need to fill in a float number without any letters
