### ISSUE TITLE
Completed Video Link does not know about -P YTLD_Option

### ISSUE THREAD

**Issue by smdion** [alexta69/metube#168]
Not sure if anyone but me is using this, but I think it would be an easy fix.

I have the following in YTDL_OPTIONS: {"paths": {"temp" : "/downloads/temp/", "home": "/downloads/"}}

This way the video won't show up in the downloads location until its finished downloading (and stop confusing plex).  When I click on the link in the MeTube WebUI under Completed, it still has the /temp/ in the URL and does not update that the file has been moved.

My OUTPUT_TEMPLATE is - "%(extractor_key)s/%(uploader)s - %(upload_date)s - %(title)s - %(id)s.%(ext)s"  which allows the videos to be put into subfolders based on the extractor (youtube/twitch/etc).  This way I can point plex at the extract folder and it won't see anything in ./temp/

I don't use that functionality so its not a big deal, just thought I'd report it.

**Comment by PikuZheng** [comment]
set docker env `DOWNLOAD_DIR` to `/downloads` please

**Comment by smdion** [comment]
Added ENV DOWNLOAD_DIR to /downloads and no change.

**Comment by PikuZheng** [comment]
sorry to hear that :(

**Comment by smdion** [comment]
Thanks for the idea.  The README does state that is the default in a docker container, but was worth a shot!

**Comment by alexta69** [comment]
Duplicate of #239
