### ISSUE TITLE
ios shortcuts for metube

### ISSUE THREAD

**Issue by Yumega** [alexta69/metube#169]
the chrome addons is nice, is there a ios shortcuts for metube?

**Comment by rithask** [comment]
I can help with this

**Comment by Yumega** [comment]
> I can help with this

please help😄

**Comment by rithask** [comment]
There you go. Do let me know if anything goes wrong.

https://www.icloud.com/shortcuts/f1548df15b734418a77a709103bc1dd5

**Comment by Yumega** [comment]
> There you go. Do let me know if anything goes wrong.
> 
> [icloud.com/shortcuts/f1548df15b734418a77a709103bc1dd5](https://www.icloud.com/shortcuts/f1548df15b734418a77a709103bc1dd5)

Thanks a lot , it works very well

**Comment by rithask** [comment]
Okay. I'll create a PR to add this to README

**Comment by rithask** [comment]
https://www.icloud.com/shortcuts/a1bf01b290fd46088da3621037f9e309

This should work. Can you check it?

**Comment by rithask** [comment]
i've wanted a shortcut like that for a long time but i don't think that's possible since the yt-dl script requires a linux environment to run which is not possible with iOS Shortcuts. 

wil let you know if i found some solution

**Comment by rithask** [comment]
@Yumega checkout [SW-DLT](https://github.com/net00-1/SW-DLT). it might fit your needs
