### ISSUE TITLE
Upgrade Docker container to FFmpeg 5.1?

### ISSUE THREAD

**Issue by bdr99** [alexta69/metube#173]
I noticed that the latest Docker image is still bundled with FFmpeg 5.0.1. FFmpeg 5.1 was released on July 22 and includes a fix for the frustrating issue noted in https://github.com/alexta69/metube/issues/63. Is there any chance that the FFmpeg version in the Docker image could be updated to 5.1? Thanks!

**Comment by PikuZheng** [comment]
mine is ffmpeg version 4.4.1, why -_-|

**Comment by bdr99** [comment]
@PikuZheng Hmm, maybe you're running an old version of the docker image? I just pulled the latest image today and it came with version 5.0.1.

**Comment by PikuZheng** [comment]
try this modify if you really want (not official version
https://github.com/alexta69/metube/commit/90eba5cd121aaac176aa9d23f32e02c4e03a86e4

**Comment by PikuZheng** [comment]
You are right, I investigated that alpine-3.16 provides ffmpeg 5.0.1, alpine-edge provides ffmpeg 5.1.
But the python official image only provides alpine stable, not edge.
I found a [static compilation of ffmpeg 5.1](https://github.com/wader/static-ffmpeg), but may be it's unstable

**Comment by bdr99** [comment]
Thanks for the investigation. I'm going to try building an image with the Dockerfile changes from the commit you linked above.

**Comment by bdr99** [comment]
That worked perfectly! Thanks again.

Is there any chance we can get these changes included in the MeTube image which is pushed to Docker Hub (so I don't need to build a new image every time MeTube changes)? Or do we need to wait for alpine to update their FFmpeg version?

**Comment by PikuZheng** [comment]
Due to unstable builds, I tend to wait for official updates. You can fork this project and use the github action to automatically sync and build the docker image and push it to the private docker hub.
