### ISSUE TITLE
Docker container  No such device: '/downloads/.metube/queue'

### ISSUE THREAD

**Issue by hejl233** [alexta69/metube#174]
I can't start when I use a network drive as a file

_gdbm.error: [Errno 19] No such device: '/downloads/.metube/queue'

**Comment by PikuZheng** [comment]
your source and destination files are reversed while mounting

**Comment by alexta69** [comment]
@hejl233 has your problem been solved? If not, please detail exactly what you're trying to do (what sort of network drive is the most important info I guess)

**Comment by alexta69** [comment]
Closing; if the problem persists, please reopen (and supply more details).

**Comment by lostage** [comment]
Hello, I'm receiving this exact error. I see that the docker container has created the `/downloads/.metube/queue` file (I can see it, and if I delete the file, metube recreates it), but the container keeps erroring with that message and restarting. Here's the compose:

```
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8110:8081"
    volumes:
      - /mnt/storage/downloads/youtube:/downloads
```

`/mnt/storage` is mergerfs, if that matters.

And here's the exact error:

```
Setting umask to 022
Creating download directory /downloads and state directory /downloads/.metube
Changing ownership of download and state directories to 1000:1000
Running MeTube as user 1000:1000
Traceback (most recent call last):
  File "app/main.py", line 75, in <module>
    dqueue = DownloadQueue(config, Notifier())
  File "/app/app/ytdl.py", line 195, in __init__
    self.queue = PersistentQueue(self.config.STATE_DIR + '/queue')
  File "/app/app/ytdl.py", line 150, in __init__
    with shelve.open(path, 'c'):
  File "/usr/local/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 19] No such device: '/downloads/.metube/queue'
```

**Comment by PikuZheng** [comment]
> /mnt/storage is mergerfs, if that matters.

yes. looks you need to add mergerfs package in the container

**Comment by lostage** [comment]
I'm unsure how to do that, so I just pointed it at one of the disks in the array which works well enough for me. Thank you!
