### ISSUE TITLE
.cache - Permission issue

### ISSUE THREAD

**Issue by LukePWilkins** [alexta69/metube#180]
When downloading a YT video, I receive the following lines in the log file
File "/usr/local/lib/python3.8/site-packages/yt_dlp/cache.py", line 44, in store
today at 10:02:19 AM    os.makedirs(os.path.dirname(fn))
today at 10:02:19 AM  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
today at 10:02:19 AM    makedirs(head, exist_ok=exist_ok)
today at 10:02:19 AM  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
today at 10:02:19 AM    makedirs(head, exist_ok=exist_ok)
today at 10:02:19 AM  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
today at 10:02:19 AM    mkdir(name, mode)
today at 10:02:19 AMPermissionError: [Errno 13] Permission denied: '/.cache'

Unsure where to set the cache location to ensure permissions are correct

**Comment by PikuZheng** [comment]
I believe it is related to the user. If you are running it on Synology, find the administrator user's gid & pid and set it

**Comment by alexta69** [comment]
Are you sure you haven't changed anything in the docker image / python files? The code as it is disables the cache directory (https://github.com/alexta69/metube/blob/master/app/ytdl.py#L80), and indeed nobody else is getting this behavior (even though metube runs without root privileges, so it really can't create /.cache).

**Comment by LukePWilkins** [comment]
Interesting. I expected it to be user related. I will double check the user. 
Thanks for the replies.

**Comment by 3guboff** [comment]
> Are you sure you haven't changed anything in the docker image / python files? The code as it is disables the cache directory (https://github.com/alexta69/metube/blob/master/app/ytdl.py#L80), and indeed nobody else is getting this behavior (even though metube runs without root privileges, so it really can't create /.cache).

The problem exists, to reproduce, use some 4k video from youture:
```metube    | INFO:ytdl:adding https://www.youtube.com/watch?v=XXX: quality='best' format='any' already=None folder=None
metube    | WARNING: Writing cache to '/.cache/yt-dlp/youtube-nsig/4bbf8bdb.json' failed: Traceback (most recent call last):
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/cache.py", line 44, in store
metube    |     os.makedirs(os.path.dirname(fn))
metube    |   File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
metube    |     makedirs(head, exist_ok=exist_ok)
metube    |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
metube    |     mkdir(name, mode)
metube    | PermissionError: [Errno 13] Permission denied: '/.cache/yt-dlp'
metube    |
metube    | INFO:ytdl:downloading XXX
metube    | ======== Running on http://0.0.0.0:8081 ========
metube    | (Press CTRL+C to quit)
metube    | INFO:aiohttp.access:172.20.0.1 [25/Oct/2022:18:38:59 +0000] "POST /add HTTP/1.1" 200 264 "https://metube.my.site/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
metube    | INFO:ytdl:waiting for item to download```

**Comment by PikuZheng** [comment]
Confirmed that the current latest version has this problem @alexta69

**Comment by alexta69** [comment]
Very strange. We're disabling the cache, so it's not supposed to it. In some videos it tries to use cache anyway? Can you provide a sample URL?

**Comment by 3guboff** [comment]
> Very strange. We're disabling the cache, so it's not supposed to it. In some videos it tries to use cache anyway? Can you provide a sample URL?

Any video, for [example](https://www.youtube.com/watch?v=LXb3EKWsInQ)

**Comment by alexta69** [comment]
Yes, I can see it happening too. Looked a bit into it, and it looks like a yt-dlp bug: we're passing cachedir=False, and there's a check for that in their Cache object, but apparently there's a Cache somewhere that's initialized without the yt-dlp options, so it continues with the default values.

In any case, I see the video downloads fine despite the error. So I guess it's not that urgent to fix. If someone has some time to try to trace the call and find the Cache object that misbehaves, I suppose a fix can be submitted to yt-dlp.

**Comment by 1RandomDev** [comment]
But why are you guys trying to disable the caching feature of yt-dlp? Why not just create the missing directory in the container with `RUN mkdir /.cache && chmod 777 /.cache` or of course you can also mount it to the host to make the cache survive updates?

**Comment by The-May** [comment]
@alexta69 Any updates on this?
 Stll getting PermissionError: [Errno 13] Permission denied: '/.cache' 
D
 
 My docker-compose is following:
```
version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /etc/youtube_metube:/downloads
```

It doesnt matter which directory I use.
Can a temporary env variable be set?

**Comment by 1RandomDev** [comment]
Where exactly did you add the line `RUN mkdir /.cache && chmod 777 /.cache` in the Dockerfile? And did you really use the image that you build yourself? It looks like you specified the url `ghcr.io/alexta69/metube` for the official one.

If you want to have a persistent cache (recommend) that you need to add `- /etc/youtube_metube/cache:/.cache` to the docker-compose.yml and make sure that the directory has file mode 777.
