### ISSUE TITLE
File path length can exceed limit when downloading

### ISSUE THREAD

**Issue by yanjulang** [alexta69/metube#184]
I tried to download a video from twitter which resulted in a file name something like /download/"username - tweet" and exceeded the file path limit (from what I found out it seems to be 242 in docker containers in general [or linux, i really don't know :/ ])

![grafik](https://user-images.githubusercontent.com/29413262/192579922-60851a48-6cac-4cdd-81ee-5e3040e56875.png)

Idk if this is a problem with yt-download or if this can be fixed by metube

**Comment by PikuZheng** [comment]
oh

**Comment by PikuZheng** [comment]
not really need. just set OUTPUT_TEMPLATE as python string-format. 
for example, `%(title).50s` (default is `%(title).s`) means cut title to 50 letters which is suitable for most file system

**Comment by yanjulang** [comment]
works 👍
maybe there should be some default limit tho since this might happen to others too

**Comment by alexta69** [comment]
I tend to follow yt-dlp and not set a default length limit. Closing the issue for now, thanks @PikuZheng !
