### ISSUE TITLE
YouTube video albums directory

### ISSUE THREAD

**Issue by Luis-Lourenco** [alexta69/metube#185]
Hello,

I'm using this app for a long time, but I try to download from YouTube music, canoe arranged with directories to each album of artist?

thank you.

**Comment by PikuZheng** [comment]
why not click the triangle on the right of the download button and specify a subfloder?

**Comment by Luis-Lourenco** [comment]
I'm using a docker version. 

and I'm using direct album from YouTube music. 

when the link is only the artist, link https://music.youtube.com/channel/UCuS6rPVZGwLbWrqkgaHywrg, it really downloads everything to a single folder. its not a big problem, because the ID3 tags are write correctly and with MP3Tag can easily arranje by artist/album/song. 

but when download music from different album, but the same song with variants, the nam already exist and it cancel download and it fails also. 

I'm sorry, but I'm used to Lidarr.

<img width="772" alt="Screenshot 2022-10-04 at 08 00 42" src="https://user-images.githubusercontent.com/29854768/193755092-5e1f93ae-5302-4c19-a4cc-0596ee045300.png">

**Comment by PikuZheng** [comment]
oh, an update last week.

**Comment by alexta69** [comment]
@Luis-Lourenco you can also try setting a custom `DOWNLOAD_DIR` with the album information, as detailed [here](https://github.com/yt-dlp/yt-dlp/blob/master/README.md#output-template:~:text=Available%20for%20the%20media%20that%20is%20a%20track%20or%20a%20part%20of%20a%20music%20album%3A).
