### ISSUE TITLE
Using Sponsorblock

### ISSUE THREAD

**Issue by thoj** [alexta69/metube#187]
Hi

Can I / how do I enable sponsorblock?

I have tried a few different YTDL_OPTIONS:

  {"postprocessors":[{"key":"ModifyChapters", "remove_sponsor_segments":"all"}]}

In different variations. But it does nothing. 

https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/postprocessor/modify_chapters.py

Any help?

**Comment by PikuZheng** [comment]
You need to mark Sponsor blocks first, then remove them. try
```
{ "postprocessors":[ {"key":"SponsorBlock","categories":["sponsor"]}, {"key":"ModifyChapters","remove_sponsor_segments":["sponsor"]} ] }
```

**Comment by thoj** [comment]
Hm.. Seems like something is happening but i got this error in the log:

metube       | INFO:aiohttp.access:172.18.0.5 [09/Oct/2022:08:56:03 +0000] "POST /add HTTP/1.1" 200 266 "https://xxx/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0" │··············
ERROR: Postprocessing: Conversion failed!

Config:

{"key":"SponsorBlock","categories":["sponsor"]}, {"key":"ModifyChapters","remove_sponsor_segments":["sponsor"]} ] }

**Comment by PikuZheng** [comment]
> {"key":"SponsorBlock","categories":["sponsor"]}, {"key":"ModifyChapters","remove_sponsor_segments":["sponsor"]} ] }

why a ]} at end but without {[

**Comment by thoj** [comment]
I forgot to copy the first part. The Json is OK.
```
environment:                                                                                                                                                                                                              
      - YTDL_OPTIONS={"postprocessors":[{"key":"SponsorBlock","categories":["sponsor"]},{"key":"ModifyChapters","remove_sponsor_segments":["sponsor"]}]} 
 ```

I get this error if and only if the video has sponsor segments:
ERROR: Postprocessing: Conversion failed!  

So i'm pretty sure the error is with ModifyChapters.

**Comment by PikuZheng** [comment]
oh. it looks like a bug of ffmpeg. try ffmpeg 5.1 with [this modify](https://github.com/alexta69/metube/commit/90eba5cd121aaac176aa9d23f32e02c4e03a86e4) or [alpine edge](https://github.com/PikuZheng/metube/blob/master/Dockerfile.alpine)

**Comment by thoj** [comment]
The modified Dockerfile worked! 

Thank you!
