### ISSUE TITLE
Embedding thumbnails in mp3 fails

### ISSUE THREAD

**Issue by stizzlestizzle** [alexta69/metube#188]
Hi and thanks for your software.

I made a minimum install of the docker image without any changes.

I am trying to download mp3 from YT videos. With the default option it is attempted to embed the thumbnails but it fails with the following error. The item is then listed as "failed" in the list but the download folder actually contains the mp3 + the webp image as seperate files. Video ID used for testing: xI6dqImaQ50

`ERROR: Postprocessing:   Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps,`

How can I fix the thumbnail creation to work correctly with mp3 so that I end up only with an mp3 file in the download directory and the items are shown as completed in the list?

To work around this I also tried  to start with `YTDL_OPTIONS={"writethumbnail":false}`
But that setting seems to be ignored or does not apply in this case because it's the same result as described above.

**Comment by PikuZheng** [comment]
I believe that 'writethumbnail' means to save thumbnails as a separate file. If you are trying to use an embedded thumbnail, maybe you need to consider after downloading event.
I'm personally recommended you ask it on the YT-DLP project, and you may get an answer faster.

**Comment by stizzlestizzle** [comment]
Ok - opened this one: https://github.com/yt-dlp/yt-dlp/issues/5287

One question though before closing this ticket:

I managed to add the `verbose` argument in `app/ytdl.py` to produce the debug output in the linked ticket. What I am missing is the excapt `yt-dlp` command which is fired. Can you point me how to find out which command is run?

**Comment by PikuZheng** [comment]
just put 'verbose' to ytdl_options like `YTDL_OPTIONS={"verbose":true}`

btw, there is a [postprocessor named embedtumbnail](https://github.com/yt-dlp/yt-dlp/tree/c13a301a94e84d581817a534875e4e2a5c0fdf19/yt_dlp/postprocessor/embedthumbnail.py) so i think it should be like (not tested)
```
YTDL_OPTIONS = { "writethumbnail": true, "postprocessors":[ {"key":"EmbedThumbnail", "maybe something else":"" } ] }
```

**Comment by sixstorm** [comment]
Just curious, did you ever figure this one out?  I've tried every option I know to try with no luck.  Even with using "postprocessors", I still get the error saying:

`Supported filetypes for thumbnail embedding are: mp3....`

I'm trying to download this as an MP3 but even the download won't start.  What gives?

**Comment by stizzlestizzle** [comment]
> just put 'verbose' to ytdl_options like `YTDL_OPTIONS={"verbose":true}`
> 
> btw, there is a [postprocessor named embedtumbnail](https://github.com/yt-dlp/yt-dlp/tree/c13a301a94e84d581817a534875e4e2a5c0fdf19/yt_dlp/postprocessor/embedthumbnail.py) so i think it should be like (not tested)
> 
> ```
> YTDL_OPTIONS = { "writethumbnail": true, "postprocessors":[ {"key":"EmbedThumbnail", "maybe something else":"" } ] }
> ```

The output in the linked issue is what I get when adding the verbose flag. It does not output the actual yt-dlp command which is executed. Any other idea how to get it in order to progress debugging?

**Comment by PikuZheng** [comment]
> I'm trying to download this as an MP3 but even the download won't start. What gives?

looks you want download a video which not provide mp3 format.

**Comment by PikuZheng** [comment]
> The output in the linked issue is what I get when adding the verbose flag. It does not output the actual yt-dlp command which is executed. Any other idea how to get it in order to progress debugging?

metube uses the embedded youtubedl.py but not the binary yt-dlp. Of course the output is different.

**Comment by kblock1** [comment]
I have this same behaviour on a clean build, I can bypass it by removing lines 69-71 in this file:

https://github.com/alexta69/metube/blob/master/app/dl_formats.py#L70

I haven't found a way to workaround with overrides yet, verbose logging of the failure is here:

`metube    | INFO:ytdl:adding https://www.youtube.com/watch?v=8SbUC-UaAxE&ab_channel=GunsNRosesVEVO: quality='best' format='mp3' already=None folder='Music'
metube    | [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
metube    | [debug] yt-dlp version 2022.11.11 [8b64402] (pip) API
metube    | [debug] params: {'quiet': True, 'no_color': True, 'extract_flat': True, 'verbose': True, 'compat_opts': set()}
metube    | [debug] Python 3.8.15 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with (OpenSSL 1.1.1s  1 Nov 2022)
metube    | [debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
metube    | [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
metube    | [debug] Proxy map: {}
metube    | [debug] Loaded 1723 extractors
metube    | [debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=8SbUC-UaAxE&ab_channel=GunsNRosesVEVO
metube    | [youtube] 8SbUC-UaAxE: Downloading webpage
metube    | [youtube] 8SbUC-UaAxE: Downloading android player API JSON
metube    | [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
metube    | [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
metube    | [debug] Default format spec: bestvideo*+bestaudio/best
metube    | INFO:ytdl:downloading Guns N' Roses - November Rain
metube    | ======== Running on http://0.0.0.0:8081 ========
metube    | (Press CTRL+C to quit)
metube    | [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
metube    | [debug] yt-dlp version 2022.11.11 [8b64402] (pip) API
metube    | [debug] params: {'quiet': True, 'no_color': True, 'paths': {'home': '/downloads/Music'}, 'outtmpl': {'default': '%(title)s.%(ext)s', 'chapter': '%(title)s - %(section_number)s %(section_title)s.%(ext)s'}, 'format': 'bestaudio/best', 'cachedir': False, 'socket_timeout': 30, 'progress_hooks': [<function Download._download.<locals>.put_status at 0x7ff71dbf08b0>], 'postprocessor_hooks': [<function Download._download.<locals>.put_status_postprocessor at 0x7ff71dbf0940>], 'verbose': True, 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': 0}, {'key': 'FFmpegMetadata'}, {'key': 'EmbedThumbnail'}], 'writethumbnail': True, 'compat_opts': set()}
metube    | [debug] Python 3.8.15 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with (OpenSSL 1.1.1s  1 Nov 2022)
metube    | INFO:aiohttp.access:172.20.0.2 [22/Dec/2022:13:46:28 +0000] "POST /add HTTP/1.1" 200 284 "https://www.youtube.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
metube    | [debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
metube    | [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
metube    | [debug] Proxy map: {}
metube    | [debug] Loaded 1723 extractors
metube    | [debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=8SbUC-UaAxE
metube    | [youtube] 8SbUC-UaAxE: Downloading webpage
metube    | [youtube] 8SbUC-UaAxE: Downloading android player API JSON
metube    | [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
metube    | [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
metube    | [info] 8SbUC-UaAxE: Downloading 1 format(s): 251
metube    | [info] Downloading video thumbnail 41 ...
metube    | [info] Writing video thumbnail 41 to: /downloads/Music/Guns N' Roses - November Rain.webp
metube    | [debug] Invoking http downloader on "https://rr2---sn-uxanug5-ntqez.googlevideo.com/videoplayback?expire=1671738391&ei=tl-kY5bvPI6OrAH-96KoCw&ip=203.51.38.64&id=o-AEqZ195jAKOySYL6aKI6JG5fEo9CbQYbRZzSsVkiS6ZO&itag=251&source=youtube&requiressl=yes&mh=mn&mm=31%2C26&mn=sn-uxanug5-ntqez%2Csn-hxa7zn7z&ms=au%2Conr&mv=m&mvi=2&pl=21&gcr=au&initcwndbps=1991250&spc=zIddbOR-9cJqidJmzwsZnTU76p97PfE&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=9029029&dur=556.841&lmt=1650322210430794&mt=1671716496&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgG3oCGqNcuW-U--N1bi8q-LkPvNbbQLHNsGbQ5FW1MscCIQDVKVFpAsTCyoyfFlPKfHpUGfrJRV_WJ1QC0e4Wii0Zfw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgLI58eonQSFSNtUbnkzwJLHckVgHMFHIDwf-kbVvuHJMCIQD-TZUygMZvoF0jBRJC2uCgRhKiuLVzlJEPiWCsvnXjYA%3D%3D"
metube    | [download] Destination: /downloads/Music/Guns N' Roses - November Rain.webm
[debug] ffmpeg command line: ffprobe -show_streams 'file:/downloads/Music/Guns N'"'"' Roses - November Rain.webm'
metube    | [ExtractAudio] Destination: /downloads/Music/Guns N' Roses - November Rain.mp3
metube    | [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/downloads/Music/Guns N'"'"' Roses - November Rain.webm' -vn -acodec libmp3lame -q:a 0.0 -movflags +faststart 'file:/downloads/Music/Guns N'"'"' Roses - November Rain.mp3'
metube    | Deleting original file /downloads/Music/Guns N' Roses - November Rain.webm (pass -k to keep)
metube    | [Metadata] Adding metadata to "/downloads/Music/Guns N' Roses - November Rain.mp3"
metube    | [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/downloads/Music/Guns N'"'"' Roses - November Rain.mp3' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=Guns N'"'"' Roses - November Rain' -metadata date=20091225 -metadata 'description=Official Music Video for "November Rain" performed by Guns N'"'"' Roses from their third studio album, '"'"'Use Your Illusion I.'"'"' Featured in Thor: Love and Thunder. 
metube    | 
metube    | Subscribe to Guns N'"'"' Roses YouTube channel and never miss an update: https://GNR.lnk.to/YouTube
metube    | 
metube    | Watch more Guns N'"'"' Roses official music videos: https://www.youtube.com/playlist?list=PLOTK54q5K4INNXaHKtmXYr6J7CajWjqeJ
metube    | 
metube    | Follow Guns N'"'"' Roses: 
metube    | Site: https://www.gunsnroses.com/ 
metube    | Facebook: https://www.facebook.com/gunsnroses 
metube    | Twitter: https://twitter.com/gunsnroses 
metube    | Instagram: https://www.instagram.com/gunsnroses 
metube    | 
metube    | YouTube view counts pre-VEVO: 6,894,036. VEVOCertified on June 24, 2012: http://www.vevo.com/certified 
metube    | (C) 1992 Guns N'"'"' Roses
metube    | 
metube    | #GunsNRoses #GnR #NovemberRain' -metadata 'synopsis=Official Music Video for "November Rain" performed by Guns N'"'"' Roses from their third studio album, '"'"'Use Your Illusion I.'"'"' Featured in Thor: Love and Thunder. 
metube    | 
metube    | Subscribe to Guns N'"'"' Roses YouTube channel and never miss an update: https://GNR.lnk.to/YouTube
metube    | 
metube    | Watch more Guns N'"'"' Roses official music videos: https://www.youtube.com/playlist?list=PLOTK54q5K4INNXaHKtmXYr6J7CajWjqeJ
metube    | 
metube    | Follow Guns N'"'"' Roses: 
metube    | Site: https://www.gunsnroses.com/ 
metube    | Facebook: https://www.facebook.com/gunsnroses 
metube    | Twitter: https://twitter.com/gunsnroses 
metube    | Instagram: https://www.instagram.com/gunsnroses 
metube    | 
metube    | YouTube view counts pre-VEVO: 6,894,036. VEVOCertified on June 24, 2012: http://www.vevo.com/certified 
metube    | (C) 1992 Guns N'"'"' Roses
metube    | 
metube    | #GunsNRoses #GnR #NovemberRain' -metadata 'purl=https://www.youtube.com/watch?v=8SbUC-UaAxE' -metadata 'comment=https://www.youtube.com/watch?v=8SbUC-UaAxE' -metadata artist=GunsNRosesVEVO -movflags +faststart 'file:/downloads/Music/Guns N'"'"' Roses - November Rain.temp.mp3'
metube    | [ThumbnailsConvertor] Converting thumbnail "/downloads/Music/Guns N' Roses - November Rain.webp" to png
metube    | [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/downloads/Music/Guns N'"'"' Roses - November Rain.webp' -update 1 -movflags +faststart 'file:/downloads/Music/Guns N'"'"' Roses - November Rain.png'
metube    | [debug] ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
metube    |   built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
metube    |   configuration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug
metube    |   libavutil      57. 17.100 / 57. 17.100
metube    |   libavcodec     59. 18.100 / 59. 18.100
metube    |   libavformat    59. 16.100 / 59. 16.100
metube    |   libavdevice    59.  4.100 / 59.  4.100
metube    |   libavfilter     8. 24.100 /  8. 24.100
metube    |   libswscale      6.  4.100 /  6.  4.100
metube    |   libswresample   4.  3.100 /  4.  3.100
metube    |   libpostproc    56.  3.100 / 56.  3.100
metube    | Input #0, image2, from 'file:/downloads/Music/Guns N' Roses - November Rain.webp':
metube    |   Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
metube    |   Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 1280x720, 25 fps, 25 tbr, 25 tbn
metube    | Stream mapping:
metube    |   Stream #0:0 -> #0:0 (webp (native) -> png (native))
metube    | Press [q] to stop, [?] for help
metube    | Output #0, image2, to 'file:/downloads/Music/Guns N' Roses - November Rain.png':
metube    |   Metadata:
metube    |     encoder         : Lavf59.16.100
metube    |   Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps, 
metube    | ERROR: Postprocessing:   Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps,
metube    | Traceback (most recent call last):
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3276, in process_info
metube    |     replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3453, in post_process
metube    |     info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3435, in run_all_pps
metube    |     info = self.run_pp(pp, info)
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3414, in run_pp
metube    |     files_to_delete, infodict = pp.run(infodict)
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
metube    |     ret = func(self, info, *args, **kwargs)
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
metube    |     return func(self, info)
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 86, in run
metube    |     thumbnail_filename = convertor.convert_thumbnail(thumbnail_filename, 'png')
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1093, in convert_thumbnail
metube    |     self.real_run_ffmpeg(
metube    |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 361, in real_run_ffmpeg
metube    |     raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
metube    | yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps,
metube    | 
metube    | INFO:ytdl:waiting for item to download
`

**Comment by PikuZheng** [comment]
> I have this same behaviour on a clean build, I can bypass it by removing lines 69-71 in this file:
> 
> https://github.com/alexta69/metube/blob/master/app/dl_formats.py#L70
> 
> I haven't found a way to workaround with overrides yet, verbose logging of the failure is here:

very good try. I think we need to convert the thumbnail to jpg (not png) before embedding in mp3 (png works fine in mp4 video but not mp3

**Comment by kblock1** [comment]
Hey that's an idea, I will try adding this before line 69

        opts["postprocessors"].append({"key": "FFmpegThumbnailsConvertor", "format": "jpg", "when": "before_dl"})

**Comment by PikuZheng** [comment]
> Hey that's an idea, I will try adding this before line 69

yeah.... convent thumbnail to jpg before embedding works 'cause neither png nor jpg but webp.

so

![image](https://user-images.githubusercontent.com/12579522/209243846-599a0b99-88f3-4d4c-9bca-b5960580dc74.png)

**Comment by kblock1** [comment]
Yep, that solved it here, I reckon there are a few other issues that also reference this

**Comment by CenterfireXid** [comment]
Hello! Sorry to re-open this issue, but I am having trouble making this work. I can successfully download thumbnails as webp files and embed them into my MP4 video files. The embedded thumbnail shows up on my file explorer, however I am using Jellyfin for my media and it does not support webp files for thumbnails and therefore does not display thumbnails correctly.

This is the what I was using for the YTDL Options - {"writeautomaticsub":true,"subtitleslangs":["en","-live_chat"],"writethumbnail":true,"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true},{"key":"EmbedThumbnail"}]}

This again downloads thumbnails as webp files and embeds them successfully. However, I need to convert the webp files into jgp before embedding. Here are various YTDL Options I have tried to no avail:

{"writeautomaticsub":true,"subtitleslangs":["en","-live_chat"],"writethumbnail":true,"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{**"key":"FFmpegThumbnailsConvertor","format":"jpg"**},"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true},{"key":"EmbedThumbnail"}]}

{"writeautomaticsub":true,"subtitleslangs":["en","-live_chat"],"writethumbnail":true,"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{**"key":"FFmpegThumbnailsConvertor","format":"jpg", "when": "before_dl"**},"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true},{"key":"EmbedThumbnail"}]}

Due to the nature of my homelab setup (I am using TrueNAS Scale with a truecharts install of metube) only have access to change the Output Template, YTDL Options, and an option to add Extra Environment Variables and Extra Args, see below.

![image](https://github.com/user-attachments/assets/e353b2d9-1825-422e-b395-4217e014e2a3)

I prefer to only edit the YTDL Options rather than add Extra Environment Variables or Extra Args, but I am happy to try it if someone has an idea of what I can do to make the webp to jpg conversion successful.

Thanks in advance for your help!

**Comment by PikuZheng** [comment]
> Hello! Sorry to re-open this issue, but I am having trouble making this work. I can successfully download thumbnails as webp files and embed them into my MP4 video files. The embedded thumbnail shows up on my file explorer, however I am using Jellyfin for my media and it does not support webp files for thumbnails and therefore does not display thumbnails correctly.

I'll get a png thumbnail when download a video from youtube. can you provide an example?

**Comment by CenterfireXid** [comment]
> > Hello! Sorry to re-open this issue, but I am having trouble making this work. I can successfully download thumbnails as webp files and embed them into my MP4 video files. The embedded thumbnail shows up on my file explorer, however I am using Jellyfin for my media and it does not support webp files for thumbnails and therefore does not display thumbnails correctly.
> 
> I'll get a png thumbnail when download a video from youtube. can you provide an example?
> 
> ![image](https://private-user-images.githubusercontent.com/12579522/375918827-7dff1ab8-5dd3-40fb-8aae-43a784694b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDk1ODYsIm5iZiI6MTcyODcwOTI4NiwicGF0aCI6Ii8xMjU3OTUyMi8zNzU5MTg4MjctN2RmZjFhYjgtNWRkMy00MGZiLThhYWUtNDNhNzg0Njk0YjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA1MDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OGZjYzdkNDkyOWRmOGEyNjgwOTliMDg1MTk3MzNkMmUyMjM5YjA4ZmIwNDJmNGY0NGUzYzhmZTMzYjcxNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1XUT2WATGevrOqnRtmPGAG_rgmPA5fWpCI-d90foaf0)

Thank you for your reply, when downloading this youtube video https://youtu.be/TTsi4Kg6hkQ?si=YhDa8IOTzoFnRbES for example as an MP4, with my set YTDL options, it will download the thumbnail as a webp while downloading the video, then once the video is downloaded, will embed the webp thumbnail into the mp4 and delete the webp.

**Comment by PikuZheng** [comment]
still works for me

![image](https://github.com/user-attachments/assets/b026cdc2-732a-4fac-8ec9-b8cd56b64fa1)

my options:
```
{
 "cookiefile":"/downloads/.metube/cookies.txt",
 "verbose":false,
 "format_sort":["codec:avc:m4a"],
 "overwrites":true,
 "outtmpl":{"default":"[%(upload_date)s]%(title).50s %(uploader_id)s(%(vcodec).4s+%(acodec).4s)[%(id)s].%(ext)s"},
 "ignoreerrors":true,
 "writethumbnail":true,
 "postprocessors":[
  {"key":"FFmpegMetadata","add_metadata":true,"add_chapters":true,"add_infojson":"if_exists"},
  {"key":"EmbedThumbnail"},
  {"key":"Exec","exec_cmd":"sh /downloads/execafterdownload.sh","when":"after_move"}
 ]
}
```
