### ISSUE TITLE
Download folder selection doesn't work in safari

### ISSUE THREAD

**Issue by LeLunZ** [alexta69/metube#192]
Doesn't work in safari. But seems to work everywhere else.

In this clip I am pressing multiple times on the dropdown but nothing happens.

https://user-images.githubusercontent.com/31982496/198843870-49f7bb79-8651-4c2e-9233-93daee5183ec.mov

**Comment by PikuZheng** [comment]
Enable Error Console through Safari -> Preferences -> Advanced, then check "Show Develop menu in menu bar". A new menu titled "Develop" appears in the menubar at the top of the screen. From there, choose "Show Error Console" and then load your page. Will you see any errors?

**Comment by niv** [comment]
Also seeing this bug on Safari, with content blockers disabled. Log shows detected subdirs fine (though you might want to skip .metube):

`[Debug] got custom_dirs: – {download_dir: [".metube", "Test"], audio_download_dir: [".metube", "Test"]} (main.dca9593d9e22ca2a.js, line 1)`

Clicking the chevron also does not emit any log messages whatsoever.

**Comment by PikuZheng** [comment]
so any subdirs in download dir?

**Comment by PikuZheng** [comment]
I configured an OSX virtual machine and confirmed that the problem exists. I will update if there is any progress.

**Comment by alexta69** [comment]
Closed by #219
