### ISSUE TITLE
CIFS share

### ISSUE THREAD

**Issue by VoidAndAny** [alexta69/metube#195]
Hi, 
I try to run metube in Docker using a CIFS share defined directly in my docker_compose, like this: 
```
...
services:
...
    volumes:
      - type: volume
        source: syno
        target: /downloads
        volume:
          nocopy: true

...
 
volumes:
  syno:
    driver_opts:
      type: cifs
      o: "username=${CIFS_USER},password=${CIFS_PASSWORD}"
      device: "${CIFS_SHARE}"
```

But when metube start entry_point.sh try to chmod my share wich is not authorized:

```
Setting umask to 022
Creating download directory /downloads and state directory /downloads/.metube
Changing ownership of download and state directories to 1000:1000
Running MeTube as user 1000:1000
Traceback (most recent call last):
  File "app/main.py", line 75, in <module>
    dqueue = DownloadQueue(config, Notifier())
  File "/app/app/ytdl.py", line 195, in __init__
    self.queue = PersistentQueue(self.config.STATE_DIR + '/queue')
  File "/app/app/ytdl.py", line 150, in __init__
    with shelve.open(path, 'c'):
  File "/usr/local/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied: '/downloads/.metube/queue'
```

My CIFS share is on a Synology NAS, I try to change UID/GID without success

Thanks

**Comment by PikuZheng** [comment]
I firmly believe this is a problem with synology. For myself, I use system level nfs mounts and map directories to containers.

```
~# cat /etc/fstab
.....
172.17.2.123:/volume2/video /mnt/nas nfs defaults 0 0

~#docker inspect 45eb
.....
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/mnt/nas:/downloads"
        ],
```
In this case, the permissions are the responsibility of synology. No need to worry about container permissions.

**Comment by VoidAndAny** [comment]
You're probably right, with Docker NFS mount on Syno it's works fine.
Is it possible to bypass the chmod in entrypoint ?

**Comment by PikuZheng** [comment]
cifs permissions are managed by the mount point. Maybe you can change `o: "username=${CIFS_USER},password=${CIFS_PASSWORD}"` to `rw,iocharset=utf8,dir_mode=0777,file_mode=0777,username=${CIFS_USER},password=${CIFS_PASSWORD}"`

(I don't use cifs on synology, just guessing)

**Comment by VoidAndAny** [comment]
Thanks a lot, works perfectly fine
