### ISSUE TITLE
No way to stop adding video's

### ISSUE THREAD

**Issue by deKoning** [alexta69/metube#198]
I love this application! I made a mistake and realized that there is no way to stop the automatic function that adds video to the waiting line. For example; by mistake I entered the URL https://www.youtube.com (copy & past mistake). After that it kept adding video's. Even after stopping and restarting the container it continued adding video's. A simple 'stop importing from URL' would help a lot.

**Comment by PikuZheng** [comment]
Yes, it caused my computer to freeze. I stop the whole container and delete the queue file, it works. Also need to clean up temporary files.

Unfortunately, the stop button (if any) cannot be operated during this time

**Comment by deKoning** [comment]
Thanks, I will try the workaround as you describe.

**Comment by deKoning** [comment]
Cleaning up the temporary files worked for me. Maybe a fix will be to add a button to delete that file from the GUI.

**Comment by Metroid-Prime** [comment]
Just ran into this via docker container. It's pretty crazy that this hasn't been addressed in the GUI. metube puts a .metube hidden folder in the Mac downloads directory that stores the queue and downloaded files. Pretty infuriating that it stores settings outside of the docker container. :-\
