### ISSUE TITLE
Audio Only Option(s)

### ISSUE THREAD

**Issue by tom472** [alexta69/metube#20]
This is amazing - really nice app!

Any chance there could be a best audio option added to the dropdown selection?
Looks like it's pretty straightforward with youtube-dl via this switch: `-f bestaudio`.

Or any option(s) to select audio only downloads?

That would be awesome.

Again great app 

--Thanks

**Comment by alexta69** [comment]
Hey,
I pushed such an option now. I hope you find it useful!
Regards
--Alex

**Comment by tom472** [comment]
Excellent - I'll update and give it a try tonight.

**Comment by tom472** [comment]
Seems to be working great - Thanks!

**Comment by alexta69** [comment]
@tom472 Glad to hear you're enjoying the software! :)
