### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by DOFfactory** [alexta69/metube#201]
I tried to set the CREATE_CUSTOM_DIRS environment to `true`, but it does not create respective folders. Can you please help me how to enforce this? What is the correct setting?

**Comment by alexta69** [comment]
With this variable as `true`, you can input a custom directory in the "Add" dropdown, and it will be created when the video starts downloading.
Can you describe the flow you're doing, and which part isn't working?

**Comment by DOFfactory** [comment]
thanks @alexta69 for this explanation, I sensed that I have to set it to `true`, which I did, but I was not aware of the dropdown menu option. I am closing this issue now but I would suggest to add this description to the documentation.
