### ISSUE TITLE
'/downloads/.metube/queue  _gdbm.error: [Errno 19] No such device

### ISSUE THREAD

**Issue by WrestlingMob** [alexta69/metube#209]
`Setting umask to 022
Creating download directory /downloads/.metube and state directory /downloads/.metube
Changing ownership of download and state directories to 1000:100
Running MeTube as user 1000:100
Traceback (most recent call last):
  File "app/main.py", line 75, in <module>
    dqueue = DownloadQueue(config, Notifier())
  File "/app/app/ytdl.py", line 195, in __init__
    self.queue = PersistentQueue(self.config.STATE_DIR + '/queue')
  File "/app/app/ytdl.py", line 150, in __init__
    with shelve.open(path, 'c'):
  File "/usr/local/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 19] No such device: '/downloads/.metube/queue'`

I'm trying to set this up in portainer. I keep getting this error. I'm using OpenMediaVault referencing an SMB share on /tank/metube

**Comment by PikuZheng** [comment]
I am also using portainer. 
This looks like a smb permissions issue. Try to mount OMV to host and confirm permissions, then map it from host to container.
A better way is to use nfs, which the permissions are the responsibility of OMV and no need to worry about container permissions.

**Comment by alexta69** [comment]
Closing (doesn't look like a MeTube issue, if you find out otherwise please reopen)
