### ISSUE TITLE
Download completed files

### ISSUE THREAD

**Issue by kyoumei** [alexta69/metube#21]
Is there an option to download completed files/playlists, from the web server to the web viewer's device? 

I understand that these files were downloaded to the web server, but was just wondering if the above was possible at this stage?

**Comment by alexta69** [comment]
Hey @kyoumei ,
There was a request to implement it, but I didn't have time.. If you feel like implementing it, you're welcome to create a PR and I'll gladly merge it.
I'l close the issue in the meantime...
Thanks
Alex
