### ISSUE TITLE
Support loading youtubeDL options from a file

### ISSUE THREAD

**Issue by ColinHebert** [alexta69/metube#210]
Currently metube loads the configuration of ytdl via the `YTDL_OPTIONS` env variable.
This could be nicely complemented by the possibility of loading YTDL_OPTIONS from a config file.

For example if `YTDL_OPTIONS` doesn't load as a JSon file, it could be worth checking if it's a path to a file in which case that file should be loaded instead.
An alternative is to support a `YTDL_OPTIONS_FILE` env variable which point to a configuration file. If not set then `YTDL_OPTIONS` should be used.

**Comment by alexta69** [comment]
What's the use case that it's designed to support? I mean, in any case a restart is needed when the options change, and if we're restarting, we might as well make the changes in the environment definition, no?

**Comment by alexta69** [comment]
I understand, sounds reasonable. I don't know if or when I get to implement it, so if you or someone else want to submit a PR, I'll gladly merge it.

**Comment by PikuZheng** [comment]
For testing purposes, I modify ytdl_options frequently. You just need to write it into docker-entrypoint.sh. As follows:
```
#!/bin/sh

export YTDL_OPTIONS={ignoreerrors:true}

echo "Setting umask to ${UMASK}"
```
then restart the container.

You can also use .env file of compose, but you still need to rebuild the container (compose up).

**Comment by evert-mouw** [comment]
If you use SystemD, you can specify a **EnvironmentFile**
E.g., I have `/etc/systemd/system/metube.service` with
```
[Unit]
Description=MeTube downloader
After=network.target

[Service]
Type=simple
User=root
Group=root
EnvironmentFile=/etc/metube.conf
WorkingDirectory=/opt/metube
ExecStart=pipenv run python3 app/main.py

[Install]
WantedBy=multi-user.target
```
(Yes, running as root, this is a virtual machine just for downloading stuff, I don't care... Also note the UID/GID switch below...)

Then, `/etc/metube.conf` just sets environment variables with standard shell syntax. Note that Bash/sh don't allow spaces before and after the equal sign (`=`); but using comments (`#`) is possible.
```
UID=2000
GID=2000
DOWNLOAD_DIR="/mnt/storage/MeTube"
STATE_DIR="/mnt/storage/MeTube/_state"
YTDL_OPTIONS='{"writedesktoplink": true}'
```
