### ISSUE TITLE
YTDL_OPTIONS to change modified time to instead just use time of download?

### ISSUE THREAD

**Issue by BliNDF123** [alexta69/metube#211]
I've tried every way I could think of but I don't see an environment variable, https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L176, like --no-mtime that I can add to the YTDL_OPTIONS in the yml.  I've already tried postprocessor, FFmpegVideoConvertor is converting it, modifying it, but apparently that doesn't change the modified time of when the video was uploaded to YT.

**Comment by alexta69** [comment]
I understand the problem, and it's a bummer. It's not something that MeTube can help with, though, as we're only a GUI for yt-dlp. I'm leaving the issue open here in case someone can come up with the correct mix of options for yt-dlp, but MeTube itself will not be able to solve it.

**Comment by PikuZheng** [comment]
A file has both a "create time" and a "modify time". "create time" is the time when the video was published; "modify time" is the time when the video was uploaded to youtube (If timed publishing is used, the "modify time" may be much earlier than the "create time").
I want to know exactly which one you need to modify.

![image](https://user-images.githubusercontent.com/12579522/213031241-9326ddd0-657a-4c6d-966a-d6cd3c05128e.png)

#166 please refer to

**Comment by BliNDF123** [comment]
> A file has both a "create time" and a "modify time". "create time" is the time when the video was published; "modify time" is the time when the video was uploaded to youtube (If timed publishing is used, the "modify time" may be much earlier than the "create time"). I want to know exactly which one you need to modify.
> 
> ![image](https://user-images.githubusercontent.com/12579522/213031241-9326ddd0-657a-4c6d-966a-d6cd3c05128e.png)
> 
> #166 please refer to

The Modify time, this for example https://www.youtube.com/watch?v=7haiKDaneI8 if I download it right now it will show Modify time of 6/25/2022, so Jellyfin will put it at the bottom of the list for sorting even if I downloaded it today.  I would like for them to just keep the time of download instead.

**Comment by PikuZheng** [comment]
A little trick is to modify this file again after the download is complete, for example adding a newline after the end of the file. This will update the modify date of the file. try
```
YTDL-OPTIONS= {"postprocessors":[{"key":"Exec","exec_cmd":"echo . >> ","when":"after_video"}]}
```

**Comment by BliNDF123** [comment]
Doesn't look like it worked, I'm seeing a X on the download in MeTube's WebUI saying 'Command returned error code 2' the only odd thing I see in the logs is this:  
`[download]  42.9% of   22.86MiB at    3.91MiB/s ETA 00:03
[download]  4      ./bin/sh: syntax error: unexpected end of file
INFO:ytdl:waiting for item to download
`
But otherwise the download is there but the modified time is still not current, as in the time of download, it's still the old modify time.  This is my environment variables right now:
`    environment:
      - OUTPUT_TEMPLATE=%(title)s [%(id)s].%(ext)s
      - 'YTDL_OPTIONS={"writethumbnail": true, "postprocessors":[{"key": "Exec", "exec_cmd":"echo . >> ", "when": "after_video"}, {"key": "FFmpegThumbnailsConvertor", "format": "png", "when": "before_dl"}]}'`

**Comment by PikuZheng** [comment]
.... my bad. these works for me:

```
YTDL-OPTIONS= {"ignoreerrors":true,"writethumbnail":true,"postprocessors":[{"key":"Exec","exec_cmd":"sh /downloads/execafterdownload.sh","when":"after_video"}]}
```
add more options if you like.

file `execafterdownload.sh` :
```
#!/bin/sh

echo . >> $1
```
----
default means no external_downloader. try`YTDL_OPTIONS={"external_downloader":"aria2c"}` if you want. https://github.com/alexta69/metube/issues/67#issuecomment-1213627110 fyi

**Comment by BliNDF123** [comment]
> .... my bad. these works for me:
> 
> ```
> YTDL-OPTIONS= {"ignoreerrors":true,"writethumbnail":true,"postprocessors":[{"key":"Exec","exec_cmd":"sh /downloads/execafterdownload.sh","when":"after_video"}]}
> ```
> 
> add more options if you like.
> 
> file `execafterdownload.sh` :
> 
> ```
> #!/bin/sh
> 
> echo . >> $1
> ```
> 
> default means no external_downloader. try`YTDL_OPTIONS={"external_downloader":"aria2c"}` if you want. [#67 (comment)](https://github.com/alexta69/metube/issues/67#issuecomment-1213627110) fyi

Yeah, the external_downloader I think would have worked too but @pukkandan in the yt-dlp Discord was also helping me and said 'updatetime' would also work and doesn't need external_downloader.  I edited my comment above to what I'm using right now.

**Comment by alexta69** [comment]
Closing (looks like it's resolved, correct?)

**Comment by shalak** [comment]
I don't believe this one was solved previously (didn't work for me correctly). I went with simple `touch` on `after_move`:

```
    environment:
      - YTDL_OPTIONS={"postprocessors":[{"key":"Exec","exec_cmd":"touch","when":"after_move"}]}
```

**Comment by PikuZheng** [comment]
> 我不相信这个问题已经解决了（对我来说没有正确的工作）。我选择了简单`touch`的`after_move`：
> 
> ```
>     environment:
>       - YTDL_OPTIONS={"postprocessors":[{"key":"Exec","exec_cmd":"touch","when":"after_move"}]}
> ```

I tried and touch works for me. Maybe you need to inspect the container and run touch to see what happens

**Comment by shalak** [comment]
Yes, that's what I said. `touch` works for me. The tricks & dedicated script with `echo . >>` doesn't work. 

Also - `touch` doesn't work with `after_video`.

**Comment by PikuZheng** [comment]
> Yes, that's what I said. `touch` works for me. The tricks & dedicated script with `echo . >>` doesn't work.
> 
> Also - `touch` doesn't work with `after_video`.

sorry I misunderstood and thanks for sharing
