### ISSUE TITLE
Ogg and Wav Audio Formats?

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [alexta69/metube#212]
Hey, this is a really nice tool and I think it's pretty useful as a convenient frontend. I've noticed that there's a list of formats that are modifiable in `/ui/src/app/formats.ts` that would allow me to add Ogg support if I were to build the project from source and host my own docker image.

However, I was wondering if you could add support for these formats for two key reasons:
1) Ogg vorbis format can be a format with better licensing conditions, and thus be a format of choice for many open source projects and applications.
2) Wav format would give some users some leeway to download a file in best-possible quality and reduce the number of re-encodes, preserving audio quality to as-close-to-source as possible. This would be useful when you need to manually split a long-form video into multiple audio files, such as when downloading a whole album.

Thanks for this great tool btw!

**Comment by PikuZheng** [comment]
I think you need to modify format.ts and dl_formats.py to use ffmpeg to convert it to ogg format after downloading. You can submit a pr.

**Comment by Presjar** [comment]
Just wondering if the same method can be used to allow mkv as the resulting file format?

In the [yt-dlp documentation](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L183)
'format' can be used, but I'm guessing If I try to use this method via the _YTDL_OPTIONS: Additional options to pass to youtube-dl, in JSON format._ for the docker it will conflict with the Format selection in the webui making that selection useless?

**Comment by alexta69** [comment]
No, there won't be a conflict, whatever you specify in `YTDL_OPTIONS` just overrides what you have in the UI. mkv is a bit different from others because it's a container format, not the encoding format, so it can contain any encoding. So it doesn't belong in the same place. For now, just use `YTDL_OPTIONS`...

**Comment by alexta69** [comment]
Fixed in #230

**Comment by Eoin-ONeill-Yokai** [comment]
Awesome, thank you so much!

I was going to look into it but never found the time.

**Comment by ChrisKolan** [comment]
@Eoin-ONeill-Yokai asked about ogg format but opus was merged instead. Are there plans to add ogg vorbis format?

**Comment by alexta69** [comment]
@ChrisKolan no plans, but feel free to submit a PR
