### ISSUE TITLE
CUSTOM_DIRS=False Performance Issues

### ISSUE THREAD

**Issue by timreuscher** [alexta69/metube#213]
Since I have a ton of subfolders, I've set CUSTOM_DIRS to False. It correctly does not display the drop down. The issue is that it still churns through all of those subdirectories to the detriment of the UI being disabled for several seconds, to the point of many videos not downloading properly when using the browser extension. If CUSTOM_DIRS is False, there's no reason to enumerate the subfolders in the background.

**Comment by PikuZheng** [comment]
> to the point of many videos not downloading properly when using the browser extension.

any details such as logs please? 

The "metube downloader" extension I'm using doesn't send custom dirs.

**Comment by timreuscher** [comment]
The issue isn't with the extension, it's just the videos error out with the extension because the server is too busy enumerating the directories. A simple reload of the failed video downloads it without issue.

Opening the metube site leads to the same slow enumeration, even with CUSTOM_DIRS set to False. That's where the problem is.

**Comment by PikuZheng** [comment]
I created 7871 random folders in DOWNLOAD_DIR and everything looks fine with CUSTOM_DIRS=False.
but yes the problem exists

**Comment by PikuZheng** [comment]
The reason is that python will interpret ENV False as the string 'False'. At this point, CUSTOM_DIRS="False" the result is bool True. 

A simple way is to set CUSTOM_DIRS="", the result is bool False, it works for me.

**Comment by PikuZheng** [comment]
![image](https://user-images.githubusercontent.com/12579522/216478068-dc3e2bb2-8f76-4079-9b9f-ba740d19d3e8.png)

**Comment by timreuscher** [comment]
That looks to be working much better. Obviously it's ideal to have False handle all of those things (the drop down AND not enumerating directories with the resulting performance hit), but the immediate issue is solved by that. False does eliminate the drop down though, so it gives the impression it's working, just not in the most logical way.

**Comment by PikuZheng** [comment]
Turning 'False' to bool Fasle is a lot of work for python.
Just do this for now 😆

**Comment by alexta69** [comment]
I pushed a fix, it was indeed a mess there.

**Comment by timreuscher** [comment]
Thanks! I did notice the issue wasn't fixed by that setting, so I appreciate the effort.
