### ISSUE TITLE
Add some kind of security

### ISSUE THREAD

**Issue by dzahariev** [alexta69/metube#217]
Can you consider to add some kind of authentication to secure the access. Without any security this cannot be started on public domain, but only on localhost.

For instance - fixed credentials from environment variable is sufficient for personal use.

**Comment by alexta69** [comment]
I recommend using [Authelia](https://www.authelia.com/) for this purpose. [linuxserver/swag](https://docs.linuxserver.io/general/swag) already comes with it pre-configured, for MeTube and everything else it supports, so you can either use directly or as a reference for your config.
Duplicate of #150
