### ISSUE TITLE
Cannot download files from Android Firefox

### ISSUE THREAD

**Issue by philipphutterer** [alexta69/metube#218]
When I try to download an MP3 file using Firefox for Android, I get the error listed below and Firefox shows me a message saying "Download failed".
This happens for both:

1. Long press the filename link > Download link
2. Press the link (which plays the file in the browsers built-in media player) > long press on the media playback > Save file to device

The download works fine in other browsers (tested Chrome) and on other devices.
There is an [open issue](https://github.com/aio-libs/aiohttp/issues/6566) in the aiohttp repository with this error message.

Solution:
I tested using the `download` HTML attribute on the anchor tag and it actually worked. So I opt for an option like [in this open PR](https://github.com/alexta69/metube/pull/178), a small download button. It seems like this PR does [currently not work](https://github.com/alexta69/metube/pull/178#discussion_r1056742353), however, this is easy to fix.

```
INFO:aiohttp.access:192.168.178.50 [10/Feb/2023:12:39:44 +0000] "GET /audio_download/<filename>.mp3 HTTP/1.1" 200 0 "http://rpi4:8081/" "Mozilla/5.0 (Android 12; Mobile; rv:109.0) Gecko/109.0 Firefox/109.0"
INFO:aiohttp.access:192.168.178.50 [10/Feb/2023:12:39:44 +0000] "GET /audio_download/<filename>.mp3 HTTP/1.1" 206 300 "http://rpi4:8081/" "Mozilla/5.0 (Android 12; Mobile; rv:109.0) Gecko/109.0 Firefox/109.0"
INFO:aiohttp.access:192.168.178.50 [10/Feb/2023:12:39:51 +0000] "GET /audio_download/<filename>.mp3 HTTP/1.1" 200 0 "http://rpi4:8081/" "Mozilla/5.0 (Android 12; Mobile; rv:109.0) Gecko/109.0 Firefox/109.0"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
INFO:aiohttp.access:192.168.178.50 [10/Feb/2023:12:39:56 +0000] "UNKNOWN / HTTP/1.0" 400 204 "-" "-"
```

**Comment by alexta69** [comment]
The comment on the PR (which says that the PR doesn't work) suggests a fix, is that fix working? If it is, I'll apply it and push the PR

**Comment by philipphutterer** [comment]
Alright, so I tested the PR rebased on `alexta69/metube:master`, applied the suggested fix and it works fine. A revised merge would be great.

**Comment by alexta69** [comment]
I looked again at the suggestion in the PR, and I see that the code calls buildDownloadLink(). but the project doesn't have this function. How could it work?

**Comment by philipphutterer** [comment]
https://github.com/alexta69/metube/blob/8a169dad1c331aa212c7c518f9757edfd2b94861/ui/src/app/app.component.ts#L195-L206

**Comment by alexta69** [comment]
Doh, it's in master. Merging the PR.
