### ISSUE TITLE
ERROR: [youtube] S5mQgNlG-48: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U I

### ISSUE THREAD

**Issue by gpnunes75** [alexta69/metube#220]
Need apply this fix

https://github.com/yt-dlp/yt-dlp/issues/6247

**Comment by PikuZheng** [comment]
metube will update yt-dlp automately when restart cotainer. It seems that current version is 20230106. Please keep an eye on https://github.com/ytdl-patched/yt-dlp/releases for new releases from the master branch.

**Comment by gpnunes75** [comment]
> metube will update yt-dlp automately when restart cotainer. It seems that current version is 20230106. Please keep an eye on https://github.com/ytdl-patched/yt-dlp/releases for new releases from the master branch.

I tried to update yt-dlp ( I know if a restart container it will be lost) inside container on /usr/local/bin. It works on terminal, but metube UI still doesn't work.

Is there any other place to change to do UI works?

**Comment by PikuZheng** [comment]
yt-dlp in metube comes from python library (pip install -upgrade yt-dlp). If you want to use your own bin, you may need to package the cotainer image by yourself

**Comment by wy580477** [comment]
> metube will update yt-dlp automately when restart cotainer. It seems that current version is 20230106. Please keep an eye on https://github.com/ytdl-patched/yt-dlp/releases for new releases from the master branch.

I can't find yt-dlp update related code in docker-entrypoint.sh. Is it updated by python code?

**Comment by j3lte** [comment]
[yt-dlp@2023.02.17](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17) has been released, should have the fix for this.

**Comment by gpnunes75** [comment]
> > metube will update yt-dlp automately when restart cotainer. It seems that current version is 20230106. Please keep an eye on https://github.com/ytdl-patched/yt-dlp/releases for new releases from the master branch.
> 
> I can't find yt-dlp update related code in docker-entrypoint.sh. Is it updated by python code?

I did't find it too, I recreate my container and yt-dlp didn't update. I need to update it manually with "pip install --upgrade yt-dlp"

I know if I restart container I will loose this.

**Comment by j3lte** [comment]
> > > metube will update yt-dlp automately when restart cotainer. It seems that current version is 20230106. Please keep an eye on [ytdl-patched/yt-dlp/releases](https://github.com/ytdl-patched/yt-dlp/releases) for new releases from the master branch.
> > 
> > 
> > I can't find yt-dlp update related code in docker-entrypoint.sh. Is it updated by python code?
> 
> I did't find it too, I recreate my container and yt-dlp didn't update. I need to update it manually with "pip install --upgrade yt-dlp"
> 
> I know if I restart container I will loose this.

Correct, but if you look at the Github actions, you will see that it runs [update-yt-dlp](https://github.com/alexta69/metube/actions/workflows/update-yt-dlp.yml) every night. Whenever there is a new update of `yt-dlp`, this job will automatically push a new commit to the main branch, which will trigger a build and update to Docker hub. 

Long story short: tonight we should have a new version of the [docker image](https://hub.docker.com/r/alexta69/metube/tags) and can update our instances with `alexta69/metube:latest`

**Comment by gerroon** [comment]
Hi

I just got the latest docker update , and this issue still seems to be there.

**Comment by j3lte** [comment]
> Hi
> 
> I just got the latest docker update , and this issue still seems to be there.

It seems I was mistaken that it would automatically update, as it seems the lockfile still points to the [2023.1.6](https://github.com/alexta69/metube/blob/master/Pipfile.lock#L640) version. We'll have to wait until it is updated by the author I guess

**Comment by gerroon** [comment]
I am sure it was a new update because there was not one couple hours ago. It sounds like you are saying that there is going to be even a newer one than that.

**Comment by wy580477** [comment]
yt-dlp version got updated less than half hour ago. So image build service haven't finished yet. Armv7 version is dragging the whole building process down.


![image](https://user-images.githubusercontent.com/98247050/219823636-64c2b3f8-b1c1-4b41-b81a-f74fbbc64742.png)

**Comment by j3lte** [comment]
@alexta69 I think we can close the issue. Last version of the Docker image has solved the problem.
