### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by Ukhupacha** [alexta69/metube#225]
Hi,

First of all, I want to thank you for everything you have done, it is one of the apps that I use the most.
I used it under its docker form from https://hub.docker.com/r/alexta69/metube.

I wanted to ask if it is possible to update the docker version given the changes with youtube.

Error adding URL: ERROR: [youtube] 9vSQ1b4icVw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Kindly,

**Comment by alexta69** [comment]
Please see [https://github.com/alexta69/metube#updating-yt-dlp](https://github.com/alexta69/metube#updating-yt-dlp).
