### ISSUE TITLE
Download speed problem - Does anyone else have problems - (Germany)?

### ISSUE THREAD

**Issue by creecool** [alexta69/metube#228]
Does anyone else have also a problem when downloading YouTube videos?
I currently have a download rate between 300 - 600 kbps.

Other pages (like f.e. ARD Mediathek) look better there are also times up to 5mbps (maximum of my connection) 
Although the display of the download rate is permanently on change and is now only displayed in kbps.

There is no difference if I change something between the quality or the format.

Installed is the last version from 17.02.2023.

**Comment by PikuZheng** [comment]
This is a known issue of yt-dlp. see #6369 of yt-dlp https://github.com/yt-dlp/yt-dlp/issues/

**Comment by alexta69** [comment]
Since it's a yt-dlp issue and not a MeTube issue, I'm closing this, please track progress on the yt-dlp project.

**Comment by creecool** [comment]
Since a new version of yt-dlp was released 15 hours ago to fix the download issue, I wanted to ask if your project / Docker image automatically refreshes tonight or that needs to be manually?

**Comment by alexta69** [comment]
A new image will be generated tonight, see https://github.com/alexta69/metube#updating-yt-dlp
