### ISSUE TITLE
[Feauture request] custom name

### ISSUE THREAD

**Issue by hellodword** [alexta69/metube#234]
I'm using metube to download and convert m3u8 to mp4, but the m3u8 resouces always have no file name infomation in the links or the responses, so they're always named to `master.mp4` if the link is end of `master.m3u8`.

It'll be great if metube can set a custom name when adding a new task.

**Comment by PikuZheng** [comment]
with http post method, I can assign a ”video title“.
How did you add the task? using the ui normally?

**Comment by PikuZheng** [comment]
I can submit the name while increasing the download queue https://github.com/PikuZheng/metube/commit/3d8e9c40de19bd8e026e9c6370b6396e20022ad2 
But I don't know how to add it in the ui.  I've been using it for a long time in greasemonkey myself.

**Comment by alexta69** [comment]
Fixed by #236 .
