### ISSUE TITLE
More download options, such as downloading a video and thumbnails at the same time

### ISSUE THREAD

**Issue by fejich** [alexta69/metube#24]
Add the following options to the **youtube-dl.conf** file to enable downloading thumbnails

`#Write thumbnail image to disk
--write-thumbnail --embed-thumbnail`

I tried to write the configuration file in the container too, but metube will not read this **/etc/youtube-dl.conf** file

Is there any way to turn on the download thumbnail option?

This project is the most beautiful Youtube-DL WEB UI I have ever used. 
Thank you very much for your work!

**Comment by fejich** [comment]
After some searching, I found that modifying **ytdl.py** can achieve this function.

Finally, I also modified the file encoding format and naming format.

Hope that the relevant options will be opened directly in the web ui.


Line 35
`    def __init__(self, download_dir, quality, info):
        self.download_dir = download_dir
        if quality == 'best':
            self.format = f'bestvideo[vcodec=vp9.2]+bestaudio/bestvideo[vcodec=vp9]+bestaudio'`


Line 56
`    def _download(self):
        try:
            ret = youtube_dl.YoutubeDL(params={
                'quiet': True,
                'no_color': True,
                #'skip_download': True,
                'writethumbnail': True,
                'outtmpl': os.path.join(self.download_dir, '%(title)s[%(resolution)s][%(upload_date)s]'),
                'format': self.format,
                'cachedir': False,
                'socket_timeout': 30,
                'progress_hooks': [lambda d: self.status_queue.put(d)],
                'postprocessors': [
                    {'key': 'EmbedThumbnail',},]
            }).download([self.info.url])
            self.status_queue.put({'status': 'finished' if ret == 0 else 'error'})
        except youtube_dl.utils.YoutubeDLError as exc:
            self.status_queue.put({'status': 'error', 'msg': str(exc)})`

source：
[https://stackoverflow.com/questions/38646886/embedding-thumbnail-to-mp3-with-youtube-dl-raise-exception](url)

**Comment by martadinata666** [comment]
In my suggestion, add download subs options. The other problem is language selection.

My usual command to download videos with subs.
```
/usr/local/bin/youtube-dl -4 -v --write-sub --sub-format srt --sub-lang en -R infinite
```

**Comment by alexta69** [comment]
Hi guys,
These are great ideas. I think the challenge is to integrate them into the UI in a way that would not clutter it.
I think a link saying "More options" to the right or just below the search bar, which opens up a panel with options for downloading thumbnails and subtitles, would be the right way to go about it.
I don't have plans to add it in the near future, but if one of you is up to the task for some Angular hacking, feel free to open a PR and I'll gladly merge it.
Cheers!
Alex

**Comment by fejich** [comment]
I want to help, but I don't know how to write code.

**Comment by alexta69** [comment]
I've added support for specifying youtube-dl options via an environment variable now (check the README), so this should work as a solution, even though it's not via the UI.
