### ISSUE TITLE
[Feature request] Add a way to send the downloaded files to local machine

### ISSUE THREAD

**Issue by TroySigX** [alexta69/metube#241]
I'm hosting MeTube on my server, and from my laptop I request that server to download some medias and want it to automatically send those files to my laptop.

**Comment by alexta69** [comment]
You have two options: either mount the server directory on your laptop via SMB, or click the download icon on the video once it's done downloading and it's in the "Completed" section.
MeTube cannot send the files directly to your laptop (there is no way to implement this).
