### ISSUE TITLE
pornhub : hs 

### ISSUE THREAD

**Issue by lenuxfrance** [alexta69/metube#243]
1 video :
root@xxxxx:~# yt-dlp https://fr.pornhub.com/view_video.php?viewkey=640abc10a38bb
[PornHub] Extracting URL: https://fr.pornhub.com/view_video.php?viewkey=640abc10a38bb
[PornHub] 640abc10a38bb: Downloading pc webpage
[PornHub] 640abc10a38bb: Downloading tv webpage
ERROR: [PornHub] 640abc10a38bb: Unable to extract encoded url; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

root@xxxxxx:~# yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
root@xxxxxx:~#

**Comment by PikuZheng** [comment]
![image](https://user-images.githubusercontent.com/12579522/229357684-493d3b8d-d720-4450-b731-f1b1ec79ee26.png)
is this video available in your location?

**Comment by alexta69** [comment]
Whatever the issue is, it's not with MeTube, but with yt-dlp. If still required, please open it on the yt-dlp project.

**Comment by lenuxfrance** [comment]
I have uninstalled and reinstalled everything the problem is the same
I found to solve the problem https://github.com/yt-dlp/yt-dlp/pull/6685
How can I do in docker to make the modification?

**Comment by lenuxfrance** [comment]
> ![image](https://user-images.githubusercontent.com/12579522/229357684-493d3b8d-d720-4450-b731-f1b1ec79ee26.png) is this video available in your location?

no download

**Comment by PikuZheng** [comment]
metube will automatically upgrade once new version of yt-dlp is released.
