### ISSUE TITLE
yt-dlp options for no metadata not working

### ISSUE THREAD

**Issue by WilliUreta** [alexta69/metube#245]
Hi,
Thanks for making this web UI for yt-dlp, I have an issue with the options. 
When I download an mp3 file, it adds info to the metadata of the file that I don't really want. Specifically the Description/Title, Media/Artists, Media/Years and the thumbnail. 
I've researched a bit and found that the following options should not add any metadata to the file (haven't tried it myself):
`yt-dlp --extract-audio --audio-format mp3 --embed-thumbnail=False --add-metadata --embed-metadata=none <video-url>
`
My current yaml stack contains this ytdl_options:
`environment:
      - YTDL_OPTIONS={"external_downloader":"aria2c","add-metadata":"","embed-thumbnail":"false","embed-metadata":"none"}`
 The docker logs show no error when starting the container so I don't know what is really wrong.

TIA

**Comment by PikuZheng** [comment]
you want to undo this https://github.com/alexta69/metube/pull/86 ?

**Comment by WilliUreta** [comment]
1. How would I undo it? Entering the container and editing the file by hand? I'm guessing pulling a new release would revert it again?
2. Wouldn't this only apply to thumbnails? What about the rest of metadata? Specifically the Title and Artits?

**Comment by PikuZheng** [comment]
just inspect the container and edit dl_formats.py, delete `opts["postprocessors"].append({"key": "FFmpegMetadata"})`, then restart container

**Comment by WilliUreta** [comment]
This would work for all the metadata? Or just the thumbnail? Also, is there a ytdl_option I could set in the stack file?

**Comment by PikuZheng** [comment]
I don't know, sorry.
I haven't tried it, but the expectation is not to save meta information but save thumbnail, because thumbnail has a separate option.

**Comment by WilliUreta** [comment]
I've tried for 5 minutes, and I think (for my case) I should basically remove all 4 lines after `if format not in ("wav"):` as if I don't, it downloads the thumbnail, and it stays not embedded in the file. If I remove the `opts["postprocessors"].append({"key": "FFmpegMetadata"})` it doesn't seem to add it either, so I think I'm set.

That said, I think there should be an option, either in the UI (I'm guessing it's not the right place as it would clutter the UI) or in the ytdl:options that would remove these 4 lines of codes. Just for the fact that they are added either if the user wants them or not, and I think there would be an option that could do it.

If you consider this to be the case, I could open a Feature Request and we could close this ticket. 
Thanks!

**Comment by alexta69** [comment]
@WilliUreta you can set "writethumbnail" to false in YTDL_OPTIONS now, and MeTube won't write the thumbnail and metadata.

**Comment by WilliUreta** [comment]
Sorry to keep replaying to this closed issue, but I want to inform that it works now and it does not embed the thumbnail and metadata. That said, **the webp is still downloaded and kept in the folder**. For me is not a major issue, but maybe we could prevent the download, or clean afterwards. 
Thanks again!
