### ISSUE TITLE
[Feature Request] Split Chapters

### ISSUE THREAD

**Issue by BenJamesAndo** [alexta69/metube#246]
Hello. Would it be possible to use the `--split-chapter` that's part of yt-dlp to split the video into multiple files?

**Comment by PikuZheng** [comment]
yes.
with FFmpegSplitChapters of post processor in ytdl_options, it should work.
but don't use embeeded thumbnal at same time.

**Comment by BenJamesAndo** [comment]
I've tried just now with an environment variable key of `YTDLP_OPTIONS` and Value of `"postprocessors": {"key": "FFmpegSplitChapters"}` but it's saying that YTDL_OPTIONS is invalid.
I couldn't find any mention of FFmpegSplitChapters in the YoutubeDL.py documentation.

**Comment by BenJamesAndo** [comment]
Got it! I didn't have enough brackets.
`{"postprocessors": [{"key": "FFmpegSplitChapters"}]}`

**Comment by BenJamesAndo** [comment]
Now I've noticed that if I'm downloading it as an audio file and specify the format to be M4A that it converts the main downloaded file from webm to m4a, but not the chapter split files, they stay as webm. Is there a way for the split chapter files to also get converted?

**Comment by PikuZheng** [comment]
looks like there are some conflicts... maybe a batch for convert the format after complete of download

**Comment by BenJamesAndo** [comment]
I'm glad you found a fix. Will the change get pushed to the main docker image? I'm not familiar with modifying Docker images so I'm happy to wait for the next release.

**Comment by PikuZheng** [comment]
It looks like the ytdl_options order is an issue. . . I don't know if doing so will have other effects @alexta69 

my suggest is inspect the container, modify this file, and restart the container @BenJamesAndo

**Comment by joeframbach** [comment]
If I'm not mistaken, that commit allows this feature request to be completed, but does not include this feature. Can you reopen?

**Comment by BenJamesAndo** [comment]
I've now tested this and it does indeed convert the split files into the specified audio format. Works perfectly for all formats I tried except .m4a With .m4a the final split files supposedly go longer than they actually do. So if the .webm version is 1 minute, the .m4a file will be 1 minute+what ever is left of the video from that chapter onwards. When I get to the end of 1 minute it stops playing, even though the scrub bar in VLC keeps going.

I'm happy to open this as a new bug report if that's better, as this original bug report is technically solved.

**Comment by alexta69** [comment]
If you decide to open a bug report, please do so on the yt-dlp project, since it's something that yt-dlp does and MeTube has no control over.

**Comment by BenJamesAndo** [comment]
I've used yt-dlp to do split chapters with .m4a and it seems to work fine. Perhaps it's that metube is inserting embedded chapter markers into .m4a files but not others. Either way I'm fine to just use .mp3 files.

**Comment by alexta69** [comment]
MeTube only invokes yt-dlp, it doesn't handle the files in any way.. So I'm not sure how that happens 😞 Glad you have a solution, either way.
