### ISSUE TITLE
Not honoring changed port 

### ISSUE THREAD

**Issue by thefrosty** [alexta69/metube#248]
I have set the compose environment with PORT=8681, and the app is still stealing the 8081 port from another application.

**Comment by alexta69** [comment]
Can you please paste your configuration? It can't steal a port -- even if there's a bug, and it still listens on 8081, it would do that only inside the container.

**Comment by alexta69** [comment]
In your ExpressVPN config, you map port 8691 to 8081. If you're changing MeTube's port to 8691, you want to change the mapping in ExpressVPN accordingly. So just change this line:
```yaml
      - 8691:8081 # metube
```
to this:
```yaml
      - 8691:8691 # metube
```

**Comment by thefrosty** [comment]
Ahh, I thought it wanted the inner port to map.
