### ISSUE TITLE
[Feature Request] Having a temp directory

### ISSUE THREAD

**Issue by neoestremi** [alexta69/metube#250]
Hi, I'm using MeTube on an SBC, with /downloads directory being an NFS share on my NAS.
I thought : torrent clients can have a different temp directory than the output one, could metube have it too ?

**Comment by alexta69** [comment]
You can set a temp directory via YTDL_OPTIONS, see here:
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L231
I suppose it would look like something like this, if I'm formatting it correctly:
`YTDL_OPTIONS={"paths":{"temp":"/path/to/your/temp/dir"}}`
