### ISSUE TITLE
Better Option Documentation

### ISSUE THREAD

**Issue by Townsy45** [alexta69/metube#253]
I am quite new to yt-dlp and this metube app, when trying to use yt-dlp options some of them don't work and it is not clear what options work or what keys to use or where to put them. For example converting thumbnails to png, converting output format to mp4 and metadata management.

The only info we have is to dig through python files to find them and some of them like post-processing lead to nothing and it makes it hard to understand what we need to put.

**Comment by alexta69** [comment]
The options are not MeTube's. MeTube is just a GUI for yt-dlp, and the options belong wholly to yt-dlp, MeTube has no knowledge of them. If you're not satisfied with their documentation, please reopen this issue on the yt-dlp project.
