### ISSUE TITLE
Download Media[Run Script] ERROR: [youtube] Wsb-mlDuFxg: Unable to extract uploader id

### ISSUE THREAD

**Issue by worm69** [alexta69/metube#254]
Hi all i face this issue 
https://github.com/yt-dlp/yt-dlp/issues/6816

Is fixed on yt-dlp side can some one confirm if this project use latest version of yt-dlp or one with fixed bug?
https://github.com/yt-dlp/yt-dlp/issues/6247

Amazing work cheers!

**Comment by alexta69** [comment]
There's a nightly job which checks for a new version of yt-dlp, and if there is one, it's upgraded and a new version of MeTube is released. So once the fix becomes part of a released yt-dlp version, MeTube will be upgraded accordingly the same night.
