### ISSUE TITLE
File disappears when setting a temp directoy

### ISSUE THREAD

**Issue by tr4nt0r** [alexta69/metube#257]
I have a SMB Share for storing downloads but its a bit slow, especially if transcoding with ffmpeg is done, so i set up a temp path in the YTDL_OPTIONS. 
Works fine for the downloading and transcoding part, but when it is finished, the File disappears. It does not get moved/copied to the download folder.
I changed the download folder to a local directory to see if it is a problem with cifs/smb, but it also disappears. I cannot see any errors in the log of the docker container.

**Comment by PikuZheng** [comment]
any postpocessers you're using?
what's the 'download dir' of your config?

**Comment by tr4nt0r** [comment]
This is my configuration:

```
  "environment": {
    "UID": "0",
    "GID": "0",
    "DOWNLOAD_DIR": "/media/",
    "YTDL_OPTIONS": "{\"cookiefile\":\"/config/cookies.txt\", \"usenetrtc\": true, \"paths\":{\"temp\": \"/media/\"}}"
    },
  "map": [
    "share:rw",
    "media:rw",
    "config:rw"
  ],
```

when i download  without any postprocessing it is the same, i see the .part, .ytdl and .webm files in the temp folder as long as the download is running, as soon as the download is completed everything disappears.

**Comment by PikuZheng** [comment]
so... after download finished, cp .webm to /media/ (download dir) and delete /media/ (temp dir) ? that's an issue.

**Comment by PikuZheng** [comment]
anyway, the most likely reason is smb permissions, especially Synology.
In order to investigate this issue, my recomment is to inspect container and test read/write of /media/subfolders/. It looks like there is a problem with the mount of the subfloders, or a permission issue causing it to blackhole.

**Comment by tr4nt0r** [comment]
it happens also with local folders, not only smb shares

**Comment by PikuZheng** [comment]
Please verify that there is enough free space

**Comment by tr4nt0r** [comment]
more than 38Gb free. the files i used for tested were between 100-300 Mb

**Comment by tr4nt0r** [comment]
using the shell command within the docker container with the option `-P temp:/tmp` works without problems. Also tried `-P temp:/tmp,home:/media/Downloads`, no problem either.

**Comment by PikuZheng** [comment]
Confirmed that this is an issue. 
After specifying YTDL_OPTIONS": "{"paths":{whatever}}", it causes ignoring the incoming parameters (DOWNLOAD_DIR or selected subfolders). In other words, YTDL_OPTIONS": "{"paths":{whatever }}" overrides all paths not just the specified one.
For subfolder selection, there are more additional issues. I don't use this feature myself, so 🤣

**Comment by PikuZheng** [comment]
All the while I specified the DOWNLOAD_DIR to /tmp and used postprocessers to move the file after the download was complete. it works fine, never got an error 🤣

**Comment by alexta69** [comment]
The issue with "paths" in YTDL_OPTIONS overriding DOWNLOAD_DIR is apparently how yt-dlp works.. Not much we can do here. As to the issue of the OP, I'm not quite sure what it might be. It seems to work for other people so I'm guessing it's some sort of local misconfiguration but I have no idea..

**Comment by PikuZheng** [comment]
> The issue with "paths" in YTDL_OPTIONS overriding DOWNLOAD_DIR is apparently how yt-dlp works.. Not much we can do here. As to the issue of the OP, I'm not quite sure what it might be. It seems to work for other people so I'm guessing it's some sort of local misconfiguration but I have no idea..

any possible, to define temp dir in env instead of ytdl_options?

**Comment by tr4nt0r** [comment]
files are copied over correctly if I set both temp and home in YTDL_OPTIONS, so yes, it seems to completely override everything else so unfortunately I cannot select a Subfolder as destination in the UI anymore. Sad :(
