### ISSUE TITLE
Error adding URL

### ISSUE THREAD

**Issue by Hannibal7777** [alexta69/metube#267]
No download possible for a few weeks:

Error adding URL: ERROR: [youtube] dQw4w9WgXcQ: Unable to download API page: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again')))

**Comment by PikuZheng** [comment]
Looks fine unless you provide more information
![image](https://github.com/alexta69/metube/assets/12579522/87834fe2-2545-44bd-9295-f803a7cc5a87)

**Comment by vacances** [comment]
I get the same error message on any yt video. 
```
ERROR: 
[download] Got error: <urlopen error [SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1131)>
```
I tried to troubleshoot that. I host my own DNS and blocked wildcard address googlevideo.com
example:
`rr2---sn-oxup5-3ufz.googlevideo.com`
is indeed preventing the download. Can we bypass that disgusting stuff somehow? Youtube works fine on all of the devices at home. It was working fine few weeks ago as @Hannibal7777 mentioned above.

**Comment by PikuZheng** [comment]
> I tried to troubleshoot that. I host my own DNS and blocked (wildcard) the address of googlevideo.com
> example:
> `rr2---sn-oxup5-3ufz.googlevideo.com`
> It is indeed preventing the download.

After Google knows your IP, it will allocate this server according to the recognized geographical location. Perhaps there are different servers inside and outside the container. 
I think you should to investigate networking issues inside the container.

**Comment by alexta69** [comment]
Either way, it's not a problem we can solve in MeTube. If a solution is necessary, it'd be in yt-dlp, so the issue needs to be reopened on that project. Closing here.

**Comment by Hannibal7777** [comment]
Indeed the network seems to be the problem. 
Quick workaround, is to change the network of the container to host. This works for me fine.
Thanks for helping!

**Comment by vacances** [comment]
Switching from host to bridge in docker fixed the issue (lol). Now i just have to grow old to get some yt-dl merges coming for other websites aswell. Thanks.
