### ISSUE TITLE
longer file names are not supported

### ISSUE THREAD

**Issue by nothanks91** [alexta69/metube#271]
i am getting following error while trying to download few videos, 

ERROR: unable to open for writing: [Errno 36] Filename too long:

i am able to download similar videos using cli by passing (-o "%(title).100B [%(id)s].%(ext)s") in download command. 

is there a way we can incorporate this restriction in GUI itself?

**Comment by PikuZheng** [comment]
yes
just set OUTPUT_TEMPLATE as python string-format.
for example, %(title).50s (default is %(title).s) means cut title to 50 letters which is suitable for most file system

**Comment by nowjon** [comment]
This worked for me
Originally: %(channel)s/%(title)s.%(ext)s
Now: %(channel)s/%(title).50s.%(ext)s
