### ISSUE TITLE
PORT environment variable (feature request)

### ISSUE THREAD

**Issue by evert-mouw** [alexta69/metube#283]
Having a configurable PORT using an environment variable (`PORT`) would be nice.

I guess the last line of `main.py` could be replaced with something like...

```
web.run_app(app, port=config.PORT)
```
While also adding to the Config class:
```
class Config:
    _DEFAULTS = {
        'PORT': '8081',
```

**Comment by alexta69** [comment]
It's there:
https://github.com/alexta69/metube/blob/dd0f96c6af1994fbf050f6475ab862d4064daae8/app/main.py#L31
It's not documented because frankly I don't see much reason to change it. But someone wanted it enough to submit a PR, so it's there :)

**Comment by evert-mouw** [comment]
Super, thanks a lot! It makes updating and maintenance easier for my home server so I'm happy :-)
