### ISSUE TITLE
Download progress bars are not displaying correctly using YTDL_OPTIONS

### ISSUE THREAD

**Issue by JunioCalu** [alexta69/metube#289]
Download progress bars are not displaying correctly using YTDL_OPTIONS='{"external_downloader": "aria2c", "external_downloader_args":["-c","-j 16","-x 16","- s 16","-k 5M"]}'. I'm using the docker version.

**Comment by PikuZheng** [comment]
see #67 please

**Comment by JunioCalu** [comment]
> see #67 please

thanks for the clarification.
