### ISSUE TITLE
Bookmarklet?

### ISSUE THREAD

**Issue by kushfest** [alexta69/metube#29]
I'm really enjoying metube! Is there a way to add a download by URL? I'd love to try to create a bookmarklet to quickly add downloads to metube without having to have metube open. Thanks!

**Comment by alexta69** [comment]
Hey!
Glad to hear you like it! And the bookmarklet is a great idea!
It's possible to add a video by issuing a `POST` request to `/add` with two parameters, `url` and `quality` (where `quality` is one of `best`, `1440p`, `1080p`, `720p`, `480p`, `audio`, or `custom:...`, in which you can specify a custom string to send to youtube-dl). If you can generate this `POST` request from the bookmarklet, then it should work.
Let me know what you think and if you get it to work, it sounds pretty useful!
Thanks,
Alex

**Comment by kushfest** [comment]
Awesome! I'm new to javascript, but after much noodling I've got this bookmarklet working in the Chrome and Brave browsers. Firefox seems close, but not working yet. Maybe someone more JS experienced can give me some pointers to fix that. I'm going try to get it to display a pop-up to confirm if the add was successful or not. We'll see how that goes hah.

To use on another server, just change the URL in the code. I've hard coded best quality, but that can be changed in the code as well. Also, this currently only works with a metube instance behind reverse proxy. I presume that's CORS related.

`javascript:!function(){xhr=new XMLHttpRequest();xhr.open("POST","https://metube.domain.com/add");xhr.send(JSON.stringify({"url":document.location.href,"quality":"best"}))}();
`

**Comment by alexta69** [comment]
Thanks so much! Perhaps I'll add it to the README, with your permission (and with credit), so others can enjoy it too.
I guess that if you're on an HTTPS page (like YouTube), it won't let you access an HTTP site from that page, so that's why it only works if your metube is behind an HTTPS proxy.

**Comment by kushfest** [comment]
That makes sense about the HTTP vs HTTPS limitation. Feel free to add to the readme. Thanks!

**Comment by shoonya75** [comment]
Thank you @alexta69 for MeTube And @kushfest  for the bookmarklet. I do not know javascript, but I was able to make the bookmarklet work for Firefox (ver 89.0.2) with minimal change (seems a matter of syntax). Maybe someone with more experience can test and verify this.  

javascript: (function() { xhr=new XMLHttpRequest();xhr.open("POST","https://metube.domain.com/add");xhr.send(JSON.stringify({"url":document.location.href,"quality":"best"}));xhr.onload=function(){if(xhr.status==200){alert("Sent to metube!")}else{alert("Send to metube failed. Check the javascript console for clues.")}}})();

**Comment by alexta69** [comment]
Thanks @shoonya75! I've added it to the README.
