### ISSUE TITLE
Feature request: authentication screen by default

### ISSUE THREAD

**Issue by JunioCalu** [alexta69/metube#290]
implementing an environment variable that enables a simple authentication screen for the program could be useful when the DELETE_FILE_ON_TRASHCAN=true option is being used. If this is not possible, creating documentation on how to do this using the linuxserver/swag docker image would be very useful for laypeople.

**Comment by alexta69** [comment]
The README mentions that Authelia can be used with the linuxserver/swag image for authentication. 

You can google and find guides on how to do that very easily. There's nothing MeTube-specific in that, so I don't think the MeTube documentation needs to include that.
