### ISSUE TITLE
minor documentation update on usage of YTDL_OPTIONS

### ISSUE THREAD

**Issue by myTselection** [alexta69/metube#295]
Dear,
Thanks for this metube! It's working very well!
The documentation README on github and docker hub shows an example of the usage of YTDL_OPTIONS. Yet, in order to be able to use it correctly, a single quote needs to be added around the full option. It took me quite some time before realizing this. Might be useful if the readme would be updated to show a correct example.
Btw , an example on the usage of the command line option `--no-mtime` that can be achieved using YTDL_OPTION `{"updatetime": false}` might also be usefull for others, to make sure the file timestamp is set to current now time and not to the youtube upload timestamp provided in youtube headers.
```
    environment:
      - 'YTDL_OPTIONS={"updatetime": false}'
```

**Comment by alexta69** [comment]
Thanks! I incorporated your suggestions.
