### ISSUE TITLE
Memory leak when downloading many videos.

### ISSUE THREAD

**Issue by ArabCoders** [alexta69/metube#297]
Hello,

I use this excellent tool to archive youtube channels, and it's works perfectly for my use case. Sadly, i think i managed to break something within the browser side, however the tool itself in the container doesn't crash.

![image](https://github.com/alexta69/metube/assets/1621552/762e8855-9055-412c-b1a3-4deee216b8de)

it keep going up and up until chrome's crashes the tab 

![image](https://github.com/alexta69/metube/assets/1621552/c45cee96-5a48-4022-ad8f-c44ec47b80c3)

However checking the container stats does not seems to be leaking internally, which lead me to believe it's something to do with the frontend side.

![image](https://github.com/alexta69/metube/assets/1621552/0fb293b6-ed6a-4d1a-8689-bb49ec2ab740)

at the time of writing this issue, there was around 200ish video queued to be downloaded.

**Comment by PikuZheng** [comment]
I think this is a problem when angular handles websocket (downloading progress bar)

**Comment by ArabCoders** [comment]
> I noticed memory growth while downloading videos. But when I switch the tab to background, chrome reclaims the memory. Why not just close the tab after adding the video download queue?

In my case, it reclaim the memory by killing the tab, i don't think closing the web UI is a solution for this problem, i personally like checking the status of all downloads. i do believe it has something to do with the progress bar, also what bothers me is i cant even run the memory debugger as it's crashes as well

**Comment by PikuZheng** [comment]
You are correct. . . I use mobile notifications to let me know when a download succeeds or fails.
Dev tools - javascript vm instance memory doesn't seem to grow, it doesn't seem to work.
