### ISSUE TITLE
Status bar not working on ABC iView

### ISSUE THREAD

**Issue by lukyjay** [alexta69/metube#30]
Hi

Running on Docker.

I've tried to download this URL:
https://iview.abc.net.au/video/FA1905H001S00

It works fine but there is no status bar. I assume you might be geoblocked from iview since it's Australian and you might be from another country.

How can I troubleshoot this and help resolve?

Thank you for your software, I find it very useful

**Comment by alexta69** [comment]
Hey.
So the status bar goes from empty to full directly, when it finishes downloading?
You could try running youtube-dl on the command line and see if it gives you the percentage there while downloading. The percentages rely on the site telling youtube-dl the size of the video in advance, maybe this site doesn't do that..
Cheers!
Alex

**Comment by lukyjay** [comment]
> You could try running youtube-dl on the command line and see if it gives you the percentage there while downloading. The percentages rely on the site telling youtube-dl the size of the video in advance, maybe this site doesn't do that..

You're right, there is no progress! It shows a green progress bar with no ETA or speed. Ideally it would either say 'N/A' or something similar.

I can see the layout is held in app.component.html but I've never used angular before. I assume (from the documentation), that this code might help?

```
<div *ngIf="!download.value.speed; then noProgress else Progress"></div>
<ng-template #noProgress>Downloading...</ng-template>
<ng-template #Progress>EXISTING PROG BAR, ETA AND SPEED CODE HERE</ng-template>
```

As you can see I have no idea what I'm doing, appreciate your guideance :)

**Comment by alexta69** [comment]
Did you try running the command line version of youtube-dl? I wonder whether it shows progress there, or not...
The Angular code doesn't really tell us anything... The interesting bit is the HTTP response that comes back from the server, and whether it contains the Content-Length header which tells the full size of the file that is being downloaded. Most likely this is how youtube-dl infers the percentages. Unless it has the full size in the HTML somewhere. It's really site-dependent.

What does the green progress bar look like? Is it green with diagonal bright lines, like in the beginning, right after the video is added? And is there any text inside?

**Comment by lukyjay** [comment]
Sorry my previous reply wasn't clear. I meant to suggest that you are right and that the output from youtube-dl does not include progress so it's impossible for metube to know this.

This is what metube shows: https://imgur.com/k7aX9TM
This is what youtube-dl shows: https://pastebin.com/HWvW4Dbn (I manually cancelled it a few seconds in)

Can we use my code suggestion above to update the angular on metube to show something else like "Loading..." rather than a green progress bar with no ETA or speed when the data isn't available?

**Comment by alexta69** [comment]
Got it, I understand the situation.
At the moment, the green bar with the stripes you're seeing is in fact the "Loading.." bar. As long as no progress updates are received from youtube-dl, this is shown. So it's equivalent to your suggestion, except it's graphic instead of textual. I wouldn't want to replace it with text, I think it'd be less pretty than the current solution...

**Comment by lukyjay** [comment]
Hi

No problem :)

Thanks again!
