### ISSUE TITLE
ERROR: This video is only available to Music Premium Members

### ISSUE THREAD

**Issue by L4ma** [alexta69/metube#300]
Hi,
I noticed a problem with MeTube today. I actually wanted to start downloading some audio books from "The Three ???", but unfortunately I get the error that this episode is only available for Music Premium Members. I didn't have this problem a few weeks ago. 

I have the following screenshot from the Docker log:
![Bildschirm­foto 2023-07-20 um 08 34 13](https://github.com/alexta69/metube/assets/26965333/790edb6d-726a-4f02-af0f-ade9805d446b)

Can anyone help me with this?

**Comment by PikuZheng** [comment]
I try to open this video in youtube and it says can't play. I believe it is a limitation of youtube itself.
