### ISSUE TITLE
Subtitles not downloading

### ISSUE THREAD

**Issue by drd2aiki** [alexta69/metube#305]
Using this string in my docker-compose file:

`- YTDL_OPTIONS={"writesubtitles":true,"allsubtitles":true,"subtitleslangs":["en","-live_chat"],"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true}]}`

But I still cannot get subtitles to download with the video/audio. What am I doing wrong?

**Comment by PikuZheng** [comment]
I suspect that YTDL_OPTIONS is not properly configured. Due to https://github.com/alexta69/metube/issues/303#issuecomment-1650666547, try changing array to object please.

**Comment by drd2aiki** [comment]
I've reviewed that thread (#303) and I'm not sure what you mean. I'm running Metube through Docker. Here's my compose file:

`version: "3.6"
services:
  metube:
    container_name: metube
    image: alexta69/metube:latest
    environment:
      - TZ=America/New_York
      - UMASK_SET=022
      - PUID=1005
      - PGID=100
      - DELETE_FILE_ON_TRASHCAN=true
      - DOWNLOAD_DIR=/downloads
      - STATE_DIR=/downloads/.metube
      - YTDL_OPTIONS={"writesubtitles":true,"verbose":true,"allsubtitles":true,"subtitleslangs":["en","-live_chat"],"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true}]}
    logging:
      driver: json-file
      options: {}
    ports:
      - 8081:8081/tcp
    restart: unless-stopped
    volumes:
      - /mnt/media/metube:/downloads
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app`

Is my YTDL_OPTIONS line incorrect?

Thank you!

**Comment by PikuZheng** [comment]
Using the compose you provided, it looks like everything works fine

![image](https://github.com/alexta69/metube/assets/12579522/1904b42a-2066-4047-bc29-4ac2ff2a0c47)

**Comment by drd2aiki** [comment]
Yes. That worked! Awesome, thank you so much.
