### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by richardhughes260** [alexta69/metube#307]
1) Download SRT & TXT files from YouTube
2) Download YouTube Thumbnails

Thanks so much for this application!

As a content creator I use downloads all the time from various video platforms.

**Comment by hungntv** [comment]
From my customers, "Any chance of being able to get subtitles?"

![image](https://github.com/alexta69/metube/assets/4994141/4eaf95d2-8ac1-498a-952a-e2e07492bd27)

**Comment by PikuZheng** [comment]
> From my customers, "Any chance of being able to get subtitles?"
> 
> ![image](https://user-images.githubusercontent.com/4994141/261776839-4eaf95d2-8ac1-498a-952a-e2e07492bd27.png)

see #305 fyi
