### ISSUE TITLE
Facebook videos will download but not Facebook reels

### ISSUE THREAD

**Issue by Tonynks** [alexta69/metube#309]
I can download
https://fb.watch/mmOasdHS5A/
But not
https://www.facebook.com/watch/?v=3009146216032116

The second link regardless of cookies or not says no video format.  

Is there a solution?

**Comment by Tonynks** [comment]
If I change URL to d.facebook.com then play the video and use link it makes, then it works.

**Comment by PikuZheng** [comment]
yt-dlp fixed it on July 11th, please wait for the next release or compile nightly binary by yourself

**Comment by Tonynks** [comment]
Is the command 
`docker pull yt-dlp/yt-dlp:2023.08.12.042625 `

**Comment by Tonynks** [comment]
What's the command inside sh to upgrade yt-dlp.  
pip install --upgrade --pre yt-dlp only pulles latest not the nightly.

**Comment by Tonynks** [comment]
For anyone else I found solution.  
Sh into the metube container
`docker exec -it metube sh`
Then go-to the /usr/local/bin dir 
Then issue this command 
`pip install --force-reinstall https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2023.08.12.042625/yt-dlp.tar.gz`

Then restart the container.
