### ISSUE TITLE
Support H.264 as default

### ISSUE THREAD

**Issue by hctrr** [alexta69/metube#313]
Both 07 and 08 releases download the video as vp9 over the ~06 release of H.264
Quality: 1080p
Format: MP4

Any support to revert to H.264?

**Comment by PikuZheng** [comment]
according [this](https://github.com/yt-dlp/yt-dlp/issues/7541#issuecomment-1684945951), maybe set YTDL_OPTIONS={"format":"h264"} will help (my guess)

**Comment by ArabCoders** [comment]
in my case `YTDL_OPTIONS={"format_sort": ["codec:avc:m4a"]}` did revert back to h264 mp4 downloads. not sure if it's universal tho

**Comment by hctrr** [comment]
> in my case `YTDL_OPTIONS={"format_sort": ["codec:avc:m4a"]}` did revert back to h264 mp4 downloads. not sure if it's universal tho

thank you for the share.

I tried with the most recent release (2023-08-19) but it looks like it's still downloading as vp9.
I'll look into the YTDL_OPTIONS to see possible alternatives.

**Comment by hctrr** [comment]
> in my case `YTDL_OPTIONS={"format_sort": ["codec:avc:m4a"]}` did revert back to h264 mp4 downloads. not sure if it's universal tho

this did the trick. 
the catch was there was a space in the initial code share `: [`

working value:
`YTDL_OPTIONS={"format_sort":["codec:avc:m4a"]}`

I'll be testing the `"format_sort_force"` option, but overall the code snippet from @ArabCoders does the trick.
