### ISSUE TITLE
TikTok downloads don't work

### ISSUE THREAD

**Issue by auanasgheps** [alexta69/metube#32]
Hi,
Trying to download any TikTok video, I get:

![image](https://user-images.githubusercontent.com/20586878/123947902-2e056680-d9a1-11eb-9a53-c0596717c08c.png)

I don't know how to get logs in this container, so I can't provide much information.

By reading here and there looks like I would have to pass the authentication info for TikTok, but this container does not have such option.

**Comment by alexta69** [comment]
Hi,
You can get the container logs with the `docker logs` command -- e.g. `docker logs metube` if your container is named `metube`. If you find the problem description there, then you can file it at https://yt-dl.org/bug as they suggest.
As to authentication, there is indeed no such option in MeTube at the moment. I don't have immediate plans to add it, but if you want to take a crack at it, you're welcome to submit a PR!
Cheers
Alex

**Comment by auanasgheps** [comment]
All I got is


```
INFO:ytdl:adding https://www.tiktok.com/@swannfreestyle/video/6975204249546362117?is_copy_url=1&is_from_webapp=v1
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
INFO:aiohttp.access:192.168.0.100 [08/Jul/2021:18:12:51 +0000] "POST /add HTTP/1.1" 200 547 "http://192.168.0.101:5802/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
```
Would there be a way to pass credentials via command/docker compose?
Probably it's easier than building a UI just for that.

**Comment by alexta69** [comment]
Actually it looks like it should be possible to hack it together. youtube-dl accepts credentials via a .netrc file (as documented here: https://github.com/ytdl-org/youtube-dl/blob/master/README.md#authentication-with-netrc-file). So if you create such a file, and mount it into the docker container as `/.netrc` (as the home directory of the process inside the docker is `/`), it should work.
Let me know if you get it to work!

**Comment by auanasgheps** [comment]
Hi, can you please provide more details? I finally had the time to have a look at this, but I cannot mount / 

Should I mount /home? If I do so, I still don't see the file. 
Maybe it's /root?

**Comment by auanasgheps** [comment]
I've also done as you said, but still doesn't work, I get the same error.

`      - /docker-apps/youtube-dl/.netrc:/.netrc`

**Comment by alexta69** [comment]
have you entered all the correct information in the netrc file?
I'm not sure how to help at this point, since this already has to do with youtube-dl itself..

**Comment by alexta69** [comment]
I've added support for youtube-dl options now (check the README), so if the netrc way does not work for you, you can also use the username and password options.

**Comment by auanasgheps** [comment]
Thank you! I will check it out!
