### ISSUE TITLE
[req] put size of file on the webpage please

### ISSUE THREAD

**Issue by WarHawk8080** [alexta69/metube#322]
It would be nice to show the size of the file on the webpage listing all the downloads...thanks

**Comment by vkartk** [comment]
Hey, great point about showing file size! I'm already on it and will get a PR up with that feature shortly. Anything else you'd like to see in the downloads list?

**Comment by WarHawk8080** [comment]
Only other thing I can think of is maybe "Date downloaded"

**Comment by PikuZheng** [comment]
fix #383 will be perfect, I make a wish

**Comment by vkartk** [comment]
@alexta69 Have you considered showing download dates alongside file sizes in the download list? I think it could be quite helpful for users to track their downloads.

**Comment by vkartk** [comment]
@PikuZheng 

> fix #383 will be perfect, I make a wish

I'll definitely check it out and see what I can do.
