### ISSUE TITLE
Is yt-dlp parse-metadata option available?

### ISSUE THREAD

**Issue by TheWicklowWolf** [alexta69/metube#326]
How do you implement this option:

Interpret the title as "Artist - Title"
$ yt-dlp --parse-metadata "title:%(artist)s - %(title)s"

**Comment by TheWicklowWolf** [comment]
This doesn't seem to work:
```yaml
    environment:
      - 'YTDL_OPTIONS={"parse_metadata":"title:%(artist)s - %(title)s"}'
```

**Comment by PikuZheng** [comment]
you need `MetadataParser` of `postprocessor` I think.

I'm not familiar with this but it should look like `'YTDL_OPTIONS={"postprocessors":[{"key":"MetadataParser","actions":[(what is to do)]}]}'`

**Comment by TheWicklowWolf** [comment]
> you need `MetadataParser` of `postprocessor` I think.
> 
> I'm not familiar with this but it should look like `'YTDL_OPTIONS={"postprocessors":[{"key":"MetadataParser","actions":[(what is to do)]}]}'`

That didn't work, I don't think `MetadataParser` is a valid option.
Thanks anyway
