### ISSUE TITLE
Remove files 

### ISSUE THREAD

**Issue by DavidHenryThoreau** [alexta69/metube#334]
It might be interesting to remove files when `DOWNLOAD_DIRS_INDEXABLE`

**Comment by PikuZheng** [comment]
are you meaning DELETE_FILE_ON_TRASHCAN？

**Comment by DavidHenryThoreau** [comment]
I've enabled it but, How to remove files if there is no one appears on downloading history ?

**Comment by PikuZheng** [comment]
> I've enabled it but, How to remove files if there is no one appears on downloading history ?

go to download dir and delete files

**Comment by DavidHenryThoreau** [comment]
I'd like to use MeTube to download , watch, and also remove, which is behind reverse proxy ssh access is not enable I don't want to connect thtough ssh just to remove files.
I mean maybe add a remove button on `http://metube/download` for each downloaded files

**Comment by PikuZheng** [comment]
After you enable DELETE_FILE_ON_TRASHCAN, removing a completed task from the list will also delete the file. 
For files that are not in the list before this feature is enabled, your best option is to install a file management system. I think you don’t want anonymous to randomly delete files.

**Comment by DavidHenryThoreau** [comment]
Yes, I don't want to randomly delete files but I think a delete button might be interesting

**Comment by MauriceTartiflette** [comment]
Hello, I've installed MeTube on my Synology NAS. It works perfectly but I can not succeed to localize the file downloaded on the NAS. I can not find the rep "/download" in the field manager. Maybe you can help. Thank you

**Comment by DavidHenryThoreau** [comment]
Do you have enable `DELETE_FILE_ON_TRASHCAN` in env var in your `docker-compose.yml` ? 

```
    environment:
      - DELETE_FILE_ON_TRASHCAN=true
```

**Comment by DavidHenryThoreau** [comment]
Do you have enable `DOWNLOAD_DIRS_INDEXABLE` in env var in your `docker-compose.yml` ?

```
    environment:
          - DOWNLOAD_DIRS_INDEXABLE=true

```

**Comment by PikuZheng** [comment]
> Hello, I've installed MeTube on my Synology NAS. It works perfectly but I can not succeed to localize the file downloaded on the NAS. I can not find the rep "/download" in the field manager. Maybe you can help. Thank you

I believe it's synology's issue. you should map /download to `/Volume/Shared Floder/sub floder` (mine is `/Volume2/admin/videos` for example). If you're using /SharedFloder only, then you'll get nothing.

**Comment by alexta69** [comment]
There is a delete button, and if you enable DELETE_FILE_ON_TRASHCAN, it indeed deletes the files as you require. So it seems that the need is met. If it isn't, please reopen with an explanation of the missing functionality.

**Comment by DavidHenryThoreau** [comment]
> There is a delete button, and if you enable DELETE_FILE_ON_TRASHCAN, it indeed deletes the files as you require. So it seems that the need is met. If it isn't, please reopen with an explanation of the missing functionality.

- The folder that contains video does not seems to be deleted
- I've got old videos on /download how can I delete them ?

**Comment by alexta69** [comment]
Both questions point to a file management solution, which MeTube is not. I'm not sure on what sort of storage your download folder resides, but you'll want to manage files there the same way you manage them elsewhere. For example mount the folder as a drive on your computer (assuming it's a NAS or another kind of remote storage) and manage files that way.

**Comment by DavidHenryThoreau** [comment]
Here's the MeTube's ariables my docker-compose.yml

```
      - DOWNLOAD_DIRS_INDEXABLE=true
      - DELETE_FILE_ON_TRASHCAN=true
      - TEMP_DIR=/tmp
      - STATE_DIR=/tmp
      - DOWNLOAD_DIR=/downloads
      - AUDIO_DOWNLOAD_DIR=/mnt
      - OUTPUT_TEMPLATE=%(playlist)s_%(id)s/%(title)s.%(ext)s
      - 'YTDL_OPTIONS={\"add-metadata\":true}'
```

Yes but If downloaded files are old or I want to remove some of them.
I'm using MeTube behind reverse proxy and access to the directory by ssh is not enable on the Internet.
The point at the beginning of the issue was to permit user to manager files on  : 
```
      - DOWNLOAD_DIR=/downloads
      - AUDIO_DOWNLOAD_DIR=/mnt
```

**Comment by DavidHenryThoreau** [comment]
Here's the MeTube's variables `docker-compose.yml`

```
      - DOWNLOAD_DIRS_INDEXABLE=true
      - DELETE_FILE_ON_TRASHCAN=true
      - TEMP_DIR=/tmp
      - STATE_DIR=/tmp
      - DOWNLOAD_DIR=/downloads
      - AUDIO_DOWNLOAD_DIR=/mnt
      - OUTPUT_TEMPLATE=%(playlist)s_%(id)s/%(title)s.%(ext)s
      - 'YTDL_OPTIONS={\"add-metadata\":true}'
```

Yes but If downloaded files are old or I want to remove some of them.
I'm using MeTube behind reverse proxy and access to the directory by ssh is not enable on the Internet.
The point at the beginning of the issue was to permit user to manage files on  : 
```
      - DOWNLOAD_DIR=/downloads
      - AUDIO_DOWNLOAD_DIR=/mnt
```

**Comment by alexta69** [comment]
Then I suggest you to look for a remote file management solution, maybe something from this list: https://github.com/awesome-selfhosted/awesome-selfhosted?tab=readme-ov-file#file-transfer---web-based-file-managers

**Comment by DavidHenryThoreau** [comment]
Yes some web based file manager exist (thanks for the list)
I mean just add a X for delete and the ability to rename file may be useful
I've got a low power arm based machine, that mean I've to install another application just to rename or remove, it's a by overkill.
Some project you link are overkill just to remove or rename file on a directory.

**Comment by DavidHenryThoreau** [comment]
Yes some web based file manager exist (thanks for the list)
I mean just add a X for delete and the ability to rename file may be useful
I've got a low power arm based machine, that mean I've to install another application just to rename or remove, it's a just overkill.

**Comment by DavidHenryThoreau** [comment]
Yes some web based file manager exist (thanks for the list)
I mean just add a X for delete and the ability to rename file may be useful
I've got a low power arm based machine, that mean I've to install another application just to rename or remove, it's just overkill.
