### ISSUE TITLE
Allow multiple cookies.

### ISSUE THREAD

**Issue by nodew** [alexta69/metube#338]
For example:
```
|- cookies
   |- www.youtube.cookies
   |- www.bilibili.cookies
```
When downloading videos with given URL, it should search the cookies folder first, if there's no match domains, then download without cookie, otherwise, download with the matched cookies.

**Comment by PikuZheng** [comment]
you can add them to one file.

**Comment by nodew** [comment]
Adding to one file might solve the problem, but it's not a good solution as when you want to update the cookie.

**Comment by PikuZheng** [comment]
Have you tried file wildcards? like `YTDL_OPTIONS={"cookiefile":"/metube/cookies/*.txt"}`

**Comment by alexta69** [comment]
Such functionality would need to be added by yt-dlp (if it isn't there already), and not by MeTube, so please reopen on that project if necessary.
