### ISSUE TITLE
Add option for auto download.

### ISSUE THREAD

**Issue by nodew** [alexta69/metube#339]
Add a new option along with current Format and Quality, because in a page, there might be a few videos, but user might only what to download one or two of them, then user should be able to turn off the auto download feature, after clicking on `Add`, the main page will only show all available items instead of starting download, user can choose which they what to download.

**Comment by PikuZheng** [comment]
Do you mean when adding a list, all videos should be added to the queue so that users can cancel unnecessary downloads in time?

**Comment by nodew** [comment]
Yes, for example:

| Name | action |
|-----------|-----------|
| video a | `download` / `cancel` / ... |
| video b | `download` / `cancel` / ... |

User can click on the `download` button to start download.

**Comment by alexta69** [comment]
Fixed in #353
