### ISSUE TITLE
Add --restrict-filenames option to youtube-dl

### ISSUE THREAD

**Issue by MisterX2000** [alexta69/metube#34]
It would be nice to have the option to add custom parameters like `--restrict-filenames` to youtube-dl.
Especially when using a custom output format, I'd like to have the option to make it more compatible to other OSes.

Info, what `--restrict-filenames`  does:
> In some cases, you don't want special characters such as 中, spaces, or &, such as when transferring the downloaded filename to a Windows system or the filename through an 8bit-unsafe channel. In these cases, add the --restrict-filenames flag to get a shorter title.

**Comment by alexta69** [comment]
I guess it could be added via an environment variable. Feel free to submit a PR!
