### ISSUE TITLE
how to start download task only on python side . without any web request or any javascript code.

### ISSUE THREAD

**Issue by xkungxfu** [alexta69/metube#341]
because I want to download videos programmatically.I don't nead a node js website. 

I write some code to try, but failed. 
```

class YoutubeWrapper:
    def __init__(self):
        config = Config()
        notifier = Notifier()
        
        self.dqueue = DownloadQueue(config, notifier)
        asyncio.run(self.initialize())

    async def initialize(self):
        await self.dqueue.initialize()

    async def addxxx(self):
        url = "https://www.youtube.com/watch?v=UyduZMDY_xA"
        #url = "https://www.youtube.com/@Soothingsound3107"
        quality = "best"
        format = ""
        folder = ""
        custom_name_prefix = ""
        status = await self.dqueue.add(url, quality, format, folder, custom_name_prefix)

if __name__ == '__main__':
    yw = YoutubeWrapper()
    asyncio.run(yw.addxxx())

```
so, my question is how to modify my code.  to start download task only on python side . 

It seems that the code "await self.event.wait()" break the function "__download". I am not sure, and have no idea. Please give some suggestions ,thanks!

**Comment by PikuZheng** [comment]
why not just use yt-dlp command like
```
import os
os.system("yt-dlp https://youtu.be/xxxxxxx")
```

**Comment by xkungxfu** [comment]
I don't know how to execute the command in async and multiple threads.

**Comment by PikuZheng** [comment]
maybe `subprocess.Popen("yt-dlp https://youtu.be/xxxxxxx")` is better? it can be run multiple times without waiting for it to complete, and does not require async

**Comment by xkungxfu** [comment]
thank you. I will try it as your advice.

**Comment by alexta69** [comment]
The point of MeTube is the UI, so use cases that don't involve the UI aren't part of this. Closing
