### ISSUE TITLE
problems downloading m3u8 links with identical file names

### ISSUE THREAD

**Issue by gitwittidbit** [alexta69/metube#345]
So I am downloading videos via m3u8 links from time to time that are distributed via Akamai.

Akamai seems to always use the same file name for all videos (at least from this source) and to differentiate between different videos only in terms of the path part of the link. The consequence is that metube names all videos the same. 

The problem with this is that as long as a video of the same name still exists in the download folder, the new (different) video with the same name will not be downloaded (because it appears to have been downloaded already). Even if I clear the downloaded video from the downloaded files list in the GUI (which leaves the actual file untouched), the new download is skipped. I have to actually delete the previous file (or rename it).

Would it be possible to either download the new video with the same name (maybe ask "are you sure?") and add (2), (3), etc. to the file name or add a function to allow me to change the name of the file on disk from the GUI?

Or does anyone know a trick to work around this issue?

**Comment by PikuZheng** [comment]
looks same as #342

A better way is to add a variable in the file name. Such as date and time. Or specify a different folder when downloading manually.

**Comment by PikuZheng** [comment]
looks same as #342

A better way is to add a variable in the file name. Such as date and time. Or specify a different folder when downloading manually.

**Comment by alexta69** [comment]
Related to yt-dlp and not MeTube, closing
