### ISSUE TITLE
Download to NAS

### ISSUE THREAD

**Issue by Gamerou** [alexta69/metube#346]
When I set the destination Folder To my NAS the docker Container crashes instantly. On local Storage ist works perfectly. Can please anyone help?

**Comment by PikuZheng** [comment]
synology？ #195

**Comment by Gamerou** [comment]
no openmediavault. a cifs network share mounted to a folder

**Comment by PikuZheng** [comment]
mount it to host then map it to container? have you confirm it can be read and write on the host of docker?

**Comment by Gamerou** [comment]
Yes on host read/write works, but when I map it to the container it crashes. But I have found an alternative solution. So this one can be neglected. Thank You!
