### ISSUE TITLE
After update keep getting "Unable to adownload API"

### ISSUE THREAD

**Issue by Dvalin21** [alexta69/metube#347]
After latest update, I keep getting the following error. 

```
Error adding URL: ERROR: [youtube] DONaIQvsNuE: Unable to download API page: <urllib3.connection.HTTPSConnection object at 0x7f36b239cd60>: Failed to resolve 'www.youtube.com' ([Errno -3] Try again) (caused by TransportError("<urllib3.connection.HTTPSConnection object at 0x7f36b239cd60>: Failed to resolve 'www.youtube.com' ([Errno -3] Try again)"))
```
Using in docker on Synology NAS. Was able to download until this update.  Thanks

**Comment by PikuZheng** [comment]
![image](https://github.com/alexta69/metube/assets/12579522/96ddfeff-c18a-44a3-ba5d-61dfe6102bf7)
mine works. maybe your network‘s issue?

**Comment by Dvalin21** [comment]
> ![image](https://user-images.githubusercontent.com/12579522/284767874-96ddfeff-c18a-44a3-ba5d-61dfe6102bf7.png) mine works. maybe your network‘s issue?

Its possible, Ill do some further research and get back to you. Thanks!!

**Comment by Rsm-Ranger** [comment]
You got an update here? Same issue dns works fine

**Comment by Rsm-Ranger** [comment]
Checked all traffic - no problem
![grafik](https://github.com/alexta69/metube/assets/155016998/b8d206d8-bc69-4903-afb4-9b6eea3fa4d5)
still got 
![grafik](https://github.com/alexta69/metube/assets/155016998/865e840b-59cd-4c27-a366-1d0346004df3)
is takeing for ever and than
![grafik](https://github.com/alexta69/metube/assets/155016998/2ce3819b-1cbf-40eb-8441-7af377d15d31)

**Comment by Rsm-Ranger** [comment]
# closed to solution found. switched to other cotainer.

**Comment by zboigor** [comment]
I had the same issue on Synology NAS, the reason is that Docker containers couldn't access Internet by default when firewall is on. Here is the fix:
https://community.synology.com/enu/forum/11/post/142221

**Comment by ghostvar** [comment]
had same problem before, failed to resolve but normal ping and inside docker yt-dlp command test works fine.
turn out forgotten yt-dlp config to proxy.

![Image](https://github.com/user-attachments/assets/1946f2d7-a0c7-4a61-81a3-bd363dd0d389)

so in my case external problem, solution fixing proxy server.
