### ISSUE TITLE
[Feature Request] Ability to import cookie

### ISSUE THREAD

**Issue by AE720** [alexta69/metube#348]
This is a bit of a QOL feature, but for those on headless instances, it would be nice to import the cookie. Such as with a button that says "Import", allowing you to select it and upload it that way. Maybe even if a checkbox to clear it after download or container restart.

**Comment by alexta69** [comment]
All of the MeTube configuration is done via environment variables, we don't have a configuration store, and not planning one for the time being, closing at the moment
