### ISSUE TITLE
How to download instagram stuff? 

### ISSUE THREAD

**Issue by tediorelee** [alexta69/metube#352]
I found that yt-dlp supports download ig stuff but how am I let mtube work as well?

**Comment by PikuZheng** [comment]
are you meaning video and seal? you should login instagram and get cookie and pass it to metube

**Comment by tediorelee** [comment]
> are you meaning video and seal? you should login instagram and get cookie and pass it to metube

does it support images too ?

**Comment by alexta69** [comment]
If you have a specific problem (something that works in yt-dlp but doesn't work in MeTube), please reopen with full details (sample URL, errors you're getting and so on).
