### ISSUE TITLE
Downloading season from Tubi is limited to 20, can I fix this?

### ISSUE THREAD

**Issue by solidsnakex37** [alexta69/metube#354]
I love MeTube, it's the best downloader out there. 

Downloading stuff from Tubi is easy, you can take a whole season link and paste it into MeTube and it will parse each episode, the problem is it only queues up the first 20 episodes. Any idea why that is? 

I am not sure how MeTube works in the backend, how it's pulling that data, or if there is a limit somewhere in the config I need to change, I don't know. 

Example would be: 

https://tubitv.com/series/300005712/masterchef-australia/season-2

This only queues up 1-20, but there are like 80 episodes.

**Comment by PikuZheng** [comment]
Can you confirm that it works fine when using the yt-dlp command line? (I can't test since I'm not in the US)
Also if there is an episode with the same name it will be skipped

**Comment by alexta69** [comment]
Closing for now, please reopen if you find that it works with yt-dlp but doesn't work with MeTube
