### ISSUE TITLE
metube does not follow custom commands

### ISSUE THREAD

**Issue by PilaScat** [alexta69/metube#356]
I'm trying to use this setting, cookies and user-agent are okay but the rest no:
```
{
    "cookiefile": "/config/cookies.txt",
    "user-agent": "USER-AGENT",
    "sub-lang": "it-IT",
    "embed-subs": true,
    "convert-subs": "srt",
    "remux-video": "mkv"
}
```
with yt-dlp they work flawlessy with this:
`yt-dlp --cookies-from-browser chrome --user-agent "USER-AGENT" --sub-lang "it-IT" --embed-subs --convert-subs srt --remux-video mkv URL`

**Comment by PikuZheng** [comment]
according https://github.com/alexta69/metube?tab=readme-ov-file#configuration-via-environment-variables ,

**Comment by PikuZheng** [comment]
```
YTDL_OPTIONS={
  "cookiefile":"/config/cookies.txt",
  "http_headers":{"User-Agent": "USER-AGENT"},
  "writesubtitles":True,
  "subtitleslangs":["it-IT"],
  "final_ext":"mkv",
  "postprocessors":[
    {"key":"FFmpegVideoRemuxer","preferedformat":"mkv"},
    {"key":"FFmpegEmbedSubtitle","already_have_subtitle":False},
    {"key":"FFmpegSubtitlesConvertor","when":"before_dl","format":"srt"}
  ]
}
```
but why convert subtitle to srt before embed?

**Comment by PilaScat** [comment]
First I use a json file for configs, second I didnt know a order was needed, third these are not yt-dlp options, never saw them documented anywhere, now I'll try them

**Comment by PikuZheng** [comment]
nevermind about the order of parameter

> YTDL_OPTIONS: Additional options to pass to youtube-dl, in JSON format. See available options here. They roughly correspond to command-line options, though some do not have exact equivalents here, for example --recode-video has to be specified via postprocessors. Also note that dashes are replaced with underscores.

For embedded yt-dlp, all command line parameters are ytdl_options

**Comment by PikuZheng** [comment]
> --embed-subs --convert-subs srt 
I mean, why should we both embed subtitles into mkv video and convert to sub

**Comment by PikuZheng** [comment]
> --embed-subs --convert-subs srt 

I mean, why should we both embed subtitles into mkv video and convert to sub

**Comment by PilaScat** [comment]
These command seems perfect, but I have some more questions:

- How to auto set first audio to match the language code?
![image](https://github.com/alexta69/metube/assets/12989749/cc2d76df-6415-4a3f-b608-d97d396b25e3)
- How to set the subs default and forced?
- Why it puts files on NA folder? How to prevent and use root folder?

**Comment by PikuZheng** [comment]
> How to auto set first audio to match the language code?

It doesn't look like YouTube and I'm not familiar with it. Maybe there are relevant parameters on the command line? We can find its comparative ytdl_options

> How to set the subs default and forced?

ytdl_options works throughout the whole container life cycle, you only need to set it

>Why it puts files on NA folder? How to prevent and use root folder?

according https://github.com/alexta69/metube?tab=readme-ov-file#configuration-via-environment-variables ,You need to set DOWNLOAD_DIR

**Comment by alexta69** [comment]
Please reopen if there are still issues
