### ISSUE TITLE
Is there a way to restore previous downloads?

### ISSUE THREAD

**Issue by gerroon** [alexta69/metube#357]
Hi

My downloads were stuck, they were not moving so I restarted the container,but now I lost all my downloads :( I had like 10 downloads  and they are gone, and I do not actually know where I got all of them since I just browse the web and add them to the queue. I see that I have some files queue files under .metube folder and they are like couple mb but it is not picking them up. Is there a way or a place to find what those previous files were?

They are binary files so I cant really see if they contain anything useful.

**Comment by PikuZheng** [comment]
metube will load download queue（.metube）automatic 出container reload or recreate.
empty means nothing, sorry.

**Comment by alexta69** [comment]
Can't really tell what happened there.. sorry :( I hope it doesn't happen again
