### ISSUE TITLE
Connecting to server...

### ISSUE THREAD

**Issue by Strongis13** [alexta69/metube#359]
I frequently get a problem when accessing the metube web UI where the page gets stuck "connecting to server..." and the only way to fix this is keep refreshing the page until it eventually loads. This happens almost every time I try to use the app, and sometimes requires 3-4 page refreshes to start working. If I decide to refresh again it will break again...

![image](https://github.com/alexta69/metube/assets/48534096/00f1c6d0-dbc1-4e80-8667-f9e8980fe8e4)

**Comment by PikuZheng** [comment]
Please try chrome's incognito mode

**Comment by Strongis13** [comment]
> Please try chrome's incognito mode

Just tested, problem still occurs in incognito mode

**Comment by PikuZheng** [comment]
so. press F12 to open debug console, nav to Network and refresh page, see which acvitity cause wating
![image](https://github.com/alexta69/metube/assets/12579522/c16f66d8-6b0e-465f-8bde-ce41a515ba31)

**Comment by Strongis13** [comment]
> so. press F12 to open debug console, nav to Network and refresh page, see which acvitity cause wating 

Here is what I am seeing
![image](https://github.com/alexta69/metube/assets/48534096/ddd998db-2b60-4854-8bbc-1d99f0bb16aa)

**Comment by PikuZheng** [comment]
It looks like metube is having difficulty reading the queue file. Did you save the queue file (by default in /downloads/.metube) to another network location such as smb or nfs? Maybe you need to investigate network issues between cotainer and storage device.

**Comment by Strongis13** [comment]
I am new to docker so it is possible that its a misconfiguration on my part. I did not change the default location of anything, and the downloads folder is on the host machine of the container. Since it does work sometimes, I would assume this part of the configuration is correct?

**Comment by PikuZheng** [comment]
you’re correct.
so...any issue of disk IO？what file system is using by the host？

**Comment by Strongis13** [comment]
Running Ubuntu 22, I have run plenty of other apps on this machine so I don't think its any kind of hardware issue

**Comment by PikuZheng** [comment]
hope container's  log will helpful `docker logs metube` (change `metube` to your cotainer's name)

**Comment by Strongis13** [comment]
```
INFO:aiohttp.access:172.18.0.1 [20/Dec/2023:23:16:17 +0000] "GET / HTTP/1.0" 200 237 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.18.0.1 [20/Dec/2023:23:16:17 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Oo9W_zu HTTP/1.0" 200 289 "http://172.16.20.52/youtube/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.18.0.1 [20/Dec/2023:23:16:17 +0000] "GET /socket.io/?EIO=4&transport=websocket&sid=CkZBznckzOV9gaY-AALy HTTP/1.0" 200 715 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.18.0.1 [20/Dec/2023:23:16:17 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Oo9W_-9&sid=CkZBznckzOV9gaY-AALy HTTP/1.0" 200 877 "http://172.16.20.52/youtube/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.18.0.1 [20/Dec/2023:23:16:17 +0000] "POST /socket.io/?EIO=4&transport=polling&t=Oo9W_-8&sid=CkZBznckzOV9gaY-AALy HTTP/1.0" 200 272 "http://172.16.20.52/youtube/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
INFO:aiohttp.access:172.18.0.1 [20/Dec/2023:23:16:17 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Oo9W_-I&sid=CkZBznckzOV9gaY-AALy HTTP/1.0" 200 224 "http://172.16.20.52/youtube/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```
After some further testing it seems like my nginx config could be responsible here? When I attempt to connect directly to the port hosting metube I am unable to reproduce the "connecting to server" message, but going through the proxy its broken as described in my original post.

**Comment by PikuZheng** [comment]
If an nginx is in the middle of a metube, maybe it's not handling websockets correctly?

**Comment by Strongis13** [comment]
> If an nginx is in the middle of a metube, maybe it's not handling websockets correctly?

It's probably not fair to ask for help here in troubleshooting my nginx proxy, but do you know what I should be looking for?

**Comment by PikuZheng** [comment]
I'm not familiar with nginx. but from what I know, it needs additional configuration for websocket. [this](https://github.com/alexta69/metube/blob/f0247415bf5ec6bfa6f08ad7a75aa1efbcd3a7b3/README.md?plain=1#L155) and #270 maybe helpful.

**Comment by Strongis13** [comment]
> I'm not familiar with nginx. but from what I know, it needs additional configuration for websocket. [this](https://github.com/alexta69/metube/blob/f0247415bf5ec6bfa6f08ad7a75aa1efbcd3a7b3/README.md?plain=1#L155) and #270 maybe helpful.

Looks like my problem was the proxy headers, everything seems to work correctly now. Thank you for the help 👍

**Comment by ultraqwertz** [comment]
I had the same problem: everything worked just fine when accessing metube via IP:port, but using the "subdomain.domain.tld" via Nginx Proxy Manager resulted in the page being stuck at "Connecting to server...".

I fixed this by activating the "Websockets Support" switch in NPM under "Edit Proxy Host".
