### ISSUE TITLE
Network Proxy settings

### ISSUE THREAD

**Issue by ramondsq** [alexta69/metube#360]
It requires network proxy to access YouTube or other websites in some regions. 

I'd like to suggest to add a way to configure the proxy setting. 

In [yt-dlp](https://github.com/yt-dlp/yt-dlp#:~:text=used%20multiple%20times-,Network%20Options,-%3A) , it could be done by adding the parameter `--proxy URL` . 

Thank you for building this great tool.

**Comment by PikuZheng** [comment]
try `YTDL_OPTIONS={"proxy":"proxy url"}`

**Comment by ramondsq** [comment]
> try `YTDL_OPTIONS={"proxy":"proxy url"}`

I solved my problem. Thank you.
