### ISSUE TITLE
Prevent accidental downloading of youtube front page

### ISSUE THREAD

**Issue by TheSpyder** [alexta69/metube#362]
I don't know exactly how I did this, but I was adding a bunch of open Safari tabs through the iOS shortcut and suddenly my download list filled up with spam. I thought I might've been hacked until I checked the logs... 🙃 

```
metube  | INFO:ytdl:adding https://m.youtube.com/watch: quality='1440p' format='mp4' already=None folder=None custom_name_prefix=''
metube  | INFO:ytdl:adding https://www.youtube.com: quality='1440p' format='mp4' already={'https://m.youtube.com/watch'} folder=None custom_name_prefix=''
metube  | INFO:ytdl:adding https://www.youtube.com/feed/recommended: quality='1440p' format='mp4' already={'https://www.youtube.com', 'https://m.youtube.com/watch'} folder=None custom_name_prefix=''
metube  | INFO:ytdl:playlist detected with 302 entries
```

I feel like blocking `https://www.youtube.com` with no video specified would be a good idea 😂

**Comment by PikuZheng** [comment]
Maybe the previous line of these logs can help

**Comment by alexta69** [comment]
I guess this can happen with any number of sites and not only YouTube.. And on the other hand perhaps it's a valid use case for some people (who actually want the stuff from the front page). I don't think we should try guarding against every possible error like that, there's no end to them.
Thanks for bringing this up though.

**Comment by TheSpyder** [comment]
> Maybe the previous line of these logs can help

nah it's just `POST /add` which doesn't include the post contents


> I don't think we should try guarding against every possible error like that, there's no end to them.

I agree, but the youtube front page seems a bit weird. I guess if someone has cookies enabled they might want the front page - but I don't, so it's just random nonsense 🙂

**Comment by TheSpyder** [comment]
I appreciate your position here, but once again `https://m.youtube.com/watch` was sent by the iOS shortcut and I didn't notice until hours later. This will take a while to clean up. I'm just going to stop using the shortcut if metube won't deal with this.

**Comment by PikuZheng** [comment]
sorry to hear that but I think you should blame the person who provided the shortcut or plugin.

**Comment by TheSpyder** [comment]
It’s the one listed in the metube readme.
https://github.com/alexta69/metube#ios-shortcut

If that’s not supported, or if metube isn’t going to bend itself to accommodate limitations of the shortcut, it probably shouldn’t be mentioned.
