### ISSUE TITLE
Continue from last downloaded file from youtube playlist?

### ISSUE THREAD

**Issue by willu87** [alexta69/metube#375]
Is there a way to make MeTube resume from last downloaded file from playlist from Youtube? Right now it just start from first video from playlist when it's restarted. I run it on odroidxu4 which is my NAS in docker. Conversion is slow, something like 140 videos per 24hrs, so when I add 300 video long youtube playlist iut takes a little bit over 2 days to finish. I have set temp folder different than download folder.

**Comment by PikuZheng** [comment]
download_archive?

**Comment by willu87** [comment]
Found a solution, when using link to playlist it adds every video as a seperate entry.
