### ISSUE TITLE
Use host's VPN with custom port

### ISSUE THREAD

**Issue by alx-xlx** [alexta69/metube#379]
I am running adguard vpn on the host raspberry pi.
I used the following command to deploy the metube 

`
docker run -d --net=host --dns=1.1.1.1 --name metube -v /home/pi/data:/downloads -p 6538:6538 ghcr.io/alexta69/metube
`

I want to use the port `6538` but for smoe reason I get the following output, but the docker runs well on `http://localhost:8081` instead of being on port 6538 
```
WARNING: Published ports are discarded when using host network mode
```

**Comment by PikuZheng** [comment]
it is about the Docker operation mechanism, it is recommended to ask in the related section of the Docker.

but as far as I know, the Host network bridges the container to the physical network, at this time there is no need for port mapping

**Comment by alexta69** [comment]
Unrelated to MeTube, closing
