### ISSUE TITLE
YouTube API key option?

### ISSUE THREAD

**Issue by Sawtaytoes** [alexta69/metube#391]
Is there an option to put in my YouTube API key like YouTubeDL-Material had?

I'm asking because YouTube often has higher quality videos available for those with Premium subscriptions (which I do), and I'd like to be able to grab those copies if possible, but I have no way to associate my YouTube account with my local downloader service.

**Comment by PikuZheng** [comment]
Can you provide a command line example?

**Comment by Sawtaytoes** [comment]
It was part of the TrueCharts image for it. I don't know what the CLI looked like.

**Comment by PikuZheng** [comment]
I don't know the youtube api, maybe the Innertube API?
But if you only need login information, you can save the cookie as a file and pass it to metube https://github.com/alexta69/metube/blob/master/README.md#using-browser-cookies

**Comment by alexta69** [comment]
Cookie file is the way, closing
