### ISSUE TITLE
Error  404 proxy reverse subfolder nginx

### ISSUE THREAD

**Issue by caio1007** [alexta69/metube#393]
Hello, I am getting this error with reverse subfolder proxy configuration. Can anyone help me improve the code?

I hid my local ip *

```
location /metube/ {
        proxy_pass http://***.***.*.***:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
}
```

![image](https://github.com/alexta69/metube/assets/53404198/c46bf5c4-124f-4b62-b041-a34b0f459188)

**Comment by PikuZheng** [comment]
/metube （file）
/metube/ （dir）
define an index file maybe？

**Comment by caio1007** [comment]
Would you have an example to show me? I did the tests with 

/metube/ /metube 

same result...

**Comment by PikuZheng** [comment]
have you setted metube env `URL_PREFIX=` to some path?

**Comment by caio1007** [comment]
it worked by inserting URL_PREFIX /metube thank you very much
