### ISSUE TITLE
Recommendation: Authentication to access the web application - 2FA would be awesome

### ISSUE THREAD

**Issue by mimranfaruqi** [alexta69/metube#400]
Hi,

This is very good solution that you have deployed here. I use this on a personal domain, however, this also expose anyone on the internet to download anything onto my machine - could be virus or simply waste of bandwidth. It would be really nice to have authentication or OAuth or maybe SSO configurable. Perhaps, through environment variables as optional.

Thank you

**Comment by alexta69** [comment]
You can use Authelia or similar solutions to implement this, see here:
https://github.com/alexta69/metube?tab=readme-ov-file#running-behind-a-reverse-proxy

**Comment by vdrover** [comment]
Adding a vote for basic file-based authentication. What dozzle has done is a simple solution not requiring a database for example:

https://dozzle.dev/guide/authentication

Until then, Cloudflare Zerotrust is working to protect remote access for me.
