### ISSUE TITLE
Error with raiplay

### ISSUE THREAD

**Issue by neroita** [alexta69/metube#401]
Hi , I'm trying to download a video from raiplay ,but when I try a get a error:

ERROR: unable to download video data: HTTP Error 403: Forbidden

to test:
https://www.raiplay.it/video/2021/12/bluey-s1e1-lo-xilofono-magico-655b0c4d-7049-41f9-a6f3-abc0d5c7c809.html

**Comment by PikuZheng** [comment]
Can you try the download using the yt-dlp command line to see what goes wrong?

**Comment by neroita** [comment]
that's the output...

/app # yt-dlp https://www.raiplay.it/video/2021/12/bluey-s1e1-lo-xilofono-magico
-655b0c4d-7049-41f9-a6f3-abc0d5c7c809.html
[RaiPlay] Extracting URL: https://www.raiplay.it/video/2021/12/bluey-s1e1-lo-xilofono-magico-655b0c4d-7049-41f9-a6f3-abc0d5c7c809.html
[RaiPlay] 655b0c4d-7049-41f9-a6f3-abc0d5c7c809: Downloading video JSON
ERROR: [RaiPlay] 655b0c4d-7049-41f9-a6f3-abc0d5c7c809: This video is DRM protected

**Comment by PikuZheng** [comment]
It seems to have nothing to do with metube.
 It is recommended to go to yt-dlp to find the answer.
