### ISSUE TITLE
does it download audio only 

### ISSUE THREAD

**Issue by fanyangto** [alexta69/metube#404]
Just curious whether the app can download audio only files from youtube. 

Been through installing a lot of apps, most are missing some important components in the end, e.g. no icecast ios client, no snapcast ios client. I just want to know ahead before committing a lot of time. 

Thanks!

**Comment by PikuZheng** [comment]
yes if you select audio format
![image](https://github.com/alexta69/metube/assets/12579522/597a6612-b3ff-4dd2-8d80-4af1b8fc4e93)

**Comment by fanyangto** [comment]
Excellent! Thank you!
