### ISSUE TITLE
How do we stop downloads after they have been initiated?

### ISSUE THREAD

**Issue by reypm** [alexta69/metube#408]
I am using MeTube installed on TrueNAS Scale. For single videos, it works "fine" (although it does not respect output template options) but for playlists, it is completely different since it keeps adding more and more videos to the list. Let's say I added an entire list. After a few I decided to cancel the remaining items on the list, currently what I am doing is watching MeTube and then marking all the videos in the UI and removing them but somehow more and more and more videos keep added to the UI. I can get where those are coming from or how to stop them forever because I do not want them, can I get some help?

**Comment by PikuZheng** [comment]
it depends “auto start” ：yes or no
generally speaking, stop the metube container, delete the queue file and then start metube，this is the easy way

**Comment by reypm** [comment]
@PikuZheng I forgot to mention, `auto start` is set to `yes`. 

I am using the TrueNAS Scale and I was able to mount the PVC volume using Heavyscript, all I am seeing there is as follows:

```
# ls -la
total 973
drwxrwsr-x 2 root apps       5 Mar  8 19:27 .
drwxr-xr-x 3 root root       3 Mar  8 14:20 ..
-rw-r--r-- 1 apps apps 1048576 Mar 13 09:59 completed
-rw-r--r-- 1 apps apps  524288 Mar  8 19:27 pending
-rw-r--r-- 1 apps apps 3670016 Mar 13 09:59 queue
```

should I remove the `queue` file? The last time I tried something like that (I removed all files in there) MeTube did not start again and I had to reinstall everything

**Comment by PikuZheng** [comment]
delete queue file works for me. if it doesn't rebuild automatically when restart the container, there must be some permissions issue.
