### ISSUE TITLE
Residual files after download

### ISSUE THREAD

**Issue by mxia9416** [alexta69/metube#416]
Hi,
I got this wired issue when download was successful, it may left over some residual files in the download folder with .part extension shown below.
![QQ截图20240326223659](https://github.com/alexta69/metube/assets/18254371/6572d8dd-b458-42e0-8af5-1925542a8a29)
I tried to use yt-dlp alone, no redundant file were left after download.
In that case, I guess it's either Metube or Synology or both?
Any suggestions on resolving or troubleshooting it? Thanks!

**Comment by PikuZheng** [comment]
try to set TEMP_DIR=/tmp

**Comment by mxia9416** [comment]
That works, thank you! I'm closing the issue.
