### ISSUE TITLE
Error 13 when saving to samba mounted share

### ISSUE THREAD

**Issue by alledarr** [alexta69/metube#42]
Hello, 

I spun this up in docker and everything seemed to work fine when the downloads destination was on my local HDD of my ubuntu machine. When I tried setting the downloads folder to that of a samba mounted share, I get the following error in the completed section of the GUI. 

"ERROR: unable to open for writing: [Errno 13] Permission denied: '/downloads/*name of video*"

I know it's a permissions issue, but i don't know how to fix it. I have looked at the samba share and believe it is not the culprit. I have tried chmod 777 for the docker folder as well as the mount share. No luck

Thanks in advance. This looks like a really great tool to have in the tool kit!!

docker 20.10.8
ubuntu 20.04
samba share on local network

**Comment by alexta69** [comment]
It is indeed a permissions issue. Note the user you run the docker with (in the examples in the README it's uid 1001, but you may have changed it), and make sure this user can write to the share -- do that before you start metube. The share (or how it's mounted) is most definitely the culprit. Doing chmod on a samba share will not work, chmod is only for unix filesystems, so it's all about how you mount it. For example, you can specify the uid and gid options to the mount command for the filesystem to appear under the specified user. Once you verify that the user you run metube with can write to the share, metube will work fine as well.
