### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by airthomas** [alexta69/metube#425]
I have below experience for a youtube video, but others looks are ok...
The youtube link: https://www.youtube.com/watch?v=1aIaZ3SrV2U

via metube downloaded to mp4 can play with sound in Media Player Classic and Media Player with Sound, but without sound if playing in "Film & TV" and "Photos". Then I try download from https://yt5s.io/en91, then it have sound in mentioned player.

I have no idea the reason... is it some error due to the source youtube video?

Many thanks

**Comment by PikuZheng** [comment]
MP4 just packages audio and video together. Can you confirm the audio encoding format and does the player support it? Use potplayer or something like that to play the video and observe the properties - audio encoding

![image](https://github.com/alexta69/metube/assets/12579522/00a0b449-0463-4cc2-93af-d8d3efe52da5)
As shown in the picture, I use metube to download the audio file from youtube and the encode is "AAC".

**Comment by airthomas** [comment]
thanks your quick reply, since it can play in media player classic and VLC etc, means it must contain the audio. and according your reply, it should be Windows 11's "Film & TV" and "Photos" not support the audio encoding format. Many thanks.
