### ISSUE TITLE
ERROR: Unable to download video: [Errno 36] Filename too long

### ISSUE THREAD

**Issue by holotone** [alexta69/metube#427]
This happens frequently with Twitter video downloads. It appears metube uses the entire text of the Twitter post as the filename, and this is reaching some kind of limit somewhere. When this happens I get the following error message:

`ERROR: Unable to download video: [Errno 36] Filename too long`

Don't hesitate to ask if you need any more info.

**Comment by PikuZheng** [comment]
duplicate of #56 
This is usually a file system limitation. Most os limit file names to a maximum of 255 characters.

**Comment by holotone** [comment]
Agreed, wouldn't it be an easy fix to have metube truncate file names to less than 255 characters?

**Comment by trekGriffin** [comment]
add an environment variable to this container. This will fix it. 
   environment:
      - 'YTDL_OPTIONS={"trim_file_name":10}'

**Comment by holotone** [comment]
> add an environment variable to this container. This will fix it. environment: - 'YTDL_OPTIONS={"trim_file_name":10}'

That worked great, thanks a bunch!

**Comment by Gener8fotos** [comment]
> add an environment variable to this container. This will fix it. environment: - 'YTDL_OPTIONS={"trim_file_name":10}'

Worked for me as well! added to the docker compose xml and redeployed.

im running mine on a 2bay Asustor, drives are formatted EXT4 so i have a 255 char limitation (probably similar to NTFS)

**Comment by hpsaturn** [comment]
Hi,
Nice development. I have the same issue, and I already added the environment variable like this:

```yml
services:
  metube:
  ¦ image: ghcr.io/alexta69/metube
  ¦ container_name: metube
  ¦ restart: unless-stopped
  ¦ ports:
  ¦ ¦ - "8081:8081"
  ¦ volumes:
  ¦ ¦ - /storage/video/downloads:/downloads
  ¦ environment:
  ¦ ¦ - 'YTDL_OPTIONS={"trim_file_name":10}'
  ¦ ¦ - 'OUTPUT_TEMPLATE=%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S - %(title|UNKNOWN_TITLE)S - %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S.%(ext)s'
```

but nothing.

error output:

```python
metube  | INFO:ytdl:waiting for item to download
metube  | INFO:ytdl:adding https://x.com/wararyo/status/1858122254607102217: quality='best' format='mp4' already=None folder=None custom_name_prefix='' playlist_strict_mode=False playlist_item_limit=0
metube  | DEBUG:ytdl:Processing as a video
metube  | INFO:ytdl:downloading wararyo - RustでオレオレM5Burner作れちゃった！  Tauri (ElectronのRust版的な存在)と espflash (esptool. pyのRust版的な存在) を使ってESP32に書き込むデスクトップアプリが作れました Pythonや他の実行ファイルへの依存はナシ  これでファームウェアアップデート機能は実現できそう！
metube  | INFO:aiohttp.access:172.18.0.1 [26/Nov/2024:23:02:51 +0000] "POST /add HTTP/1.1" 200 265 "http://localhost:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0"
metube  | INFO:aiohttp.access:172.18.0.1 [26/Nov/2024:23:02:56 +0000] "GET /ngsw.json?ngsw-cache-bust=0.05446063746400498 HTTP/1.1" 200 244 "http://localhost:8081/custom-service-worker.js" "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0"
metube  | ERROR: unable to open for writing: [Errno 36] Filename too long: '/downloads/wararyo - . pyのRust版的な存在) を使ってESP32に書き込むデスクトップアプリが作れました Pythonや他の実行ファイルへの依存はナシ  これでファームウェアアップデート機能は実現できそう！ - 2024-11-17.mp4.part'
metube  | INFO:ytdl:waiting for item to download
```
It is failing with the same error. You able to test or replicate this issue with this video from twitter:
https://x.com/wararyo/status/1858122254607102217

**Comment by arbitarytwist** [comment]
It's not working. Do we remove the environment variable?

**Comment by hpsaturn** [comment]
I think that it is working only for some cases. I notice that with other videos, Metube trim the title or name file on right way, but with this specific video or link, it fails.

**Comment by arbitarytwist** [comment]
Doesn't seem to work for me. Was working with the environment setting before,  but not anymore.

**Comment by holotone** [comment]
This seemed to be working for me for quite awhile but it stopped recently, anyone know what's up?

**Comment by scubanarc** [comment]
Same here, was working, is not working now.

Current workaround:

`
OUTPUT_TEMPLATE=%(title).64s.%(ext)s
`

Seems to be working.
