### ISSUE TITLE
TikTok videos being downloaded with watermark

### ISSUE THREAD

**Issue by Spugit** [alexta69/metube#433]
Afaik yt-dlp downloads TikTok videos without a watermark by default nowadays, but Metube doesn't. Is there a way to resolve this?

**Comment by PikuZheng** [comment]
could you please check the versions both yt-dlp command and yt-dlp embeeded in metube?

**Comment by Spugit** [comment]
Using the `yt-dlp --version` command in the MeTube docker container returns: 2024.04.09

How to check the other version?

**Comment by PikuZheng** [comment]
I mean, what version of yt-dlp are you using to download without watermark? It may be newer than metube.
metube uses stable yt-dlp, which may lag behind in terms of newest functionality

**Comment by Spugit** [comment]
I see, i misunderstood. Looking further into this, it seems to be a returning problem with Tiktok changing the API that yt-dlp uses.

I will close this issue and sorry for wasting your time. Thank you!
