### ISSUE TITLE
Question: Will downloaded and deleted files be also deleted on the server?

### ISSUE THREAD

**Issue by stoneubi** [alexta69/metube#434]
Hi, 

I downloaded some files and afterwards pressed clear completed button. 

The files where still on n the folder on the server but not visible in the gui any more.

Is this normal? 

I expected that the files will also be deleted on the server where metube is installed via docker.

Thank you
Stoneubi

**Comment by PikuZheng** [comment]
maybe [DELETE_FILE_ON_TRASHCAN](https://github.com/alexta69/metube?tab=readme-ov-file#configuration-via-environment-variables) ?

**Comment by stoneubi** [comment]
Thank you - that was the missing part. Now it works,
