### ISSUE TITLE
Installation without docker?

### ISSUE THREAD

**Issue by jonylentzmc** [alexta69/metube#436]
Hello, thanks for maintaining the project
Is there a way to install this without using docker?

**Comment by PikuZheng** [comment]
Only necessary Python environment is required to run it. But nodejs is required to build web gui.
If you have a container environment, you can extract the necessary files from it after building.

**Comment by jonylentzmc** [comment]
Thank you for the reply,

**Comment by PikuZheng** [comment]
I think so.
get python codes and ui from container (named metube for example) and run
```
docker cp $(docker ps -aqf "name=metube"):/app/app /tmp/somepath
docker cp $(docker ps -aqf "name=metube"):/app/ui /tmp/somepath
cd /tmp/somepath && python app/main.py
```

**Comment by jonylentzmc** [comment]
I'll try that
Thx

**Comment by MortRainey** [comment]
really ? 

https://github.com/alexta69/metube?tab=readme-ov-file#building-and-running-locally
