### ISSUE TITLE
How to set --no-mtime ?

### ISSUE THREAD

**Issue by ZataH** [alexta69/metube#44]
If I try to set --no-mtime in the output variable, it just insert that in the filename. 

Example from docker-compose:
- OUTPUT_TEMPLATE=%(title)s.%(ext)s --no-mtime

**Comment by alexta69** [comment]
OUTPUT_TEMPLATE defines the format of the filename, so you can't put options there.
There's currently no way to add arbitrary command-line options. I don't have immediate plans to add this, so it's up to contributors who wish this to add the functionality and create a pull request..

**Comment by alexta69** [comment]
I've added support for youtube-dl options via the YTDL_OPTIONS environment variable (check the README). For the equivalent of `--no-mtime`, you need to set `updatetime` to false. So your YTDL_OPTIONS would be `{"updatetime":false}`.
