### ISSUE TITLE
nebula.tv support

### ISSUE THREAD

**Issue by shalak** [alexta69/metube#443]
Hello!

Is there a way to add nebula.tv support? I added all the `nebula.tv` and `.nebula.tv` cookies to the cookie file (being logged in in the browser of course), but it doesn't seem to work.

It reports the following error:

```
Error adding URL: ERROR: [Nebula] video_title_goes_here: This video is only available for registered users. Use --username and --password, --netrc-cmd, or --netrc (watchnebula) to provide account credentials
```

Any suggestions on how to make this work?

**Comment by PikuZheng** [comment]
my suggestion is add `'verbose': True` to env YTDL_OPTIONS to see if cookies works correct

**Comment by shalak** [comment]
Ok, I know what the issue above was about - I pasted the nebula cookies to the original file that contained only youtube exports. The original one was using `<tab>`, while pasting the new content converted them to regular spaces.

Proper `cat cookies-yt.txt cookies-nebula.txt > cookies-for-metube.txt` solved the cookie-loading issue - the log above no longer appears.

However, yt-dlp still doesn't seem to support nebula correctly :/

```
metube  | [debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) API
metube  | [debug] params: {'quiet': True, 'no_color': True, 'extract_flat': True, 'ignore_no_formats_error': True, 'cookiefile': '/cookies/cookies.txt', 'verbose': True, 'writesubtitles': True, 'subtitleslangs': ['en', 'pl'], 'postprocessors': [{'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}, {'key': 'FFmpegMetadata', 'add_chapters': True}, {'key': 'Exec', 'exec_cmd': 'touch', 'when': 'after_move'}], 'color': 'no_color', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.24 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
metube  | [debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-5.15.0-106-generic-x86_64-with (OpenSSL 3.1.4 24 Oct 2023)
metube  | [debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
metube  | [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
metube  | [debug] Proxy map: {}
metube  | [debug] Request Handlers: urllib, requests
metube  | [debug] Loaded 1901 extractors
metube  | [Nebula] Extracting URL: https://nebula.tv/videos/practical-engineering-the-most-confusing-part-of-the-power-grid
metube  | [Nebula] practical-engineering-the-most-confusing-part-of-the-power-grid: Fetching video meta data
metube  | [Nebula] Reauthenticating to Nebula and retrying, because last bearer call resulted in error 403
metube  | ERROR: [Nebula] practical-engineering-the-most-confusing-part-of-the-power-grid: This video is only available for registered users. Use --username and --password, --netrc-cmd, or --netrc (watchnebula) to provide account credentials
```

**Comment by PikuZheng** [comment]
>metube  | WARNING: skipping cookie file entry due to invalid length 1: 'nebula.tv   FALSE   /   FALSE   1748023338  muxData mux_viewer_id=XXXXXXXXX&msn=0.00000&sid=XXXXXXXXX&sst=000000&sex=0000000\n'

try to remove this line

and any cookies from api.watchnebula.com ?

**Comment by shalak** [comment]
> > metube  | WARNING: skipping cookie file entry due to invalid length 1: 'nebula.tv   FALSE   /   FALSE   1748023338  muxData mux_viewer_id=XXXXXXXXX&msn=0.00000&sid=XXXXXXXXX&sst=000000&sex=0000000\n'
> 
> try to remove this line

As mentioned above - this log was because of tabs vs whitespaces in the cookies file.

> and any cookies from api.watchnebula.com ?

No, I exported cookies from the entire browser went `grep -i nebula cookies.txt` and only `nebula.tv` & `.nebula.tv` shows up.

**Comment by PikuZheng** [comment]
>nebula.tv FALSE / FALSE 1748023338 muxData mux_viewer_id=XXXXXXXXX&msn=0.00000&sid=XXXXXXXXX&sst=000000&sex=0000000

try to remove this line

**Comment by shalak** [comment]
Unfortunately, removing the `muxData` cookie did not help, same issue.

**Comment by PikuZheng** [comment]
regret for that :(

but, yt-dlp's extractor (https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/nebula.py) does not seem to handle nebula cookies, but supports username/password or netrc authentication. so any chance to forget cookies and put username/password in env YTDL_OPTIONS like {'username':'abc@def.gh', 'password':'p@ssw0rd'}

**Comment by shalak** [comment]
Heh, looks like it's [impossible to login via cookies to nabula anyway, and local-storage is not supported by yt-dlp](https://github.com/yt-dlp/yt-dlp/pull/5979)
