### ISSUE TITLE
restrict public access over IP

### ISSUE THREAD

**Issue by 279308** [alexta69/metube#445]
Please excuse me if the question has already been asked, but I couldn't find anything about it..  

I was able to set authorization with nginx proxy manager over FQDN. But how can I restrict public access over IP?

Thank you in advance!

**Comment by PikuZheng** [comment]
I don't fully understand but ip can be fqdn

**Comment by 279308** [comment]
I have set up Docker on a VPS, which means:

access metube over the (public) IP:port
AND 
with Nginx Proxy Manager, use the FQDN and Access Lists <-- that should the only way

i want to prevent the access over the (public) IP:port.

**Comment by PikuZheng** [comment]
ip is a kind of fqdn, it can be understood this way. try config generator like 
https://www.digitalocean.com/community/tools/nginx?
You will see ip appear in `server_name` if you fill it in site name

**Comment by 279308** [comment]
Alright. Since this is more of a question and understanding issue on my part, we can close this here. Again, thanks a lot for your fast reply
