### ISSUE TITLE
How to embed metadata and thumbnail?

### ISSUE THREAD

**Issue by foolab** [alexta69/metube#450]
Hi,

Thank you for the great app :)

If I download a video manually using yt-dlp then I can pass --add-metadata --embed-thumbnai to embed the metadata and thumbnail into the resulting file.

How do I do that with metube? I checked ytdl options here https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L183 but I am unable to figure out how to do it.

Any tips would be greatly appreciated.

**Comment by PikuZheng** [comment]
yes.
set YTDL_OPTIONS
```
{
 "writethumbnail":true,
 "postprocessors":[

  {"key":"EmbedThumbnail"}
 ]
}
```

**Comment by foolab** [comment]
That is quite embarrassing. I was not aware it could be added like that. It works like a charm.

Thank you :)
