### ISSUE TITLE
"Best" quality setting not downloading best quality

### ISSUE THREAD

**Issue by RobertD502** [alexta69/metube#452]
**Random example video used for testing:** https://www.youtube.com/watch?v=YiRMs5ZhcH4

### Formats available for video

![image](https://github.com/alexta69/metube/assets/52541649/9877c535-5d62-47bc-a376-ed3d1d510c60)

With the quality set to `Best` and the format set to `Any`, metube ends up downloading the 1080p video instead of the 2160p video. `Note:` NO `YTDL_OPTIONS` were set so it wasn't a customization causing the weird behavior.

After noticing that this was happening every time, I set `verbose` to true. Looking at the logs, I can see that yt-dlp is grabbing the 1080p version.

#### yt-dlp settings being used

```log
params: {
    'quiet': True,
    'no_color': True, 
    'paths': {
        'home': '/downloads',
        'temp': '/downloads'
    }, 
    'outtmpl': {
        'default': '%(title)s.%(ext)s', 
        'chapter': '%(title)s - %(section_number)s %(section_title)s.%(ext)s'
    }, 
    'format':"bestvideo[vcodec~='^((he|a)vc|h26[45])']+bestaudio[acodec=aac]/bestvideo[vcodec~='^((he|a)vc|h26[45])']+bestaudi. o/bestvideo+bestaudio/best",
    'socket_timeout': 30, 
    'ignore_no_formats_error': True, 
    'progress_hooks': [<function Download._download.<locals>.put_status at 0x70c10f75e700>], 
    'postprocessor_hooks': [<function Download._download.<locals>.put_status_postprocessor at 0x70c10e9bee80>], 
    'verbose': True, 
    'postprocessors': [], 
    'color': 'no_color', 
    'compat_opts': set(), 
    'http_headers': {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36', 
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate' 
    }
}
```

When compared to the formats available (shown at the beginning of this issue) and log from yt-dlp (shown below), you can see that the 1080p video is getting downloaded - `video 137 + audio 251`:

```
YiRMs5ZhcH4: Downloading 1 format(s): 137+251
```

#### Workaround

If I manually set the `format` to `bestvideo+bestaudio` in `YTDL_OPTIONS`, it then ends up downloading the 2160p version. 
**However**, this is not an ideal workaround since it renders the `quality` and `format` selectors in the metube UI non-functional - i.e., with the format manually set to bestvideo+bestaudio, selecting 720p in metube will result in the 2160p version getting downloaded.

So, it seems that the format option being sent to yt-dlp, when `Best` quality is selected in the metube UI, needs to be reworked as it isn't actually grabbing the best video and audio.

**Comment by PikuZheng** [comment]
with best + any, metube will download 313+251 (3840x1920)
with best + mp4, metube will download 625+140 (3840x1920)

![image](https://github.com/alexta69/metube/assets/12579522/d90de519-587d-4c00-b3f5-234f6dc60b7a)

so it looks working correctly on my pc.

**Comment by RobertD502** [comment]
Mine is running as a docker container. Perhaps that is the difference?

**Comment by craigcabrey** [comment]
I'm also seeing this, especially with no option for webm (for which av1 is required I believe)

**Comment by PikuZheng** [comment]
```
'format':"bestvideo[vcodec~='^((he|a)vc|h26[45])']+bestaudio[acodec=aac]/bestvideo[vcodec~='^((he|a)vc|h26[45])']+bestaudi. o/bestvideo+bestaudio/best",
```
I belive this is a limit for download format.... but I'm not familiar with this. sorry :(

**Comment by PikuZheng** [comment]
```
vcodec~='^((he|a)vc|h26[45])'
```
looks matched avc which is 137 but 401 (av01

**Comment by RobertD502** [comment]
> I'm also seeing this, especially with no option for webm (for which av1 is required I believe)

No issues downloading webm if I MANUALLY set the format to `bestvideo+bestaudio`. Using my example link, if you set the format to this in the `YTDL_OPTIONS`, it will grab the 2160p webm version. However, manually setting the format prevents you from being able to set the file format or quality from the metube UI. My findings are pointing to the format arg needing to be relooked at for when a user selects the best quality option in metube (and doesn't have a format already manually set via the `YTDL_OPTIONS` env variable).

**Comment by PikuZheng** [comment]
> No issues downloading webm if I MANUALLY set the format to `bestvideo+bestaudio`. Using my example link, if you set the format to this in the `YTDL_OPTIONS`, it will grab the 2160p webm version. However, manually setting the format prevents you from being able to set the file format or quality from the metube UI. My findings are pointing to the format arg needing to be relooked at for when a user selects the best quality option in metube (and doesn't have a format already manually set via the `YTDL_OPTIONS` env variable).

I don't think so, although ytdl_options has higher priority. But your options above limit the format. If there is no formats restriction, it should be as I tested

**Comment by RobertD502** [comment]
As I mentioned before - that long format that you see, I am not setting myself. That is the verbose output from yt-dlp with what metube is setting the format to when best quality is selected from the metube UI.

**Comment by PikuZheng** [comment]
> As I mentioned before - that long format that you see, I am not setting myself. That is the verbose output from yt-dlp with what metube is setting the yt-dlp format to when I select best quality and Any is selected from the metube UI.
> 
> Related code [here](https://github.com/alexta69/metube/blob/6b4db7c7577d11665337c0025edc6c1923f4ffe8/app/dl_formats.py#L47)

you're right.... I'm using old version which don't has these code https://github.com/alexta69/metube/blob/2142e759aa70d591481d066cc96d4c2c3bbdd098/app/dl_formats.py

so, maybe there is an issue with your commit @jgoguen

**Comment by jgoguen** [comment]
Hmm, maybe I got "lucky" and everything I tested on the iOS-compatible MP4 was equal quality to the best.

Perhaps we could add iOS as another quality option? Default to "Best" which would be the old behaviour of best possible formats in a MP4 container, and a new "Best (iOS)" option that will enforce iOS compatibility. Or I could add another option to the `Config` class to specify strict iOS compatibility. 

@alexta69 any opinion on which you'd prefer? Adding a config option would be cleaner, but will mean a bigger PR; having another quality option would be faster but might be odd.

**Comment by RobertD502** [comment]
As an outsider, so feel free to disregard my thinking, I'd think that having another config option would make sense. However, it would be more flexible if said option is something that can be enabled or disabled from the UI instead of it only being possible to set by an env variable. There may be instances where iOS compatibility is not a worry, but without being able to disable it via the UI, you'd have to recreate the container with the option disabled, if previously enabled via an env variable.

Again, feel free to ignore my thinking - I mainly spun up the container for others to use as I personally go to yt-dlp directly from my terminal.

**Comment by PikuZheng** [comment]
> ```
> vcodec~='^((he|a)vc|h26[45])'
> ```
> looks matched avc which is 137 but 401 (av01

maybe change avc to av? is av01 working for ios? @jgoguen

**Comment by RobertD502** [comment]
> > ```
> > vcodec~='^((he|a)vc|h26[45])'
> > ```
> > looks matched avc which is 137 but 401 (av01
> 
> maybe change avc to av? is av01 working for ios? @jgoguen 

If I remember correctly, AV1 (av01) hardware decoding was made available starting with the iPhone 15. However, although older iOS devices can support it via software decoding, it has to be implemented in the app where the video is being played - VLC, YouTube, etc.

Since it isn't "natively" (within Safari or playing an AV1 video directly from the device without the use of a 3rd party app) supported on a lot of devices, it makes sense to not include it in the Regex.

**Comment by alexta69** [comment]
@jgoguen I think adding another quality option makes more sense, I agree that it's odd, but that's the price of making everyone happy :)
