### ISSUE TITLE
Support for embedding videos with start and end time parameters

### ISSUE THREAD

**Issue by sbhal** [alexta69/metube#468]
I am looking to embed downloaded videos from Metube and want to specify the start time and end time of the video. Currently, the download link works as expected (e.g., `https://metube.domain.com/download/My Video Title.webm`), but I need the ability to embed the video with specific start and end times.

The desired format for the embed link would be:

`https://metube.domain.com/embed/My Video Title.webm?start=10&end=20`

This would embed the video and start playing from the 10-second mark and stop at the 20-second mark.

**Comment by alexta69** [comment]
As hosting videos is not the main focus of MeTube, I don't think we're going to add features in that realm. If you need advanced features like that, I suggest you use another app to expose the MeTube download folder to the web.
