### ISSUE TITLE
Skip Duplicate Downloads

### ISSUE THREAD

**Issue by TerroFlys** [alexta69/metube#507]
I am downloading a playlist however sometimes a song can be in there 2x.

Is there an option to disable duplicates from downloading? 

When I look into the downloaded files folder I do only see 1 of them however I do not like that it redownloaded a whole video. Possibility to disable/skip these?

**Comment by PikuZheng** [comment]
r u means download-archive #414

**Comment by TerroFlys** [comment]
No, this has not to do with extentions. 
When I download a file, It gets saved. When I put in the URL again, despite it already existing in the downloads folder, it gets downloaded again. But there will always only be 1. So I think the new one overwrites the old one. Would it be possible to let MeTube check if a file already exists before downloading?

**Comment by PikuZheng** [comment]
sounds like download_archive is exactly what you need. why not satisfy?

**Comment by TerroFlys** [comment]
Ah it seems I have misunderstood. How do I use MeTube with download_archive?

**Comment by TerroFlys** [comment]
I am not sure this works for me but it seems to be the solution to this problem. I used YTDL_OPTIONS={download_archive:/archive/archive.txt}. Thanks @PikuZheng
