### ISSUE TITLE
error adding URLs due to out of date yt-dlp

### ISSUE THREAD

**Issue by Durtndur** [alexta69/metube#508]
as of today I get this error anytime I try to add a link

Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

ive tried recreating/installing metube image and still won't work

**Comment by 2813910154** [comment]
bro,and now ？
