### ISSUE TITLE
Raycast Extension

### ISSUE THREAD

**Issue by dotvhs** [alexta69/metube#512]
My Raycast Extension for communication with MeTube was recently approved on Raycast Store: https://www.raycast.com/dot/metube

I plan to expand it with additional features but for now it supports adding links from clipboard as well as typed.

I just wanted to notify about my "contribution", hopefully this is a correct way. Thank you for MeTube, it works great :)

**Comment by alexta69** [comment]
Thanks @dotvhs !

**Comment by muava12** [comment]
is this extension still works? i can't get it work

**Comment by dotvhs** [comment]
> is this extension still works? i can't get it work

I use it every day so yeah, it works. Did you set up the correct location?
