### ISSUE TITLE
Error opening input files: Invalid argument

### ISSUE THREAD

**Issue by salty-catpuccino** [alexta69/metube#523]
Hello, I am running MeTube on TrueNas Scale.
So far its been working quite well, but there is 1 video it wont download and the error seems like something that might be of interest.

See the logs below:
```
2024-10-04 14:52:50.951680-07:00INFO:ytdl:downloading 3y3s
2024-10-04 14:52:55.917548-07:00INFO:aiohttp.access:172.16.0.1 [04/Oct/2024:21:52:55 +0000] "GET / HTTP/1.1" 200 295 "-" "kube-probe/1.26"
2024-10-04 14:52:55.917679-07:00INFO:aiohttp.access:172.16.0.1 [04/Oct/2024:21:52:55 +0000] "GET / HTTP/1.1" 200 295 "-" "kube-probe/1.26"
2024-10-04 14:52:59.108098-07:00ERROR: Postprocessing: Error opening input files: Invalid argument
```

The error in the UI reads:
![image](https://github.com/user-attachments/assets/c4b93e08-fa9a-45a6-a53d-bbf8f3bd13c8)

**Comment by PikuZheng** [comment]
it looks like you set some postprocesser in ytdl_options but wrong timing of execution ("when"?

**Comment by salty-catpuccino** [comment]
Im actually running it stock with no special options configured for MeTube on TrueNas Scale. 

Here are my current settings, I can post the latter half if you would like.
![image](https://github.com/user-attachments/assets/df2037ec-ad12-4212-a810-a2a8a999a390)

Its ultimately probably not a big deal, I was more thinking its a little odd this 1 video is having issues. Its a very old youtube video.

**Comment by PikuZheng** [comment]
I searched for it by name https://www.youtube.com/watch?v=Vpvxzt0PsxU
Yes I believe there are some issues with this video. Unlike modern video, it is only available in low-resolution formats and the audio/video are not separated.

![image](https://github.com/user-attachments/assets/0387bdbd-2bbe-4f6f-b2a3-b70b8b8202cd)

In fact, it still can't be played on the web. With ffmpeg 6.0, it can process normally (no error), but the file cannot be played.

![image](https://github.com/user-attachments/assets/dc5b2d9f-a5d7-4bb9-92a6-0a5cec7ebdbe)

**Comment by salty-catpuccino** [comment]
How very interesting! Thanks for taking a look!
