### ISSUE TITLE
Error opening input files: Invalid data found when processing input

### ISSUE THREAD

**Issue by evgeniy-harchenko** [alexta69/metube#527]
Hello. I am using MeTube in Docker, Ubuntu 24.04. All work good. But with some videos I have next error:
```
INFO:ytdl:adding https://www.youtube.com/watch?v=vJz8QzO1VzQ: quality='480' format='mp4' already=None folder=None custom_name_prefix='' playlist_strict_mode=False playlist_item_limit=0
DEBUG:ytdl:Processing as a video
INFO:ytdl:downloading Shades of Black 12K HDR 60fps / Dolby Vision
======== Running on http://0.0.0.0:8081 ========
(Press CTRL+C to quit)
INFO:aiohttp.access:192.168.0.102 [11/Oct/2024:11:38:16 +0000] "POST /add HTTP/1.1" 200 275 "http://serverdesktop.local:8081/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
[download]  95.5% of ~ 299.91MiB at    3.14MiB/s ETA 00:05 (frag 25ERROR: Postprocessing: Error opening input files: Invalid data found when processing input
```
![image](https://github.com/user-attachments/assets/d0ff7577-b587-4d71-b95e-6f36ee9d93fc)

Example of buggy video: https://www.youtube.com/watch?v=vJz8QzO1VzQ
In download directory I get 2 files: `*name*.mp4` (without sound) and `*name*.m4a` With `Quality: Best` and `Format: Any` it downloads normally.

**Comment by PikuZheng** [comment]
>INFO:ytdl:adding https://www.youtube.com/watch?v=vJz8QzO1VzQ: quality='480' format='mp4' already=None folder=None custom_name_prefix='' playlist_strict_mode=False playlist_item_limit=0

looks you selected 480 but best

**Comment by evgeniy-harchenko** [comment]
I checked `yt-dlp` with next parameters and it works without any problems:
`yt-dlp -f 'bestvideo[height=480]+bestaudio[ext=m4a]' --merge-output-format mp4 https://www.youtube.com/watch\?v\=vJz8QzO1VzQ`

**Comment by evgeniy-harchenko** [comment]
Thanks, a lot, the problem is really in ffmpeg version, but I had to install version 7.0.2. Version 6.1.1 didn't work for me.
