### ISSUE TITLE
Doesn't work with videos I've copied from my Watch Later playlist.

### ISSUE THREAD

**Issue by gamerkonks** [alexta69/metube#53]
I get the following error.
Error adding URL: 500 Internal Server Error
Server got itself in trouble.

Example URL
https://www.youtube.com/watch?v=o1R0dCSIhvc&list=WL&index=2

Removing the playlist and index parameters from the URL resolve the issue.
I think this is because the URL points to a private playlist.

Potentially the solution is to attempt to download the playlist, and if it fails, i.e. if it's a private playlist, only attempt to download the video?
Or check if list == "WL" then only download the video, as the watch later playlist visibility can only be set to private.

**Comment by alexta69** [comment]
Hi,
Thanks for reporting this! I pushed a fix. In about half an hour it will finish building, and you'll be able to pull the fixed version from Docker Hub.
Alex
