### ISSUE TITLE
[Feature Request?] Automate cleanup of downloads

### ISSUE THREAD

**Issue by DeuSCaNoN** [alexta69/metube#530]
I'm not sure if there's an api already, but I'm wondering if it's possible to have a script that every week calls the "Clear completed" command on this (running in a docker container)

The reason is my non-tech-savvy mom likes to download youtube videos, but she's pretty bad at cleaning up afterward, so since I'm not using this much, I can foresee the drive getting clogged up by tons of downloaded videos.

As such a bash script that gets run on a cron job would be nice to auto clean up these downloads every month or so.

**Comment by arabcoders** [comment]
> I'm not sure if there's an api already, but I'm wondering if it's possible to have a script that every week calls the "Clear completed" command on this (running in a docker container)
> 
> The reason is my non-tech-savvy mom likes to download youtube videos, but she's pretty bad at cleaning up afterward, so since I'm not using this much, I can foresee the drive getting clogged up by tons of downloaded videos.
> 
> As such a bash script that gets run on a cron job would be nice to auto clean up these downloads every month or so.

You can create a weekly cronjob with the following content:

```bash
find /home/user/Downloads/ -type f -mtime +30 -exec rm {} \;
```

notice `+30` this will delete files older than 30 days. you can tweak it as you see fit.

or you can also install `tmpreaper` and use something like:

```bash
tmpreaper -m 30d /home/user/Downloads/
```

**Comment by DeuSCaNoN** [comment]
> ```shell
> find /home/user/Downloads/ -type f -mtime +30 -exec rm {} \;
> ```
> 
> notice `+30` this will delete files older than 30 days. you can tweak it as you see fit.
> 
> or you can also install `tmpreaper` and use something like:
> 
> ```shell
> tmpreaper -m 30d /home/user/Downloads/
> ```

I figured out that already, but doesn't this only delete the files from the filesystem? Do the items still appear in meTube's webpage under the "Completed" section? If so it's not the most ideal, that's why calling the "Clear completed" would both delete it from meTube as well as the filesystem with the DELETE_FILE_ON_TRASHCAN flag

**Comment by arabcoders** [comment]
Indeed, it will not remove them from the history... however, you can also automate the process the webui is just wrapper around the API. 

you can create a script that do the following

1. get files that are older than XX days.
2. send request to metube api to remove said files. it will remove them both from the UI & filesystem.

**Comment by DeuSCaNoN** [comment]
> 1. get files that are older than XX days.
> 2. send request to metube api to remove said files. it will remove them both from the UI & filesystem.

Ok thanks, I was reading the python code in main.py and it looks like the routes are defined there. I the original ask in this ticket would be to expose not just a "delete" route but a "clear" route. But i can understand if that's not on the table.

Assuming there won't be an exposing of a new api route, what shell commands are recommended? I don't do much web api coding in my day job and i only know curl/wget commands in linux for web interfaces.
