### ISSUE TITLE
ARM Docker Image on Raspberry Pi 4

### ISSUE THREAD

**Issue by BorussiaPlayer17** [alexta69/metube#54]
Hi,

I was trying your docker image on my Raspberry pi 4. The container doesn’t start and fails with this error

> metube    | Fatal Python error: pyinit_main: can't initialize time
> metube    | Python runtime state: core initialized
> metube    | PermissionError: [Errno 1] Operation not permitted
> metube    | 
> metube    | Current thread 0xb6f59390 (most recent call first):
> metube    | <no Python frame>

**Comment by alexta69** [comment]
Hi,
It seems a common problem with many images, and the fix needs to be on the docker host.
This is the fix you need, apparently: https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal-and-alpine-3-13
See this for reference for example: https://github.com/linuxserver/docker-calibre-web/issues/119
I'm closing this issue, if you find out it's a different problem, please reopen.
Thanks

**Comment by BorussiaPlayer17** [comment]
Thank you for your help! That works!
