### ISSUE TITLE
Filename Too Long Error When Downloading Videos

### ISSUE THREAD

**Issue by shuanat** [alexta69/metube#543]
When attempting to download a video from TikTok, the application encounters an error due to the filename being too long. The error message is as follows:

ERROR: unable to open for writing: [Errno 36] Filename too long: '/downloads/#tags... .mp4.part'
This issue arises because the filename is generated using the full title, which can exceed the maximum allowed length for filenames on the operating system.

Solution:
The issue was resolved by modifying the filename template in [app/main.py#L31](https://github.com/alexta69/metube/blob/4a87e9fa68569e467224c8ef9cc49df8dfede831/app/main.py#L31). The OUTPUT_TEMPLATE was updated to limit the title length to 50 characters, ensuring that the generated filename does not exceed the system's maximum length:

'OUTPUT_TEMPLATE': '%(title).50s.%(ext)s'
This change prevents the error by ensuring that filenames remain within acceptable limits.

**Comment by PikuZheng** [comment]
duplicate of https://github.com/alexta69/metube/issues/56 , #271 , #427

**Comment by nanohits** [comment]
That fixed the long file name but now I get this error: ERROR: [facebook] 1086735726758578: No video formats found!
