### ISSUE TITLE
Delete for real when using the UI

### ISSUE THREAD

**Issue by nicanordlc** [alexta69/metube#557]
When I click on the `trash can` icon on the completed items, I expect the item to be deleted from the filesystem. This way we can clear the disk if we remove items from there and not have to access the terminal to delete any item on the `/downloads` path.

<img width="1307" alt="image" src="https://github.com/user-attachments/assets/dc352ee6-aa6e-42e1-8e70-596cadac4313" />

Right now it only deletes the item from the UI and not downloads folder. Can a new button be created to delete to delete both on the UI and the filesystem or modify existing delete button to do this ?

**Comment by PikuZheng** [comment]
set env `DELETE_FILE_ON_TRASHCAN` to true if you want

**Comment by nicanordlc** [comment]
Oh ! This is perfect. Thank you very much !

**Comment by commodore-84** [comment]
@PikuZheng Sorry to rehash this - but this reverts when the metube app is updated
I added `DELETE_FILE_ON_TRASHCAN=true` to the .env file
Did I miss something?

**Comment by PikuZheng** [comment]
> I even added `DELETE_FILE_ON_TRASHCAN=true` to the .env file

I don't know except you are using proxmox. it looks related to the operating system and docker environment
