### ISSUE TITLE
Cookies not being used

### ISSUE THREAD

**Issue by jdeath** [alexta69/metube#58]
Running from the UI on a site that requires cookies gives:
`This video is only available for registered users. You may want to use --cookies.`

Confirmed the environment is set, by logging into container and doing an env:
`YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}`

Running it manually from the container works correctly and gets the video, putting in the mountpoint set for cookiefile
`yt-dlp --cookies /cookies/cookies.txt URL`

am I doing anything wrong? Container was rebuilt today

**Comment by ykram** [comment]
not sure if this is the problem but in `__extract_info`  within the `DownloadQueue` class, could you try changing the call to `yt_dlp.YouTubeDL()` to look like this:

`        return yt_dlp.YoutubeDL(params={
            'quiet': True,
            'no_color': True,
            'extract_flat': True,
            **self.config.YTDL_OPTIONS,
        }).extract_info(url, download=False)
`

**Comment by alexta69** [comment]
@jdeath doesn't look like you're doing anything wrong... not sure what the problem might be, frankly

**Comment by jdeath** [comment]
@ykram That worked. Thanks. I made the change with vi inside he container on /app/app/ytdl.py , restarted the container, and it worked.

**Comment by alexta69** [comment]
Brilliant! Thanks @ykram ! I pushed the fix to the master now.
