### ISSUE TITLE
Add download link and file removal

### ISSUE THREAD

**Issue by achaiah** [alexta69/metube#6]
Hi,

Thanks for this great web UI. Would it be possible to make the items in the `Completed` list be linked to the actual files. The use case is that I'm downloading files to my NAS but may want to open them up from the web UI on another machine.

Also, it would be nice to be able to delete the underlying downloaded files from the UI rather than just removing them from the list.

Thanks!

**Comment by alexta69** [comment]
Hey,
Serving the file by clicking on it is an interesting idea, and shouldn't be hard to implement. (Maybe a download button next to the filename, or something like that.)
Deleting the files is not what I want -- I want to clear the list, but keep the files, since I wanted to download them...
Maybe there can be two buttons, one for clearing, one for deleting the file.

**Comment by achaiah** [comment]
Yeah, that's what I meant by deleting.. that there would be two options. Definitely want to have the option of simply clearing the list but deleting the file is also useful when you've downloaded the wrong format or found a better version etc and just want to remove the previous file.

I figured serving wouldn't be hard and I think it would be super useful.  I would just make the file name in the list into a link if that's easy enough.

Thanks!

**Comment by pointmax** [comment]
I just found this tool and would absolutely love to see a file hosting & deleting functionality 👍🏻

**Comment by codepoet80** [comment]
Perhaps y'all would want to check out my service wrapper -- a collection of PHP files and a script for downloading and clean-up:
[metube-php-servicewrapper](https://github.com/codepoet80/metube-php-servicewrapper)

**Comment by achaiah** [comment]
@codepoet80 Cool that looks interesting. Can you please extend your readme a bit with a screenshot and further description of directory mapping? I’m confused on what a “virtual directory” and what is “www-data”?

**Comment by codepoet80** [comment]
@achaiah yup, yup. working on it.
That said, Apache is a pre-requisite for a PHP service, so you'd have to be comfortable with that for things like [virtual directories](https://stackoverflow.com/questions/13636594/apache-alias-and-subdirectories), and [www-data](https://askubuntu.com/questions/873839/what-is-the-www-data-user) permissions.
You could run it on a Raspberry Pi or Mac, on a Windows box with some additional hops. I won't be able to cover setting up a web server.

**Comment by achaiah** [comment]
Yup, actually that's not why I'm asking. The point is to dockerize your wrapper along with metube so that you can run it on any platform and not care about permissions or virtual directories etc.  Then anyone can run it and you can have it locally or on a server with no problem.

**Comment by codepoet80** [comment]
I definitely won't be doing that. Not a Docker fan. But feel free to fork!

**Comment by achaiah** [comment]
Oh yeah thanks. I will actually be able to clone your project right into the container build. IMHO you should give docker another look. It's seriously awesome.

**Comment by alexta69** [comment]
Guys, I'm closing the issue for now. I'll gladly accept a pull request if anyone of you is inclined to add these features, since I don't really have time to work on it myself.
Thanks!
Alex
