### ISSUE TITLE
[Errno 13] Permission Denied immediately

### ISSUE THREAD

**Issue by codepoet80** [alexta69/metube#7]
Running a docker container with a valid download path on the host that has +W +R permissions, I immediately get an [Errno 13] Permission Denied: /downloads/<filetodownload>

Startup command like:
sudo docker run -d -p 8081:8081 -v /home/myuser/Downloads:/downloads --user 1001:1001 alexta69/metube

**Comment by alexta69** [comment]
@codepoet80 You're specifying that the program will run with uid 1001. Does your user ("myuser") indeed have this uid? In many cases it's actually 1000, it all depends on how you set up your system, so verify that. (Type "id" and it will show you your uid.)

**Comment by codepoet80** [comment]
Thanks for responding, its definitely a permissions thing. You're right, my user was 1000, not 1001 -- but I got the same error with that too. In fact, the only user it would work with was 0, and I'm not sure the implications of running this as root.

**Comment by alexta69** [comment]
@codepoet80 Well, it has to be some sort of ownership / permissions issue -- either the directory isn't owned by that user or its permissions are set wrong or something like that.. did you change the gid to 1000 as well? ("--user 1000:1000")
You can run it as root, it's pretty isolated inside its docker container, but it's not considered best practice.

**Comment by codepoet80** [comment]
Changing ownership of the download folder and setting permissions to drwxr-xr-x resolved this issue.
Thanks!

**Comment by alexta69** [comment]
@codepoet80 Glad to hear! :)
