### ISSUE TITLE
"Host not found" with Swag subfolder config

### ISSUE THREAD

**Issue by jgillman** [alexta69/metube#74]
I'm running MeTube in a docker container and I'm trying to use the swag subfolder config but getting a "Host not found" error which _I believe_ is an issue around the upstream_app name (`metube`).

I've got MeTube configured and working via IP address. I can successfully hit `http://192.168.1.2:8082/metube/` and MeTube loads (I had to change the port because 8081 was taken by another container). In the [swag subfolder conf for metube](https://github.com/linuxserver/reverse-proxy-confs/blob/master/metube.subfolder.conf.sample) I updated the port to 8082 but it doesn't resolve.

I tried changing the container name from `MeTube` to `metube`. I also tried changing the docker container network from the default "Bridge" to Linuxserver's "lsio" network that they use for all their containers but no change their either.

What DOES work if I change `$upstream_app` from `metube` to the IP on my network `192.168.1.2` it works. So the app is reachable and responds via the subfolder/path but there's something funky with the named container.

---

I'm not sure where to continue debugging but happy to try any permutations or post most info if I overlooked something.

**Comment by alexta69** [comment]
You have to make sure your swag container and the metube container run in the same network. Are you running them via docker-compose or by other means? You can use the `docker inspect` command to see all the details about a container, including its network. Once you put them in the same network, it will start working for you.

**Comment by jgillman** [comment]
Thanks for taking a look!

I've switched them back to the same docker network (`lsio`) but no change after restarting both the swag and metube containers. I'm running them in an Unraid system so I'm not exactly sure what's coordinating the containers in the background so I realize this is understandably a bit out of scope for your normal debugging.

<img width="961" alt="Screen Shot 2021-11-06 at 6 07 31 PM" src="https://user-images.githubusercontent.com/172217/140625210-f5c7bec3-8fcc-4858-89f9-6dd33528ba81.png">

From what I can tell the proxy config is super standard as is the docker container config for metube so I'm a bit at a loss. I'll poke around in the Unraid forums and Discord as well.

**Comment by alexta69** [comment]
I understand. It's indeed out of scope for me, as I'm not an Unraid user. Since it works for me and others who don't use Unraid, I assume it's something specific about Unraid. Good luck, I hope you find it quickly! I'll close the issue here for now.
