### ISSUE TITLE
what's Errno -3 ?

### ISSUE THREAD

**Issue by 0x01x0** [alexta69/metube#75]
INFO:ytdl:adding https://www.youtube.com/watch?v=j_5_Zv01bqU
WARNING: [youtube] Unable to download webpage: <urlopen error [Errno -3] Try again>

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] Unable to download webpage: <urlopen error [Errno -3] Try again>

WARNING: [youtube] Unable to download webpage: <urlopen error [Errno -3] Try again>

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] <urlopen error [Errno -3] Try again>. Retrying ...

WARNING: [youtube] Unable to download API page: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again')))

ERROR: [youtube] j_5_Zv01bqU: Unable to download API page: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again')))

INFO:aiohttp.access:172.16.100.99 [01/Nov/2021:06:34:16 +0000] "POST /add HTTP/1.1" 200 430 "http://172.16.100.3:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
WARNING: [youtube] Unable to download API page: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again')))

ERROR: [youtube] j_5_Zv01bqU: Unable to download API page: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again')))

**Comment by alexta69** [comment]
This URL downloaded fine for me. It looks like you have some network issues.
