### ISSUE TITLE
Monitor subscriptions for auto-download

### ISSUE THREAD

**Issue by MadsMighty** [alexta69/metube#76]
MeTube fits so many of my needs perfectly! One of the few interfaces to properly take my yt-dlp output and create the correct folder/file naming scheme.

The only issue I've run into is I'd love to have it auto-download new videos from the channels I'm downloading from. That would let all of my Youtube videos auto download in the correct format, then auto-add themselves to Plex as well.

Fantastic work on this project so far and thank you for any feedback or info you can provide.

**Comment by alexta69** [comment]
Hi @MadsMighty ,

I'm glad you like the software!

To tell the truth, I don't envision it going in the direction you're describing, something like that would be a very different piece of software, more like Radarr/Sonarr. Perhaps there's already other software that does this?

In any case, I'll leave the issue open for now, for reference for others as well.

**Comment by MadsMighty** [comment]
Hi @alexta69 

Thank you for the reply! I understand if that functionality isn't a part of your project roadmap for sure.

I do wish that ANY of the other PVR style youtube downloaders worked with YT-DLP output commands nearly as well as your project does :/ MeTube perfectly formats the file names for Plex to read the channel and videos properly, and no other service can manage that despite using YT-DLP.

This is totally above and beyond and there's no need to answer, but would you know of a project with PVR functionality that can accept the YT-DLP output properly? Here's what I'm working with: 

`%(channel)s - [%(channel_id)s]/%(title)s - %(upload_date)s - %(season_id)s - [%(id)s].%(ext)s`

**Comment by alexta69** [comment]
Hi,
Sorry, but I'm not familiar with other such projects...
