### ISSUE TITLE
Add download over link parameter

### ISSUE THREAD

**Issue by thobbiit** [alexta69/metube#77]
Hey, I really love metube and I'm using it daily. I have written a python script to automaticly check some playlists and return the links of the videos I haven't downloaded yet. Would it be possible to add the link to the downloads by just adding it at the end of the link? like metube.mydomain.com/url=youtube.com/id

I'm sorry if the answer is obvious, I'm very new to working with stuff like this

**Comment by alexta69** [comment]
Hi,
There are bookmarklets in the README which do exactly that. Check them out and see the exact URL and parameters that they use to do what they do.
Good luck!
Alex

**Comment by thobbiit** [comment]
> Hi, There are bookmarklets in the README which do exactly that. Check them out and see the exact URL and parameters that they use to do what they do. Good luck! Alex

Sorry that I'm asking you again. But I always get an Http Error 405 and in the log of metube it says:
```
NFO:aiohttp.access:<MyIP>` [11/Nov/2021:08:22:23 +0000] "POST / HTTP/1.1" 405 213 "-" "python-requests/2.24.0"
```

Do I somehow have to allow post requests? I have tried it with http to the intern ip adress and also over https nginx reverseproxy with a domain (same result)
