### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno 113] Host is unreachable>

### ISSUE THREAD

**Issue by mkopnsrc** [alexta69/metube#78]
ERROR: unable to download video data: <urlopen error [Errno 113] Host is unreachable>

My metube recently started failing for any youtube videos. I've also tried passing cookies.txt but it has no impact. This was working 4 days ago.

I'm running metube on docker inside unraid server. Please let me know what can I do to help resolve this issue.
Thanks.

**Comment by alexta69** [comment]
Hi,
It looks like you have connectivity problems. I can't know why, but it looks pretty certain that it doesn't have anything to do with MeTube (which hasn't even been updated in the last few weeks). I'm not an Unraid user, and I don't know much about it, so I can't really help in debugging it, sorry.
