### ISSUE TITLE
metube stops to download videos after latest update

### ISSUE THREAD

**Issue by garanda21** [alexta69/metube#79]
Hello, 

After yesterday update in docker, application do not download videos anymore, when you paste youtube URL, click ADD, and video never starts to download, like this image:

<img width="1200" alt="Captura de pantalla 2021-11-13 a las 11 25 12" src="https://user-images.githubusercontent.com/9530250/141615206-5a065cd4-e814-4ed3-bc09-0e98c43873ef.png">

And when you check logs inside the docker not much info to help:

`today at 11:24:59 INFO:ytdl:adding https://www.youtube.com/watch?v=OushE7mq0Ak
today at 11:25:00 INFO:aiohttp.access:172.17.0.1 [13/Nov/2021:10:24:59 +0000] "POST /add HTTP/1.1" 200 268 "http://192.168.1.123:49176/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"`

If I install a previos version it works perfect again.

Any clues? 

Thanks in advance.

**Comment by alexta69** [comment]
yes, I just saw this today. I reverted the updates, pull the docker image again. I'll investigate it, and push the updates again when it's resolved.

**Comment by Tsaukpaetra** [comment]
Just curious what the fix was? I'm not using the Docker image and after noticing the python version was bumped to 3.11 re-created the virtual environment, but it fails to launch the yt-dlp portion, though calling it manually does indeed work.

**Comment by Tsaukpaetra** [comment]
Nevermind, apparently the frontend wasn't building properly (and/or was cached in a weird state).
