### ISSUE TITLE
support of download-archive in YTDL_OPTIONS

### ISSUE THREAD

**Issue by awirthy** [alexta69/metube#80]
does your script support download-archive in YTDL_OPTIONS?
Also is the following line valid when using YTDL_OPTIONS?

'YTDL_OPTIONS': '{"playlist-end":"5","restrict-filenames":true,"add-metadata":true,"merge-output-format":"mp4","abort-on-error":true,"abort-on-unavailable-fragment":true,"no-overwrites":true,"continue":true,"write-description":true}',

**Comment by alexta69** [comment]
The options supported by YTDL_OPTIONS can be seen [here](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L176), they're passed to yt-dlp directly, so please consult the yt-dlp docs about them, metube just passes them as is.
