### ISSUE TITLE
ERROR: unable to open for writing: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by yangchris4** [alexta69/metube#84]
**download fails**  
![Snipaste_2021-11-25_12-51-41](https://user-images.githubusercontent.com/13220804/143399034-83c62d73-bb32-4599-81e4-39c174390a0f.png)

**here is my  compose.yml**
![微信截图_20211125131407](https://user-images.githubusercontent.com/13220804/143398487-5b185e42-7318-4dbd-939f-246b9629b416.png)

**i added  --privileged: true  to solve,but useless.
and here is the detail log** 

![微信截图_20211125153632](https://user-images.githubusercontent.com/13220804/143399177-4de0d268-4230-4274-a0a0-841f9c00992f.png)

**Comment by alexta69** [comment]
You're running the container as user 1001. Make sure that the folder /root/downloads/youtube is writable for user 1001, or alternatively, change the `user:` parameter in docker-compose to a UID which has write permissions in that directory.
