### ISSUE TITLE
404: not found  when download link

### ISSUE THREAD

**Issue by pstandard** [alexta69/metube#89]
Hello,
  I run metube in Centos 7. The link can't be download , show 404 not found. 

  The url:
`<a _ngcontent-mgx-c28="" target="_blank" href="download/../downloads/German FM Baerbock announces new 'value based' approach towards China _ DW News.mp4">`
I think it 's problem in href. The correct one is 
`href="download/German FM Baerbock`

This is the parameter I create the docker:
docker run -d -p 8081:8081 -v /root/downloads:/downloads --user 1001:1001 alexta69/metube

**Comment by pstandard** [comment]
Ok, I resolved this problem by setting env to `-e DOWNLOAD_DIR='/download'`. Please close this issue.  At the same time, the directory also must be changed from downloads to download.

**Comment by Animosity** [comment]
This solution worked for me also, thanks!

Previously had a volume mapped as `/my/path:/downloads` only.

Changed the volume mapping to: `/my/path:/download' and added environment var for `DOWNLOAD_DIR=/download`

Can now view the downloaded files in browser

**Comment by alexta69** [comment]
I've pushed a fix for the issue, so you don't need to do these manual changes any longer. I'll be glad if you guys could test it (once it finishes building) and see if it resolves the problem you saw!
Thanks
