### ISSUE TITLE
Web app just says "Connecting to server..."

### ISSUE THREAD

**Issue by zeko9381** [alexta69/metube#9]
I've followed your instructions for manual install. Here is the log:

INFO:ytdl:waiting for item to download
======== Running on http://0.0.0.0:8081 ========
(Press CTRL+C to quit)
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:28 +0000] "GET / HTTP/1.1" 304 140 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:28 +0000] "GET /runtime-es2015.js HTTP/1.1" 304 140 "http://192.168.1.123:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:28 +0000] "GET /polyfills-es2015.js HTTP/1.1" 304 140 "http://192.168.1.123:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:28 +0000] "GET /styles-es2015.js HTTP/1.1" 304 140 "http://192.168.1.123:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:28 +0000] "GET /vendor-es2015.js HTTP/1.1" 304 140 "http://192.168.1.123:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:28 +0000] "GET /main-es2015.js HTTP/1.1" 304 140 "http://192.168.1.123:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
ERROR:engineio.server:The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:29 +0000] "GET /socket.io/?EIO=3&transport=polling&t=NR8U80t HTTP/1.1" 400 269 "http://192.168.1.123:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
INFO:aiohttp.access:192.168.1.28 [03/Jan/2021:13:38:30 +0000] "GET /socket.io/?EIO=3&transport=polling&t=NR8U8Nz HTTP/1.1" 400 269 "http://192.168.1.123:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"

**Comment by alexta69** [comment]
Fixed a dependency that made this happen. Thanks again!

**Comment by romquenin** [comment]
hello @alexta69 , i have the same kind of problem on latest version running on docker.

INFO:aiohttp.access:192.168.2.23 [07/Sep/2023:14:23:23 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Ofm1hza&sid=REDACTED HTTP/1.1" 200 210 "https://metube.me/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
INFO:aiohttp.access:192.168.2.23 [07/Sep/2023:14:23:48 +0000] "POST /socket.io/?EIO=4&transport=polling&t=Ofm1o3y&sid=REDACTED HTTP/1.1" 200 302 "https://metube.me/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

Any help would much appreciated.
Thanks.

**Comment by PikuZheng** [comment]
> INFO:aiohttp.access:192.168.2.23 [07/Sep/2023:14:23:23 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Ofm1hza&sid=REDACTED HTTP/1.1" 200 210 "https://metube.me/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

It looks like you configured https://metube.me/ as metube website name, it doesn't work because https://metube.me/ is a real website. Maybe you need to use local ip instead of metube.me

**Comment by romquenin** [comment]
Hello @PikuZheng, i have redacted my website name for MeTube. I run it on my synology nas with docker, the adress looks like this: https://metube.REDACTED.i234.me/

**Comment by PikuZheng** [comment]
> 你好@PikuZheng，我已将我的网站名称修改为 MeTube。我用docker在我的synology nas上运行它，地址如下：https: [//metube.REDACTED.i234.me/](https://metube.REDACTED.i234.me/)

I don't think this can work. It is recommended to use local ip to test first. If you need to use a domain name, make sure all computers can resolve it correctly

**Comment by PikuZheng** [comment]
> Hello @PikuZheng, i have redacted my website name for MeTube. I run it on my synology nas with docker, the adress looks like this: https://metube.REDACTED.i234.me/

I don't think this can work. It is recommended to use local ip to test first. If you need to use a domain name, make sure all computers can resolve it correctly
