### ISSUE TITLE
Help : To work on Heroku

### ISSUE THREAD

**Issue by dishapatel010** [alexta69/metube#91]
i have tried to add [Heroku-support](https://github.com/dishapatel010/metube/commit/59fb82626a5cbf26c99b993f23ae3bc4bcc0bfca). Which works fine to deoply app.
after runing  start cmd i.e. `python3 app/main.py` it throws **[error](https://pastebin.com/raw/xJy5tb54)** & crashes.

**Comment by dishapatel010** [comment]
[Sloved](https://github.com/dishapatel010/metube/commit/2729f4227b7aef74be9c9e7783ac4e3b4d2c9d0c)

**Comment by patwari6862** [comment]
Bro can we deploy on heroku?

**Comment by dishapatel010** [comment]
> Bro can we deploy on heroku?

[Yes.](xmetube.herokuapp.com)
