### ISSUE TITLE
Quality "Best" for format "MP3" downloads lowest bitrate

### ISSUE THREAD

**Issue by kleest** [alexta69/metube#93]
When selecting "best" as download quality with format "MP3", the lowest bitrate is used and `ffmpeg` encodes the video as follows:

```
Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 128 kb/s
```

![quality selection](https://user-images.githubusercontent.com/6516878/146839646-c8177a22-d578-48a3-ac9f-3eefbc5a18e3.png)

Selecting a quality explicitly encodes the video correctly.

I think the culprit is that `preferredquality` is not set if "best" is selected as download quality: https://github.com/alexta69/metube/blob/e635a4a7f59734b4881cb7ef24b3f54c106b5a19/app/dl_formats.py#L61-L62

In the ffmpeg post-processor code, the `preferredquality` is parsed in two possible ways: If the value is greater than 10, it is assumed to be a bit rate in kb/s. If less than or equal to zero, it is assumed to be quality factor, where 0 means best quality and 10 means worst quality, see https://github.com/yt-dlp/yt-dlp/blob/adbc4ec4bbfbe57842049cf9194384480f534859/yt_dlp/postprocessor/ffmpeg.py#L405-L425.
If `preferredquality` is not set, no bitrate or quality flag is passed to ffmpeg, so that ffmpeg uses 128 kb/s (somehow).

I would suggest setting `preferredquality` to `0` if "best" is selected in the frontend.

**Comment by alexta69** [comment]
Thanks! I've updated the code accordingly. Let me know if it solves the problem

**Comment by cheneraie** [comment]
Sorry, but I have the same issue. If "Best" is selected, the mp3 file is encoded with a 32 kb/s bitrate.
