### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by iball** [alexta69/metube#94]
Just updated my metube stack tonight after adding in cookies.txt parameter and now getting the following error starting the container:

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' on line 60
Traceback (most recent call last):
  File "app/main.py", line 11, in <module>
    from ytdl import DownloadQueueNotifier, DownloadQueue
  File "/app/app/ytdl.py", line 7, in <module>
    from dl_formats import get_format, get_opts
  File "/app/app/dl_formats.py", line 64
    })
    ^

I'd fix it myself but since the container won't start now I can't get in and remove the "extra" }

**Comment by alexta69** [comment]
Doh! Made a silly typo in the code. Thanks for pointing it out. Fixed now, build will be ready in probably half an hour or so.
