### ISSUE TITLE
metube cannot download tver.jp's content.

### ISSUE THREAD

**Issue by choime** [alexta69/metube#95]
yt-dlp supports tver, but on metube an unsupported resource "url_transparent" message is output.

I installed the docker version of metube and confirmed that the contents of the same URL can be downloaded by yp-dlp in the container with the docker exec command.
</br>
</br>

![2021-12-22 223912](https://user-images.githubusercontent.com/75112257/147101930-fae92525-8e59-41ef-a005-ad3453f78df4.png)
</br>
</br>

![2021-12-22 224033](https://user-images.githubusercontent.com/75112257/147101939-6401ee37-b892-4411-b224-bc8509580d31.png)

**Comment by alexta69** [comment]
Fixed, try the new build when it's ready and let me know if you're still seeing issues
