### ISSUE TITLE
Chrome extension doesn't add video to metube, only opens the page

### ISSUE THREAD

**Issue by 3shirts** [alexta69/metube#97]
I have the extension installed and pointed it to my instance of meTube (running in a docker on my server) but all it does when I click the extension is open the metube webpage (like a bookmark) it doesn't send the video to it or even paste the link in the box.

**Comment by alexta69** [comment]
Are you running MeTube behind an HTTPS reverse proxy? It's required for the extension to work, I think.
In any case, please refer to the extension author for help with the extension.
